{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservation-details-usecase/0.9.1/reservation-details-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "reservation-details-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservation-details-usecase-iosArm64Main-0.9.1.klib",
          "url": "reservation-details-usecase-iosarm64-0.9.1.klib",
          "size": 4951,
          "sha512": "78b2766d8b2b2bc899ae55fc8a6a511dfb9abf6c2f7cc1b555729fd7ed9b70ade82ace2c5c45b2949bf6d42233297741fe929962ae3d35b0b726ad93ba00cabb",
          "sha256": "375812d8998d526c6bcfa9a953e03c9670a2e1fbaa216702173bd90e6528827b",
          "sha1": "08b932e8d0879e3a29e70f8f90c3b824b9089f23",
          "md5": "63cbbe39c599c5aca909444e20c3389f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservation-details-usecase-iosarm64-0.9.1-metadata.jar",
          "url": "reservation-details-usecase-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "3fea22f6215854d15492a5407d94b136958a388ffb1cb3762f9266537c4f9481396472a77762c595b3a4161c4213f301d7072aa75d2eef6796e54e6ee927af00",
          "sha256": "19961b66331547318e3b140331226360bc419b6855dab80a2e66a9492ddd882f",
          "sha1": "1a36220a16e00aa88fc47c31898f4409b185b36e",
          "md5": "cfc31a3b57a1f329a6b669d951f5f7c0"
        }
      ]
    }
  ]
}
