{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-domain/0.7.0/user-profile-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-domain-iosX64Main-0.7.0.klib",
          "url": "user-profile-domain-iosx64-0.7.0.klib",
          "size": 25119,
          "sha512": "46fb042a8f7444b70b2a05ecf8d898500bad4fb6c6295d8587bb486e366fb2fab5ac7a2db1c2c89a0a7ee4651f21b247c1899e5820068b058a76fe20ea22eca1",
          "sha256": "614ef5dc4719cccf7d2129ec7637a6ac69eda8b9f9092605620ea2626b59011c",
          "sha1": "84c0fa88cb88baf9b3a2839b0fa95bf1458d6a4f",
          "md5": "6c0d15418fa500f0b5cdca9692d8678c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-domain-iosx64-0.7.0-metadata.jar",
          "url": "user-profile-domain-iosx64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "c10a877a87534cbec5c6086096c3c05d32447a61985d7d1f05cc8070266fc2c0352d954d585009cd622b8aba69c4eeab278420100bafcf2372e1600b0cc1bece",
          "sha256": "ea278e85f9271524c5d53c692e44ee0806b656ef7733bd0eaf1c1d85eb0e987b",
          "sha1": "b4672e14c8a6c298238a0565df71d5c971d93633",
          "md5": "0e2b57433f5d75d799ff77504f4d2f6b"
        }
      ]
    }
  ]
}
