{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-domain/0.7.0/user-profile-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-domain-iosSimulatorArm64Main-0.7.0.klib",
          "url": "user-profile-domain-iossimulatorarm64-0.7.0.klib",
          "size": 25197,
          "sha512": "d1ec1cd26e4ce6973f2d035f0a6487396def7e8f9a33dca25111d91edce157b24fe558f8bc8d3fee2e40830925eb1fd22ffb80308f44cff6f9e6fd8914818f90",
          "sha256": "616db06aee8ba524d115eec45a9d949777d6d9945c7b0760b51bb9aa802cc768",
          "sha1": "934ea2d37cb40c0b203226d6043a131895a9333f",
          "md5": "3f34c665a607a577a61689250c4ccf78"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "user-profile-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "c10a877a87534cbec5c6086096c3c05d32447a61985d7d1f05cc8070266fc2c0352d954d585009cd622b8aba69c4eeab278420100bafcf2372e1600b0cc1bece",
          "sha256": "ea278e85f9271524c5d53c692e44ee0806b656ef7733bd0eaf1c1d85eb0e987b",
          "sha1": "b4672e14c8a6c298238a0565df71d5c971d93633",
          "md5": "0e2b57433f5d75d799ff77504f4d2f6b"
        }
      ]
    }
  ]
}
