{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coupons-usecase/0.7.0/coupons-usecase-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "coupons-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-iosX64Main-0.7.0.klib",
          "url": "coupons-usecase-iosx64-0.7.0.klib",
          "size": 4877,
          "sha512": "b9836999f4eae428fb64e596d033d37099eb515747fd62591fd5304d544f34b3015143b69ab7ae371832515957a25a8246436648d8d11affaf45018f232914cb",
          "sha256": "50ef1c7ed9a671a583aade1e8af286788ba61adebd435abef6f7eadb288c98a8",
          "sha1": "10d45693137ec4490405fa4489852ee61bb67d79",
          "md5": "b41796ddff9d0c11732bc51590dcd407"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-iosx64-0.7.0-metadata.jar",
          "url": "coupons-usecase-iosx64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "677b6d61a37549b91908d5a1afc377f0cc19649167cec0df33153530743441aebb73f8acec4a8a00b45db8377c228f0dbc623cafb6f98ccd4f29a647b12a7cf7",
          "sha256": "1551aeac126ba0bd04f3fdc9575da0086f9f2f2aef7316d4e4d0471429b43f0a",
          "sha1": "5ae026736ba26e8876d8365b41e3cfee50af7278",
          "md5": "d440f6643801a807095e21b25eff2a0e"
        }
      ]
    }
  ]
}
