{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-data/0.7.0/pricing-data-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "pricing-data",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-data-iosArm64Main-0.7.0.klib",
          "url": "pricing-data-iosarm64-0.7.0.klib",
          "size": 53266,
          "sha512": "2de3aa9a490a4104812254751f8bdc67a3b40985175d3d7bac7eed2c29e6ca3128134bd5650ad216824ede21187dd6e47c397edf70546ac58d7438bae825b177",
          "sha256": "77ba925aa196dd2a208b7aa964ae34b780e3d0b8f30d2698e881c9216f8d72d9",
          "sha1": "9d1a0871d4901828b70c802d07b2b8f9104548e2",
          "md5": "e4144f7d9decfe47c38450a3b31b580d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-data-iosarm64-0.7.0-metadata.jar",
          "url": "pricing-data-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "15aa596054fbcdce0eea85d9a81b6afbb3ff617fd7c2cf5b747762f6bb19c9c831fb2956697035b843460edb695ac5202b1a519bf7de2b0b12e37b1464572b21",
          "sha256": "ac8d9b819f37c10b716473d6e7c20b1b2626b6dee1c497e85fbc3af202ce9f02",
          "sha1": "fa1690047a61ab5b8ac71fa51e2cbc766bcb2f39",
          "md5": "d79c37f52e4749118335ccea9debddc1"
        }
      ]
    }
  ]
}
