{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-usecase/0.9.1/amenities-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "amenities-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosX64Main-0.9.1.klib",
          "url": "amenities-usecase-iosx64-0.9.1.klib",
          "size": 4753,
          "sha512": "1c466075134551f9ff9edca64c597b06e2b7e5216cb02d4fe3f92a5053b3124df7020665e40535b14aa5c3ea734b09828b49a1af45e648e7e1a5bb283fc37746",
          "sha256": "de1b12719d19458b34f390f02b361dabc1ba8071780f403ec22f2d896329f9fe",
          "sha1": "6faa47937531c34052c68b71d70d2e48e28a2e5e",
          "md5": "8769b588f6f6a2017be4d01b6b296a22"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosx64-0.9.1-metadata.jar",
          "url": "amenities-usecase-iosx64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "5d932dee3613387bce447bcd4828c60d5fd5ca4e148a62ab0175ecdf3b4b107a3d77882ea43c12770da4f5faeaa3c7ca784e2a251e2fd7f60bc7faa53442df0e",
          "sha256": "8aa20184aa17240b863e75c9b008ef5a6337169bc093fb00189ab073b7e9d450",
          "sha1": "2d1500903ca1b6303fbdc428887b200870b0c20d",
          "md5": "7272f124cb185a18ba601ac077c1de27"
        }
      ]
    }
  ]
}
