{
  "formatVersion": "1.1",
  "component": {
    "url": "../../local-storage-data/0.8.0/local-storage-data-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "local-storage-data",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosSimulatorArm64Main-0.8.0.klib",
          "url": "local-storage-data-iossimulatorarm64-0.8.0.klib",
          "size": 8676,
          "sha512": "9e9e768b2d7aa8537c7427311f687339bc7b91525fbf5e5a8830fd2181a8467f77ca53c597f283c0a60f7040fe1ba66d0252a655bb6787c0a84ccb8d47e025d8",
          "sha256": "7571cb97c632f28106cabf2a839f3a70cf42e5e587f41e2542ab6b3aa75b3e3a",
          "sha1": "f8b284a8bb164bb02985b4d07906d60a1882b885",
          "md5": "4f079e0d7a6b7d046eecebb42f06481f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "local-storage-data-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 2471,
          "sha512": "1559aa54e2f83ad58a2e25f115a22acaba06ecd8712230acf7ee6d84109da46aa44966ca3aa143ce71bb12df90dbc960bd806b330f8655fad8f0ffcc0c4c02e5",
          "sha256": "39ba76177fe64c74cf20ebd208ed9802646e0ff13dd7108759a70981f6a020b4",
          "sha1": "026e80138a4b0f3f1a5e9f67f8e08d38099894b8",
          "md5": "bea509564bf865b081cdd9f576fb7d88"
        }
      ]
    }
  ]
}
