{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-di/0.8.0/sdk-di-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-di",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "sdk-di-iosArm64Main-0.8.0.klib",
          "url": "sdk-di-iosarm64-0.8.0.klib",
          "size": 7236,
          "sha512": "a82d05ef8a5dcda1cd7f4e43240f162ed66fee4c3aa3dc99c637cbe8efa92edbca9775ea77c6d2a5fa8d89d32360b526b4b799dd1abcb7767be61d32e08aa59a",
          "sha256": "744afedd202664db2579a26710fd91cf0b8a98baf91a312acf21e12b9249d83e",
          "sha1": "729eadb67d88bfb7d171e098f4e0ea0a8f69cd79",
          "md5": "69519c8d64f9341d5e48d1fc76c6d012"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "sdk-di-iosarm64-0.8.0-metadata.jar",
          "url": "sdk-di-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "2c3796bea6548f2c7b793fb9c000a2b6211afd6f7896630f8d7ea9f845ef7501bc89608cf1128351b3f0522dfab46397678b3a378f956e98cb38a9e4e8e35f13",
          "sha256": "5ab0f29d5a5d554c9b6ac0fb7fae9befb854f07bc18b77477cf476e4af51304c",
          "sha1": "e4fc105cc92d4946bf05285fc9036deb036b623f",
          "md5": "c1950288ace44940a537a4ccc608ea0b"
        }
      ]
    }
  ]
}
