{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api-config/0.7.0/sdk-api-config-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api-config",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config-environment",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-iosSimulatorArm64Main-0.7.0.klib",
          "url": "sdk-api-config-iossimulatorarm64-0.7.0.klib",
          "size": 39112,
          "sha512": "947cda45e0892ffd60f7323b0b587e9df55fbef6fb73ee443d82a8583ed4356cce603f253feae2655bfaacb0114004eda05b7a3ada30a7e194e90efb7a0b5cd8",
          "sha256": "f50bf2acdbd57ec3891ff1ad69114aa48331b47a343a460e755d2f22783f4993",
          "sha1": "f25c95e1011a80031879f2ad4ef096caed519603",
          "md5": "93dc6b50621d0fc5ab4f511a38f6e01d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config-environment",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "sdk-api-config-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "ca49bbb06deae571fe3f3bb357d42110d0319b5f4573f066d05cceee15974421f8e9333390e6f6c88ab28bbd0b4afc7e06f428479331e0607a7d0d6d121534ae",
          "sha256": "adca7e864f6039d90faa35bafdf406c122997b17209244bfd1fc5f8f6d7d4922",
          "sha1": "8e8678f00ba63f4e7bdbb23b5415ee7493d37cf5",
          "md5": "6c88c33dc3524d5773f828d76d51a794"
        }
      ]
    }
  ]
}
