{
  "formatVersion": "1.1",
  "component": {
    "url": "../../searched-locations-history-domain/0.9.1/searched-locations-history-domain-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "searched-locations-history-domain",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-domain-iosSimulatorArm64Main-0.9.1.klib",
          "url": "searched-locations-history-domain-iossimulatorarm64-0.9.1.klib",
          "size": 31239,
          "sha512": "d98c1d39437861c68e29c858c6b4b328c6d59ab8e8bcd87e3956e100b77cae93f57c383c2415d2a3056997ea830dc21746f5691fecb100ff09ddaf5efca3b87a",
          "sha256": "e1fc89d8c2849cff8cc2fa62311b121121796ea5b88c16ad12d452e3aaedb4e6",
          "sha1": "397ea4cbd834d2e0f596ddb88b2bbc0b316188cd",
          "md5": "7a34c9f440b6428545804e66bff74fba"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-domain-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "searched-locations-history-domain-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "85ef3ef2f39b928ecb7a74aa942641100559903e62edd4c622968a1d64c8c4158321a1ac642e2d5b4fc2390a4a4420849237ceca4c88024f2a440c780214e278",
          "sha256": "ba6c1675772ac89a597881cffb2621953c1c675df6aa80e0cd86831068bb9912",
          "sha1": "13dd4ed19bc1ba9434db168dd64dd5321be47686",
          "md5": "cf46299b5ab164eb263e8eb72e0e1fd8"
        }
      ]
    }
  ]
}
