{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api-config-environment/0.9.1/sdk-api-config-environment-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api-config-environment",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-environment-iosSimulatorArm64Main-0.9.1.klib",
          "url": "sdk-api-config-environment-iossimulatorarm64-0.9.1.klib",
          "size": 6786,
          "sha512": "be2fd76db6add2e0a62a56388ed5466d35dac080977eef6ff91ed76a3d3c2f8968ebd4bfb8b3bdae9adb403a016d2de4a9521279e9fbaaad95b1f9f31a38d6d2",
          "sha256": "823a1ed60541deb5ac74b52e382e193db6121ee1a5369759fa1bc7b2e80eb198",
          "sha1": "4317c38ee8e80995cf88cfc21eb0f195a0cf08fd",
          "md5": "05328a11d66f3475d99794671e175035"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-environment-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "sdk-api-config-environment-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "42406702accfaab4ebe05880e0ac041ea6b41ebe981669c98c98131c0a2bc9e221a080d540f1728209462cde83b319669706a21d130237c9e87d91db55384846",
          "sha256": "9c755e5ca86de5ca07355e7403c7e52a7d8bb7f237afdd95907420aface1f862",
          "sha1": "ea1ff4f4c35973cb90921fe76ff96e92e8579442",
          "md5": "deada6d8c48c8004d2d41c0c4f98a28d"
        }
      ]
    }
  ]
}
