{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-data/0.9.1/countries-info-data-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-data",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosSimulatorArm64Main-0.9.1.klib",
          "url": "countries-info-data-iossimulatorarm64-0.9.1.klib",
          "size": 16357,
          "sha512": "9d9c1d87c9feeaf7ffab7892e1aff5008872fb5918e6605dc74f372c4db7450fabab082ea9df37264d25665433a17b717bf16f8298b61154ba848054cac8b08d",
          "sha256": "50694050e92796f5c9837ba8480f1be8c84ba0b6f8d1e6f272be66cf67df2182",
          "sha1": "7e59fd1ded7fc5b7db63fe409cf45330d9f78944",
          "md5": "444519fbe48a19b8ce374d0653c27f6b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "countries-info-data-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 3299,
          "sha512": "034411f1e41f377974eb96a4706bb2b8738e544c1a3a7e5b67dbce74b9e3a041853462e9caee1dcec1a81d5e8e1f74d6986dfbbbdcbc0850ffe68245b92ef0ed",
          "sha256": "b9817dfc36751071fff5e3b6d24040099a5e78eb61c8d9bae576a10590f4e218",
          "sha1": "e841a11cf5b5ea8f9151c82010755fa30eed520e",
          "md5": "97cd24613797141bac49ea07fdb5b6fb"
        }
      ]
    }
  ]
}
