{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-domain/0.8.0/countries-info-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosSimulatorArm64Main-0.8.0.klib",
          "url": "countries-info-domain-iossimulatorarm64-0.8.0.klib",
          "size": 15202,
          "sha512": "4259fe5d91e7896aab181f88955964bf1fa702704e142efd4afdd4c345a4ad80dd15482109c3801a78870be959460f556e099ce9ccfd63e1d329b073ad5a6998",
          "sha256": "dafd1aac2e279a98b5d37e94c48e6349a3403aa2306a0b1bab27b02a2eb3b879",
          "sha1": "7f2568f0d05b9130d36433751d6fd5e9f88e0bae",
          "md5": "3b6a4984c0b84b414ed8750a20121a89"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "countries-info-domain-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "9eb585611646f17851870fb295f0ecc7792596df781b2afeda367846459b3859f4e426a15bdf49c4a66b27ad368ee91d317f0de0b6c942f14921222d956e3558",
          "sha256": "a9eb4ec5a5bcfaeaae3c8774b24a35a840989dfa5d53b3f6e4c1fa39586aaadb",
          "sha1": "54bd402112d3372cfe1167030332d26290360155",
          "md5": "abeb9072cd7288214a527ae5c463f56a"
        }
      ]
    }
  ]
}
