{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "locations-domain",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-metadata-0.4.0.jar",
          "url": "locations-domain-0.4.0.jar",
          "size": 10391,
          "sha512": "36eee682be3c30ddd986253583b0ca4af597f53be4a94eec0033b1221a4ec6dd46092c9a5fa6ae4cd8d2a1ac6a9cfefa9ec50fdc21ddee688c9e45fd223f0c12",
          "sha256": "c83a54e65a90286d22873358a5a250d0c30c4f5dc433ae649be373df36f44ef4",
          "sha1": "ad4cee21c502e11846f19f74c2cbca32cd39148b",
          "md5": "8b5530b13e05bf5fab08c5bff7a1de8d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../locations-domain-android/0.4.0/locations-domain-android-0.4.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-domain-android",
        "version": "0.4.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../locations-domain-android/0.4.0/locations-domain-android-0.4.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-domain-android",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../locations-domain-iosarm64/0.4.0/locations-domain-iosarm64-0.4.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-domain-iosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../locations-domain-iosarm64/0.4.0/locations-domain-iosarm64-0.4.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-domain-iosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../locations-domain-iossimulatorarm64/0.4.0/locations-domain-iossimulatorarm64-0.4.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-domain-iossimulatorarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../locations-domain-iossimulatorarm64/0.4.0/locations-domain-iossimulatorarm64-0.4.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-domain-iossimulatorarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../locations-domain-iosx64/0.4.0/locations-domain-iosx64-0.4.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-domain-iosx64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../locations-domain-iosx64/0.4.0/locations-domain-iosx64-0.4.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-domain-iosx64",
        "version": "0.4.0"
      }
    }
  ]
}
