{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coupons-usecase/0.7.1/coupons-usecase-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "coupons-usecase",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-iosArm64Main-0.7.1.klib",
          "url": "coupons-usecase-iosarm64-0.7.1.klib",
          "size": 4890,
          "sha512": "1d1878a19638fcf1b2d3bf141435b042ff29b98a080b2aafc82a6b10a8cf5bcf1ed7fddd850f10815e16bc83b74e31e6b5a19b0070b9a520449a8346845ba75d",
          "sha256": "505a61e959e0d9f74fcc936fe569c0606828c9f716f3bad14c3753ccc75e22c1",
          "sha1": "a98ec9b89a08dad0367e7dedc82b77d258c6aad5",
          "md5": "00171be30022cd9d356fb8ed5a4f63b0"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-iosarm64-0.7.1-metadata.jar",
          "url": "coupons-usecase-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "301e29e77afa5b484f5f5b45017457788061f2462406ab8aef16bc8803dabeb33e58751aecfcb19cbe4408421e8ce07913a7c454e8bec68f720c0580f06752e4",
          "sha256": "8c320cc04a3251005062d9e51ab71e9c811caf95257e864e5575dd0bf3c43eb2",
          "sha1": "23249d46b8f7d03773d752b4eb39ebed5e68d0fb",
          "md5": "d679d8f431449bad5fd3100ea3c1d1e6"
        }
      ]
    }
  ]
}
