{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile.android",
    "module": "reservation-details-ui",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-usecase",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-ui-0.4.0.aar",
          "url": "reservation-details-ui-0.4.0.aar",
          "size": 750813,
          "sha512": "46f2afae589c50bc6a9d0eeb8c6ad0f2b08c249f54951cc265188328e983430c86b345585463c907dc15e877dc83e18b25b41096e078ede88d50c80d67d0dba5",
          "sha256": "e4551989a95548e46347b6551ca0b89c3bed83c790770b2cd6581492bedbcf4c",
          "sha1": "a0e34219036e0f8f5ad295f444a1d24cf48c00d4",
          "md5": "5d8601dd1aa1aa6f625af7221381d239"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "core-ui",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-svg",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.github.jeziellago",
          "module": "compose-markdown",
          "version": {
            "requires": "0.5.7"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "googlemaps-ui",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-compose",
          "version": {
            "requires": "6.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-ktx",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-utils-ktx",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-permission",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie-compose",
          "version": {
            "requires": "6.6.7"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "sdk-analytics-ui",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-di",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-usecase",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-ui-0.4.0.aar",
          "url": "reservation-details-ui-0.4.0.aar",
          "size": 750813,
          "sha512": "46f2afae589c50bc6a9d0eeb8c6ad0f2b08c249f54951cc265188328e983430c86b345585463c907dc15e877dc83e18b25b41096e078ede88d50c80d67d0dba5",
          "sha256": "e4551989a95548e46347b6551ca0b89c3bed83c790770b2cd6581492bedbcf4c",
          "sha1": "a0e34219036e0f8f5ad295f444a1d24cf48c00d4",
          "md5": "5d8601dd1aa1aa6f625af7221381d239"
        }
      ]
    }
  ]
}
