{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "search-domain",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-metadata-0.5.0.jar",
          "url": "search-domain-0.5.0.jar",
          "size": 15126,
          "sha512": "f165100046055e987707a6afdb5430bb6281a80d93845ba8eb1022b2817539b0c22f5cd9a4dc2fe6b25481ea6b92a756fd1e027a09b689bbfc28ec105966151e",
          "sha256": "72d2e8aa85b5ff053834a497fdf7464de13e6fb36f2efdc8e32db96c1f288a65",
          "sha1": "fe6f8504c7f74063766eb242095d9f70ca5e752e",
          "md5": "50f4bb80402cb6d180928ccce08bb76b"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../search-domain-android/0.5.0/search-domain-android-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../search-domain-android/0.5.0/search-domain-android-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iosarm64/0.5.0/search-domain-iosarm64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iosarm64/0.5.0/search-domain-iosarm64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iossimulatorarm64/0.5.0/search-domain-iossimulatorarm64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iossimulatorarm64/0.5.0/search-domain-iossimulatorarm64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iosx64/0.5.0/search-domain-iosx64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iosx64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iosx64/0.5.0/search-domain-iosx64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iosx64",
        "version": "0.5.0"
      }
    }
  ]
}
