{
  "formatVersion": "1.1",
  "component": {
    "url": "../../locations-domain/0.8.0/locations-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "locations-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosX64Main-0.8.0.klib",
          "url": "locations-domain-iosx64-0.8.0.klib",
          "size": 33629,
          "sha512": "276431f44ded511fbe40e44c8679f651a709bbc0ddd822d5dbd82395faa92cc1b7167c4328f46587983abe05d47afb7410f3d290df6e3381565b318a0a2a4508",
          "sha256": "e4ad4f1550a320f614eeb5d1c3d8350f76e145281e034ee55b141cb4696621da",
          "sha1": "e8eebcaa1be9143295c54815d941ddc8ab35cf48",
          "md5": "d436ea923c0246697f5238509d28282c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosx64-0.8.0-metadata.jar",
          "url": "locations-domain-iosx64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "416bf5c8a96e3d16f49d264fcc98577499b2660161efd204e552eeca7143e96d07a4d41011262266493d94edd064bc31b32140e82608fd886c11019cb075650a",
          "sha256": "dd0f5feaac822f731d988bf2953a48ee59b70de75b09ce99b01f97232795132d",
          "sha1": "0faa22fb6855bfc36e17cac2634bc5480f80c700",
          "md5": "83542e6ce7ab51a16c77bcd5f2d53e15"
        }
      ]
    }
  ]
}
