{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-bff/0.9.1/core-bff-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "core-bff",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "mobile-sdk-bff",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-bff-iosSimulatorArm64Main-0.9.1.klib",
          "url": "core-bff-iossimulatorarm64-0.9.1.klib",
          "size": 12160,
          "sha512": "7489946560b5827bb1457ad220d0d4fb0ccb5219408a55a69af08b7357171298e16f5a3097a6c25ce5b5bbbc58207301521c92d74aac958d8eb180bb32a11e6a",
          "sha256": "24e8189fc1e8127c291b03641dedbed1d50756c4e9ecf21295a25798ef028664",
          "sha1": "453f83133840ed18d12313d63a8010d1f3e78b89",
          "md5": "f22f802d2c161a3fc65f61c751550720"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "mobile-sdk-bff",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-bff-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "core-bff-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "900d5d9e701784e5da57bb880b23986a72459edec462edd8498635dcc185c97cb878b7d40f571d3ba82ca67d1cbd07070d8ef8f80d4fd4cfed1638b7fcd88686",
          "sha256": "8ad9bbb64ae30b1e7028e0a92fcb223964a782c4e246bf13580dafbf188a7d97",
          "sha1": "69c09a805d39d5460736bb51679054953b186565",
          "md5": "4d9937ab9ea4062e30fc780ea13354e8"
        }
      ]
    }
  ]
}
