{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-usecase/0.7.0/amenities-usecase-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "amenities-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosArm64Main-0.7.0.klib",
          "url": "amenities-usecase-iosarm64-0.7.0.klib",
          "size": 4911,
          "sha512": "9252dfcd7a60acf7c678b816e1d25561dc5acbaad0a9f1396f0b265e1e7a914fd5ca9638d54303bc93ee5850769492ca2c5bd535ec89152ed50ec7d44166e0d9",
          "sha256": "1010f6198bb21ed6da98b296211616f6e16cb1675acc173472315fc1df9e831b",
          "sha1": "56831ab5a663e9f56d015f97ce286a8b319640cf",
          "md5": "cfe64bec286bca06034c032935554c7a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosarm64-0.7.0-metadata.jar",
          "url": "amenities-usecase-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "293692818dee1641197fea5e22831a4c62b03e629caff71840cb2b54fed745cddaa5800a53eb987df38a360aa7a3f5ab339a9aa80363a09101bd5ea775b1745b",
          "sha256": "f24d8bc91ae4fa9b876408ea5ba99ffd704493c379324d07e186aa556db02e22",
          "sha1": "540680740f51a59b584f844a3877c5f48d91ec3a",
          "md5": "206d20b26b7b7e6b16ff2bb40cb194b9"
        }
      ]
    }
  ]
}
