{
  "formatVersion": "1.1",
  "component": {
    "url": "../../locations-usecase/0.9.1/locations-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "locations-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "locations-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "locations-usecase-iosArm64Main-0.9.1.klib",
          "url": "locations-usecase-iosarm64-0.9.1.klib",
          "size": 4783,
          "sha512": "3dfc52cdd6e70e6baff238509a696636e4d55b286dcb12a249484b1434efaacaee8e7f1462519322a0c6c82e4b9e2cb28afe8ce417bf6999b5ad35d21984f15c",
          "sha256": "130b107b59607a7bd2451b0842bc69b318026fc9e99174dd2495a10d9a64db32",
          "sha1": "52c86b2157953b32b710ab94caa1cdf97901cf45",
          "md5": "33d743582a9da2c5932b795b54c3bf24"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "locations-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "locations-usecase-iosarm64-0.9.1-metadata.jar",
          "url": "locations-usecase-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "5bb76721afc581c43a678327a11ed5aff0bd78953d561c1e319439a9d495d86982dd66fd0ce63ce2697ee85ad5083c4d8458f442a7d2e725409832fad6f40197",
          "sha256": "f8d654b6a55dc1151134eafcf9c726ae7c3712f63a6b5deb549adbbf7c3b6943",
          "sha1": "ec04e6e540cdbded3f429555e34279da1c8e27db",
          "md5": "4a915b50f393d46e426f0a4a02078b71"
        }
      ]
    }
  ]
}
