{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api/0.7.1/sdk-api-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-analytics",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-di",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-iosX64Main-0.7.1.klib",
          "url": "sdk-api-iosx64-0.7.1.klib",
          "size": 11951,
          "sha512": "d099c541a83ca5bf1517a0b00a9b139b20d1c441971de9ddf19a28e7c089093e75cd9948a4bd2343ac8a60b1b0045cb2ffd445b06ea346819941fd9bd3bd37b0",
          "sha256": "a9536c2c5444eded13def6a8105cdb55719c7c64a363f885e0a117d73825ae53",
          "sha1": "b4da3ab90f4e9bd95db44b9d96846e011a0b1dfb",
          "md5": "71e1e65699b28c81c8636cb5251549e4"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-usecase",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-analytics",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-di",
          "version": {
            "requires": "0.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-iosx64-0.7.1-metadata.jar",
          "url": "sdk-api-iosx64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "aa3181a8dd243cf37f4eca4f7367a23db0499f1fc7238b052c24263a905bac63d2b758aa7d934a2d67364d5287d1a602dedd060b4b5a6bdd5231d1ea4995e810",
          "sha256": "c60ccc1dc1d6b1a8942fc96314ac131025259246691e9e702b34454770989fee",
          "sha1": "ec973d14e62dde79834f08a3a9f493167933cdeb",
          "md5": "af8313eab3f0e1182d77ec7522464a1d"
        }
      ]
    }
  ]
}
