{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-domain/0.7.1/countries-info-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosX64Main-0.7.1.klib",
          "url": "countries-info-domain-iosx64-0.7.1.klib",
          "size": 15263,
          "sha512": "83b4f532f0ef313127bf081b90b297320543e65ef9be65c7b16e15fa1f0a2057f33e63af5cfb46cb8fdffe870b1532b9efb1dbc278b839d342beadcb56ceab43",
          "sha256": "4bc417b50ef2ed967f1dacda550c65b2a2d9372aba027ad0fa087329394c6374",
          "sha1": "e7eef375d6c5b45ad64f6dcad590f9af1ddd71e7",
          "md5": "123222b9384a3436fe611b32053ce099"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosx64-0.7.1-metadata.jar",
          "url": "countries-info-domain-iosx64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "bb3892d5c8f1a6236d82f17fa4dae2e042215394cfe1c45a0e0c5ca15d692547ee7c3afc2d1599eb2654503b048325f7e9aee2cf3e6316633ac710c8da014bb2",
          "sha256": "ded1e81d1ebee22429a52543f7886d3193a3eb5280b624be844159c3794aa97a",
          "sha1": "159e9affcd034dd134dee4212e66fea09b6d2b15",
          "md5": "cea67134eb46faadd10cc186e6be4b97"
        }
      ]
    }
  ]
}
