{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-usecase/0.9.1/user-profile-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-iosSimulatorArm64Main-0.9.1.klib",
          "url": "user-profile-usecase-iossimulatorarm64-0.9.1.klib",
          "size": 4931,
          "sha512": "5af40eedc51c9892b4a9ba3e8077ef45c4d7f0d2c134c54e18295ee3b4dd2ad5187f153e0d031db2afc7f9022da9bd649f46443ebf6a34f9a9c134962f0d97cb",
          "sha256": "92745be7f08ac74d995e9954fc0fcaf073bb81e7470c2bc54f5d6b0e1af275ad",
          "sha1": "bd447626d547f988026aa67fc2553f8ccff34603",
          "md5": "3e2dfa2adcf35042c6ffa8d1c8984e24"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "user-profile-usecase-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "0d9fc7600b61b5cb8b05c004b09a1b940d9cbda3113e777423a3842e2e7b1cb1ecae89e55045efd2500d8be518ba9b2d29b66a244f20783bf835659f6be1dba8",
          "sha256": "c588f02c24bb70a9d9d32c284c0b861905314ab33b5d6c5135c453f8fa138eab",
          "sha1": "c3f67c81aa50cbb922dd52528aae5566a6969538",
          "md5": "efc1eeed03038a300bd6867646cf1a12"
        }
      ]
    }
  ]
}
