{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "pricing-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-metadata-0.8.0.jar",
          "url": "pricing-usecase-0.8.0.jar",
          "size": 2475,
          "sha512": "04539d9798474f98a34c54d5d2ff2f199a9686f03fb3d35713ef6bf3f2d438ec07522125279a53a71e53eae83d1b5232122c9512789f8cdb667d5410f8281134",
          "sha256": "64758592c90f968bab24243e9d938bb4dc64e1508a95d03b0f2006ff20441fe3",
          "sha1": "3791be4e2a4792b8c0110aa463f8244e87675bf4",
          "md5": "4bb49f6d8350e2f90fcdb764808508ff"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../pricing-usecase-android/0.8.0/pricing-usecase-android-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-usecase-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../pricing-usecase-android/0.8.0/pricing-usecase-android-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-usecase-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-usecase-iosarm64/0.8.0/pricing-usecase-iosarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-usecase-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-usecase-iosarm64/0.8.0/pricing-usecase-iosarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-usecase-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-usecase-iossimulatorarm64/0.8.0/pricing-usecase-iossimulatorarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-usecase-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-usecase-iossimulatorarm64/0.8.0/pricing-usecase-iossimulatorarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-usecase-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-usecase-iosx64/0.8.0/pricing-usecase-iosx64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-usecase-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-usecase-iosx64/0.8.0/pricing-usecase-iosx64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-usecase-iosx64",
        "version": "0.8.0"
      }
    }
  ]
}
