{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api-config/0.9.1/sdk-api-config-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api-config",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config-environment",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-iosX64Main-0.9.1.klib",
          "url": "sdk-api-config-iosx64-0.9.1.klib",
          "size": 38057,
          "sha512": "f16951caee20bf8b5c443bafb8b39e20d75c5ff863c7c812387ef3c19f1d720ee1188b150d7c3596899e2ce10710229f3f858d81612d5c294c5cf518066001db",
          "sha256": "cbeaea1849981c090b9e726cc70f8d05bd175ba8b1c77b5946ec22de5624c982",
          "sha1": "9b9281af0b296dbe206ddc974bad43fadb28dfbc",
          "md5": "58702f4a04dce7a065ba71474e04c720"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config-environment",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-iosx64-0.9.1-metadata.jar",
          "url": "sdk-api-config-iosx64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "38c9db2b0c0c4eca4066972ba348e6761ec28e75b1673080b837404474b19ff8d9d4f2016e90d1fc474ec295b832e3dd123cf383c69a58b5b5c3b2eb739d05aa",
          "sha256": "52410a78c685cfb76397154976452cfabac3cdd734ce0bfcb68378fcc4eb8bb1",
          "sha1": "278b94d6fa6a03bde71c4d38d9ec68b924ca174c",
          "md5": "b43657a6d52a3a57510dd50f8926e7b0"
        }
      ]
    }
  ]
}
