{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-usecase/0.7.1/amenities-usecase-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "amenities-usecase",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosSimulatorArm64Main-0.7.1.klib",
          "url": "amenities-usecase-iossimulatorarm64-0.7.1.klib",
          "size": 4976,
          "sha512": "5fcac54e3858cd485f37cb4d5852a14c840de5a78235d00a0972122459769160267f87232519d74e58d3abc7229b77c79b21d30a50d915189442abccbfbb2a8b",
          "sha256": "10842dd98cbbd21e7f615c85deaa6a73f6ec07a1723265314c6fef12c1fa462c",
          "sha1": "4e280c99b6fcb4f8b1d60f486d1afc70fe959262",
          "md5": "045d46785c008ce5bd2bf7dba3509237"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "amenities-usecase-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "dfd8dd84c2197526f2866d4bcd63f3dc055b8975cc478bfce5155e0f11a07352d33ddb14a00c24305513945992ca7750d668491042322bd54e0fce1a7b0e8e00",
          "sha256": "55f03a7296df2334cd6f1b7e9de7c83e9597a042b0cc89648127ea163b0d2197",
          "sha1": "7c56ebcaf6ec530e0c55412029e4acc159b431b0",
          "md5": "9532c833160923685a1e8b088b1657d4"
        }
      ]
    }
  ]
}
