{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-data/0.8.0/countries-info-data-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-data",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosX64Main-0.8.0.klib",
          "url": "countries-info-data-iosx64-0.8.0.klib",
          "size": 16279,
          "sha512": "18f5919a6f824d78b0b9b4f13652faaf854a1ba4c6e1f95ec0021d4d4cff53a8d64eaf6a26b8e29c82d2fe7635275a6754f8ad997b188cec4a80f74f726438a5",
          "sha256": "222cbf77cb7d25253b67ed2a5f7411106b12a6f0b68fc4344640520be8b27c28",
          "sha1": "f809f25ac0684e8cce0efa0ed4b48685b9da1614",
          "md5": "e1608950fd2fbe3b10b6781476e0ce4f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosx64-0.8.0-metadata.jar",
          "url": "countries-info-data-iosx64-0.8.0-metadata.jar",
          "size": 3299,
          "sha512": "5a42f891f065fc69fd10c437c539e45c2be1ef5a95dea187c7cee59d8ac5483b119ea78850feeeffb1ec5ba7e5654f76c6a195fc52f2acebb28db34dbf34dbfe",
          "sha256": "953c4896b7d7b8b60a1f9c11b07aa8ff3475012513a1b5ed84791b34cf31c354",
          "sha1": "6ba3fe858597327f439fc83c1a27a65a29bf7110",
          "md5": "4a3269cfed03824257cf32bc4ef9a430"
        }
      ]
    }
  ]
}
