{
  "formatVersion": "1.1",
  "component": {
    "url": "../../searched-locations-history-usecase/0.9.0/searched-locations-history-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "searched-locations-history-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-usecase-iosArm64Main-0.9.0.klib",
          "url": "searched-locations-history-usecase-iosarm64-0.9.0.klib",
          "size": 4890,
          "sha512": "dfcead4001ed638da408e3da2b165b6cd102fc5d4f9d881d5cf7e03c095bd56d586efd12ae20657df4e7aea8508584e6b9c3005f5a26e10a709bf255c4c075c0",
          "sha256": "aeb17f911dc48f6b951faadd4f1631811ea9a16a56c76fb8dc7a24c9187b41b5",
          "sha1": "9d49238f0ede20372f510adc683ff757a46b8dde",
          "md5": "537f6fbe356d52e0fbeedfe34403b8dc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-usecase-iosarm64-0.9.0-metadata.jar",
          "url": "searched-locations-history-usecase-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "1d8033f83946382dd501757506d22e1b6c5dae6c48077d859ef11bc08ef8742fc2b4f68bcd5f9be4e45a7149687c8ba46f351b0b7dc6541d275ff5fa49f76bb8",
          "sha256": "0a16bbe9d63574663fe85c924e207bcf58f485a08cb06cf8eaf3159e80a2e68a",
          "sha1": "c942307fa70b99b4b5c9659314aa31042a74ed1f",
          "md5": "952463ec2ad309d709f2bbac489abdd9"
        }
      ]
    }
  ]
}
