{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile.android",
    "module": "sdk-ui",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "sdk-ui-config",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-analytics",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-0.3.0.aar",
          "url": "sdk-ui-0.3.0.aar",
          "size": 36845,
          "sha512": "5f951b63a574b2f29ca19640bfa8d935977d2ceccedbd586de1c28a671b537d6f706a71594bcfa5163709af75736609d80aef5590afbe6c89c94b1ead19a5415",
          "sha256": "58ce0e801362454fbd8a06e4d58e12d3dc673cd85bb812d22b42a83c15811483",
          "sha1": "30c5061ce45afd5e4535f6a8edd6eb48077391b5",
          "md5": "e2b418875280f40135fcd682168cb309"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile.android",
          "module": "core-ui",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "search-rides-ui",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "prebook-ui",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "prebook-bookingflow-ui",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "authentication-ui",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "myaccount-ui",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "main-ui",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "reservation-details-ui",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "21.20.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-di",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "sdk-ui-config",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-analytics",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-0.3.0.aar",
          "url": "sdk-ui-0.3.0.aar",
          "size": 36845,
          "sha512": "5f951b63a574b2f29ca19640bfa8d935977d2ceccedbd586de1c28a671b537d6f706a71594bcfa5163709af75736609d80aef5590afbe6c89c94b1ead19a5415",
          "sha256": "58ce0e801362454fbd8a06e4d58e12d3dc673cd85bb812d22b42a83c15811483",
          "sha1": "30c5061ce45afd5e4535f6a8edd6eb48077391b5",
          "md5": "e2b418875280f40135fcd682168cb309"
        }
      ]
    }
  ]
}
