{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-usecase/0.9.1/user-profile-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-iosX64Main-0.9.1.klib",
          "url": "user-profile-usecase-iosx64-0.9.1.klib",
          "size": 4852,
          "sha512": "cfaddf773909f198d8a3ad00d2a4b9c7c25fb838afbaeceea844df1802081ba41152f74a1907d532f9fd3981af63a0a11d31c6f817666cfe75b691349fb84c77",
          "sha256": "6fca5fa1e7eb5394247c7c28066d73fc42a5a96555c02386b490dc165e562f28",
          "sha1": "0e0a24375a6055c1f4f7be7c4ae7dc172f5948c7",
          "md5": "fde788932759e243725b9b0f4a4aa1e7"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-iosx64-0.9.1-metadata.jar",
          "url": "user-profile-usecase-iosx64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "0d9fc7600b61b5cb8b05c004b09a1b940d9cbda3113e777423a3842e2e7b1cb1ecae89e55045efd2500d8be518ba9b2d29b66a244f20783bf835659f6be1dba8",
          "sha256": "c588f02c24bb70a9d9d32c284c0b861905314ab33b5d6c5135c453f8fa138eab",
          "sha1": "c3f67c81aa50cbb922dd52528aae5566a6969538",
          "md5": "efc1eeed03038a300bd6867646cf1a12"
        }
      ]
    }
  ]
}
