{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-analytics/0.7.0/sdk-analytics-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-analytics",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-analytics-iosArm64Main-0.7.0.klib",
          "url": "sdk-analytics-iosarm64-0.7.0.klib",
          "size": 28328,
          "sha512": "06c93e900643e132ad0b329ab45a382474c27b9f7a00c3934466959769135f2bd8fa0e33f762ce82e661a7a439e417003f7730d764c3fc58e0fe16e9872a5778",
          "sha256": "438f7b723ce4f024b6a49ca1c6623da0f5389b2464da08fbef045ae59e021b11",
          "sha1": "3ace1da37ae249e3250f28af3ee1b7db1eeeaa8f",
          "md5": "08500930c6ac95598f1367321e475d6c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-analytics-iosarm64-0.7.0-metadata.jar",
          "url": "sdk-analytics-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "0ec2b107cf89411591083cbc9cf05adfd65a7ed72041f2f71f212947787d54886b26153008b960397008e48847ffd8c113f67c543707325149e23e766c15fd9e",
          "sha256": "8342fbe0ce61782a3cc5e117e75af46af2c81b3c7226194c8136ce25ffeae221",
          "sha1": "e07e2bc60acdc481b219c1d41679541e280f34c0",
          "md5": "b5dee93e2d2a2a1efed0df40315f76b9"
        }
      ]
    }
  ]
}
