{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-domain/0.7.0/countries-info-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosSimulatorArm64Main-0.7.0.klib",
          "url": "countries-info-domain-iossimulatorarm64-0.7.0.klib",
          "size": 15341,
          "sha512": "1d8a90a9fe9f941f53f8e288a78745b1a6c5e61d0e96a4a5e3f54456849e053ecda325d596382b780bf7d5c8c885401a56653bc32abcc3b636c16d83f1d332f8",
          "sha256": "3824950e47067a8f68ca7acc156b508bb1423b106d33c61d18a14520e4802f86",
          "sha1": "686d1d248c2b2e8308e9c1e5358b46611155a4a7",
          "md5": "ba238b4b2a157724cffa995d66c2b9c0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "countries-info-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "3de90eefdcb60c672edf2061d8b242bdd6e1fb38d4cff3660b7a72a399ad38ecbc08eb0ab2cabf102b129839f000699ad8185ab6f6dc2d07ffb158329bfa071a",
          "sha256": "8146593157de5e2204a61a83365d5b58d78518802d76d33a22f930a0915c1699",
          "sha1": "83ad5cfc278813629380d047a014c9316d8455f1",
          "md5": "19c787cfa38a5e8dc645a13d2df589a8"
        }
      ]
    }
  ]
}
