{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-domain/0.7.0/authentication-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "authentication-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-domain-iosSimulatorArm64Main-0.7.0.klib",
          "url": "authentication-domain-iossimulatorarm64-0.7.0.klib",
          "size": 44802,
          "sha512": "567a8d4c21d1f0e720e90c601599a6a05895aea51f349f294a36e8c4ca163775629745c767982fa9e6b96570d6bed55f0b7914cd5c1e4be157a9f5fa6bfd3858",
          "sha256": "efc184d6370a032abc05618a381172f5f7a85d03c5f24f996a7f48c1ef27ccb1",
          "sha1": "fae89703af166e00fab2395c9a59f492a5242af0",
          "md5": "954507a9f015860a3bcf59829f21afed"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "authentication-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "c1f1d3b684cca141b96bcb716e1f0c3d018b99a9be6c2b4ade6ec520e4b31a43c652e5790dbc4762ae5511643685f50b2258f9f342889717f37a059e400f7deb",
          "sha256": "d895d9ec29bb296c2febf3f3c0d4f84e1e6732c31353dfc33d2a86adabe7d927",
          "sha1": "8e2ce806464f34a913468701f9c050e4fe634771",
          "md5": "8f6357433ccb3ecb454408f7bdae5bc0"
        }
      ]
    }
  ]
}
