{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservations-domain/0.7.1/reservations-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "reservations-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-domain-iosX64Main-0.7.1.klib",
          "url": "reservations-domain-iosx64-0.7.1.klib",
          "size": 23279,
          "sha512": "c363553653c9410bb8e7549abeeb721fc6ea7ae510530cbe2149844c22ae445fe17944306d84d764f346dd21eb47fb882a8803eb69e1e2c3be442da9da8dafb4",
          "sha256": "f50bc3620cbe9efe071eb6bf299d9522ff4190b38cde8c4cc757a933acf43428",
          "sha1": "21ce537b8c2d75b3b7c3259ff1db13dd9d23da40",
          "md5": "55c37efe7c9065142d9a0d11cd46bb18"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-domain-iosx64-0.7.1-metadata.jar",
          "url": "reservations-domain-iosx64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "18dc949410dda845322ec972274c78ab949e78587e6361c98f4ced8759ed8282048784bc6c5612fcf3a6dfc595a5a6a2333e939b68bdc3fc1a70d62ce70599d5",
          "sha256": "ff9b22163e5911873f68c7716a98b98baa21d4f01eeaaf8315c72cd136f572cb",
          "sha1": "a0d7886f942a10f549481cd4df5047f2723d7ae6",
          "md5": "8df94ffabfe1f51679ce6be1cb182eb7"
        }
      ]
    }
  ]
}
