{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-data/0.7.1/user-profile-data-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-data",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-data-iosSimulatorArm64Main-0.7.1.klib",
          "url": "user-profile-data-iossimulatorarm64-0.7.1.klib",
          "size": 55839,
          "sha512": "d2b2c7fae4faceaa25e33317a72b5961695849fe0a29e77e9897ca33a72ae1d3a9c7bed27ebf37a6f6b331588aa709c59d015708331d3a7e52f5b7e702bd89e4",
          "sha256": "9c7bd6d1c3756dee4dd0e3aeaf4dc442cc8933704515ca03c4728c6147a2b0b1",
          "sha1": "e1a9c489a3bbb8ea2b876f7b78979f4c379bce6f",
          "md5": "34aec60998c656df4ac3c0c1a80af030"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-data-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "user-profile-data-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "2e2b7f8783608927ec1062e4d5cc98ae893fe366bc20a199c4e6ab2acdba4dff875536ee7675e270d206b73417a2a263586cfe71fd270dc400af2405681abd9e",
          "sha256": "d799e6c1aaf4c7737837d09a99ab8e42efd4c3239b8fd181a2e6ef83af0498cd",
          "sha1": "ae81790651be4391392fdc54d80d3ada097afd23",
          "md5": "44e28a56f75ebbbb8ea217478589c41f"
        }
      ]
    }
  ]
}
