{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "user-location-data",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-domain",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-data-metadata-0.5.0.jar",
          "url": "user-location-data-0.5.0.jar",
          "size": 7065,
          "sha512": "2a8f7651ee7b9c5a20b62ff7090138ad1e097c11c991993e4e1f28d6d724b2ac7f2d1a7f9561fa291ea914d73ca7962ff2c8854058541357cc7432ce3bdab76d",
          "sha256": "cafdb4265e674ea574f0dc385b23f1d43e52d77ec3e9f3535098ac0f331c2f7a",
          "sha1": "7bd0121fa11df21b35245fe27ff5646813dbdc9c",
          "md5": "6088fc3de92b80215be118d9d16f5d3a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../user-location-data-android/0.5.0/user-location-data-android-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "user-location-data-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../user-location-data-android/0.5.0/user-location-data-android-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "user-location-data-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-location-data-iosarm64/0.5.0/user-location-data-iosarm64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "user-location-data-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-location-data-iosarm64/0.5.0/user-location-data-iosarm64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "user-location-data-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-location-data-iossimulatorarm64/0.5.0/user-location-data-iossimulatorarm64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "user-location-data-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-location-data-iossimulatorarm64/0.5.0/user-location-data-iossimulatorarm64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "user-location-data-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-location-data-iosx64/0.5.0/user-location-data-iosx64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "user-location-data-iosx64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-location-data-iosx64/0.5.0/user-location-data-iosx64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "user-location-data-iosx64",
        "version": "0.5.0"
      }
    }
  ]
}
