{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stripe-payments-domain/0.9.0/stripe-payments-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "stripe-payments-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "stripe-payments-domain-iosX64Main-0.9.0.klib",
          "url": "stripe-payments-domain-iosx64-0.9.0.klib",
          "size": 29206,
          "sha512": "ac4858d450437c614fe5705c5649daf9f035157db83fd4728c413378f713f4a48ebd9065bb72636e137de6c6168751e798c73c1d2d4cee33c373c5d8dabd7a8f",
          "sha256": "32c85789fc3661e255a16a841fcb89d1f181d9a2b4a73e0cd28f837602787f73",
          "sha1": "fb47512edecd988fe369eb05016ccadbfc359cc8",
          "md5": "c6bf181f72177489ca9f161f659a3961"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "stripe-payments-domain-iosx64-0.9.0-metadata.jar",
          "url": "stripe-payments-domain-iosx64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "8f6f6f9a72d1dd98922aecd3d053dc02711887be00a94a2b798d94248a0b6f44f8c1d3cb4a1a34d1a7a80e86238fb39a740813b3ca96a265ff49fc9a3c1bddcb",
          "sha256": "4a133ebf49c048957a9695ca55a8647d4cc2fbf2d97c35a04388cab57585cc73",
          "sha1": "528c01b624856dfb5d10f149f58ab2713188a532",
          "md5": "c88908c29f872127484539d783559e91"
        }
      ]
    }
  ]
}
