{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile.android",
    "module": "myaccount-ui",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "myaccount-ui-0.2.2.aar",
          "url": "myaccount-ui-0.2.2.aar",
          "size": 130851,
          "sha512": "51b8f00be63a4ade3ad331e908c19b36453e2ab3f88a643e1cd11baa12371947736e953c096b7442c886c5175752f2dd2c1bc40a65c1971a7bc9cfc78ced5d6a",
          "sha256": "821d52776f9317960705d451bc3c74842b122af83e7e1d52118285286754c3b5",
          "sha1": "11e9e5b4a79ea9988a28e07aa1b4f6386700fb82",
          "md5": "6eab84bc2210f940bd121ce5c6dbaaaf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "core-ui",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "authentication-ui",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "country-phone-ui",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "myaccount-ui-0.2.2.aar",
          "url": "myaccount-ui-0.2.2.aar",
          "size": 130851,
          "sha512": "51b8f00be63a4ade3ad331e908c19b36453e2ab3f88a643e1cd11baa12371947736e953c096b7442c886c5175752f2dd2c1bc40a65c1971a7bc9cfc78ced5d6a",
          "sha256": "821d52776f9317960705d451bc3c74842b122af83e7e1d52118285286754c3b5",
          "sha1": "11e9e5b4a79ea9988a28e07aa1b4f6386700fb82",
          "md5": "6eab84bc2210f940bd121ce5c6dbaaaf"
        }
      ]
    }
  ]
}
