{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mobile-sdk-bff/0.7.0/mobile-sdk-bff-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "mobile-sdk-bff",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-iosX64Main-0.7.0.klib",
          "url": "mobile-sdk-bff-iosx64-0.7.0.klib",
          "size": 136306,
          "sha512": "db7be9bca01bacc2bb0313a128827defdc037ead22d2719da22e0e431e08c124b279c948b21dae238e3411fd7bbd35f60abad9bfb2743fc323caf786bd738000",
          "sha256": "9e140e770b9b323963aa4b7401b3f9b33a8f879485fe6915f9fb61b999a11535",
          "sha1": "375f4352887d4f2b49e37e07fc5a205cf7c482ba",
          "md5": "d2f49c89bf67cd7cb3442b74c82a7507"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-iosx64-0.7.0-metadata.jar",
          "url": "mobile-sdk-bff-iosx64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "f88e708b30d75fe10443214f0c5dad15475bace0731956de14aa2087ebba36aee64e4438f6325bf1b979def46d5b721f95ef71bedd7a76da3009def93f968cf3",
          "sha256": "4273db65dda1369c04a99dbd7dafe172a3de09f02ea1f343641c15630c52d1da",
          "sha1": "062e9177e1764ed80acab5b87e9429fa99f1d98b",
          "md5": "666d82ed9f249e2d9eb66bbf8189e14e"
        }
      ]
    }
  ]
}
