{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "amenities-domain",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-metadata-0.1.2.jar",
          "url": "amenities-domain-0.1.2.jar",
          "size": 5153,
          "sha512": "df8d72898eb846a5a90c191586ced79b7525d0472910b7ff498c49c1dd4f768f62bb2257975ff9351271fad5cb36affbe3ec7b5a7dbb904f2ce523982fa4bbaa",
          "sha256": "5ee270592c11531035241cb2de830e41c4d536b882cd88719a3372054d4e2670",
          "sha1": "5f7a6c111e1560214b84b06ce9759d6222104bfc",
          "md5": "317b963fd1967d2905c2d876f46065e3"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../amenities-domain-android/0.1.2/amenities-domain-android-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "amenities-domain-android",
        "version": "0.1.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../amenities-domain-android/0.1.2/amenities-domain-android-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "amenities-domain-android",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../amenities-domain-iosarm64/0.1.2/amenities-domain-iosarm64-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "amenities-domain-iosarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../amenities-domain-iosarm64/0.1.2/amenities-domain-iosarm64-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "amenities-domain-iosarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../amenities-domain-iossimulatorarm64/0.1.2/amenities-domain-iossimulatorarm64-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "amenities-domain-iossimulatorarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../amenities-domain-iossimulatorarm64/0.1.2/amenities-domain-iossimulatorarm64-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "amenities-domain-iossimulatorarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../amenities-domain-iosx64/0.1.2/amenities-domain-iosx64-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "amenities-domain-iosx64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../amenities-domain-iosx64/0.1.2/amenities-domain-iosx64-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "amenities-domain-iosx64",
        "version": "0.1.2"
      }
    }
  ]
}
