{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-bff/0.7.1/core-bff-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "core-bff",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "mobile-sdk-bff",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-bff-iosX64Main-0.7.1.klib",
          "url": "core-bff-iosx64-0.7.1.klib",
          "size": 12470,
          "sha512": "6b87579be2f6f7e173d9dd522fe9eff4ae8fcfd2f84f9414bb0ab951feee959fef0f4a39b3e5f6ce1680544a8afbda2435b8f935cfb7859ae2adf0f296a1c9c5",
          "sha256": "029ee93e0a731ab9cf1aa7b8c258bd8447906fc55c7deb6d3496ba9add974728",
          "sha1": "8daa255258e35c3cff174a8ef9e2611c21af50d1",
          "md5": "c62c37804bf0d305768b7b980e99850e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "mobile-sdk-bff",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-bff-iosx64-0.7.1-metadata.jar",
          "url": "core-bff-iosx64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "7dc1bad2569992eb3d091f4a6d5393a46d7ce1d9285c5d281626802ad62e6d651c5d75979ebb3d010d87353ef63d008811a3fd3ff3539975e82a277d2e141d82",
          "sha256": "a00a67cde48e698105d3faef533af8b69d3c37183664a218e9572c5dca9f9d36",
          "sha1": "846fb3c07f28a00ba1f9417189677409f0483ecc",
          "md5": "fc64abc493edc91881d70d5a8713198d"
        }
      ]
    }
  ]
}
