{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-usecase/0.7.1/authentication-usecase-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "authentication-usecase",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iosSimulatorArm64Main-0.7.1.klib",
          "url": "authentication-usecase-iossimulatorarm64-0.7.1.klib",
          "size": 5075,
          "sha512": "65fa77990acd19f3f32d5a78798fec782788208c0158bb3cdc6f10ca93112ad4bc564d4182d4324bd15aa30e92957d9ed7e76d418dbcfd5be003020999991b6c",
          "sha256": "37fecc854911b9f891e47e0c9da62577c9a47c8a241c43336154eeb93172887e",
          "sha1": "5dad57405b79be59400cf0b093bcf6c8c59e5c8c",
          "md5": "eefd79e5a130d24e6ce0918c578beca8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "authentication-usecase-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "194384cf5a4bb2c58497bf7c63fe5037cc6aa5556a5f12e2f98991764cc6f816753c7b68b3082a69d64d758cea6aab776f490ae4768202fa73f224592f33f2b4",
          "sha256": "0399d97f8654c467734a23715852cf288727f455793e5b82fbc7545c084e41ce",
          "sha1": "745adfff05478158c7d1584d262716cd11dde261",
          "md5": "9f025919ab239db5be5e4c65ef1d101f"
        }
      ]
    }
  ]
}
