{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api/0.9.1/sdk-api-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-analytics",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-di",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-iosX64Main-0.9.1.klib",
          "url": "sdk-api-iosx64-0.9.1.klib",
          "size": 11379,
          "sha512": "0a34014f83b645e5ea8fe139d3f1ce0c8284ba4a4d465529a365074d287f18187934d1549211d63bca1f4c3a6ca4800958a77cc19f037611243b9173853d4e8c",
          "sha256": "a5114fce87d84fe53a7220fe103f3f0d3942a2b3d9f8131546decbd2d9e341df",
          "sha1": "87dac318232f2a293b798c5a4bc4edc7ae3b5974",
          "md5": "d7d6a685945f12f536e0a46013cbbd0c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-usecase",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-analytics",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-di",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-iosx64-0.9.1-metadata.jar",
          "url": "sdk-api-iosx64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "587689eebe751b577df38953ef43f3f59ac02a5e436030f1d854e78db5bff10d7f781db2c45668e29c0871feefe852b80675cc789ae3cb21856fd0716a88efc1",
          "sha256": "b795cf0be775810d57ad0023b8692689d140308078daee828900e460a4bc7a0a",
          "sha1": "553af15c8a2e64faada07004405541abaf9c899a",
          "md5": "8f8557d48d230ff161ff0d434b90f549"
        }
      ]
    }
  ]
}
