{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-usecase/0.9.0/user-profile-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-iosX64Main-0.9.0.klib",
          "url": "user-profile-usecase-iosx64-0.9.0.klib",
          "size": 4852,
          "sha512": "cfaddf773909f198d8a3ad00d2a4b9c7c25fb838afbaeceea844df1802081ba41152f74a1907d532f9fd3981af63a0a11d31c6f817666cfe75b691349fb84c77",
          "sha256": "6fca5fa1e7eb5394247c7c28066d73fc42a5a96555c02386b490dc165e562f28",
          "sha1": "0e0a24375a6055c1f4f7be7c4ae7dc172f5948c7",
          "md5": "fde788932759e243725b9b0f4a4aa1e7"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-iosx64-0.9.0-metadata.jar",
          "url": "user-profile-usecase-iosx64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "9b29b9b8063b5ab2b6a23262365422462b9592ea5170cff41c070ff768c2fa9ce9704db5cc4f3488dc11cd82bc9c80bc36026be8e9ade39c6dd7131db5ab799b",
          "sha256": "37dac990407054f7e1fb954b4d28394ab0da8c576151fe8e5ef42ad8e804478c",
          "sha1": "f1b5d2125f1aa719cdb9bddf6d6be54d429c15a3",
          "md5": "e046ef3ca42927fcc88560c388eaa6b6"
        }
      ]
    }
  ]
}
