{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-domain/0.9.0/countries-info-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosX64Main-0.9.0.klib",
          "url": "countries-info-domain-iosx64-0.9.0.klib",
          "size": 15124,
          "sha512": "cc181c3d7fbb71dfc337a943c8095753c4a356bbee4a9d94a8caac3d31b3b1bc3671e586d5e35a9eb14f6b44eac267dc530ef651d6971902b832808f1f8165f3",
          "sha256": "5c155f8d910441323f5f2b8c2fb81e4cf91b296f0b2c7eafbb693dcc2394e9cd",
          "sha1": "9747e47cf267564b6ddb50dc8ee9c475b7c2279b",
          "md5": "ec9f33acd80534944f514d6079e789f6"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosx64-0.9.0-metadata.jar",
          "url": "countries-info-domain-iosx64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "6187e0e2297a7cbf699f1609581f085963e6144605c6f0b63866e438c165bd0715dac24269568cfa745d0e8fb48a20548711626337283e057b90a130565dc7e8",
          "sha256": "231d8391816f0128facda5339ecd50c29a6d0f85c4404d6d575a16d81f7766a7",
          "sha1": "739f1f83115e8fa13578f73945e3cd3f5d0188f2",
          "md5": "302549466abd31e221e1fbb5d8f406be"
        }
      ]
    }
  ]
}
