{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "searched-locations-history-usecase",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-domain",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-data",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-usecase-metadata-0.2.2.jar",
          "url": "searched-locations-history-usecase-0.2.2.jar",
          "size": 2605,
          "sha512": "c5d3cc0511d8360bca4ca1591b552f3f91992bff05a556e33d3fdcd92424505e6c859aeb1f10d8f205476df663a7c365ae91d42b60791c04fdb1c0233ef99d2f",
          "sha256": "3680d0f07b5da8455c25140ed7e8ebc111bd84181128af8365f6053d5f6bb308",
          "sha1": "f442623c5cad3152afecb1122dae6b903b6cefa3",
          "md5": "51e66dc6ea516f4fb3dc6d2acf47b6f3"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../searched-locations-history-usecase-android/0.2.2/searched-locations-history-usecase-android-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-usecase-android",
        "version": "0.2.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../searched-locations-history-usecase-android/0.2.2/searched-locations-history-usecase-android-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-usecase-android",
        "version": "0.2.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-usecase-iosarm64/0.2.2/searched-locations-history-usecase-iosarm64-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-usecase-iosarm64",
        "version": "0.2.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-usecase-iosarm64/0.2.2/searched-locations-history-usecase-iosarm64-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-usecase-iosarm64",
        "version": "0.2.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-usecase-iossimulatorarm64/0.2.2/searched-locations-history-usecase-iossimulatorarm64-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-usecase-iossimulatorarm64",
        "version": "0.2.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-usecase-iossimulatorarm64/0.2.2/searched-locations-history-usecase-iossimulatorarm64-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-usecase-iossimulatorarm64",
        "version": "0.2.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-usecase-iosx64/0.2.2/searched-locations-history-usecase-iosx64-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-usecase-iosx64",
        "version": "0.2.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-usecase-iosx64/0.2.2/searched-locations-history-usecase-iosx64-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-usecase-iosx64",
        "version": "0.2.2"
      }
    }
  ]
}
