{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "search-domain",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-metadata-0.1.2.jar",
          "url": "search-domain-0.1.2.jar",
          "size": 15114,
          "sha512": "fe727a77d1b8ffc80acf484c4895dda39768c3daf765e2c009cada2fea2e06d83d52cf45976405dc33bf56b4284e8ea9f9599cda7a9cb7023712664a9c0ac533",
          "sha256": "6ebc8250f87a36e5284b3ce8b7ae494b5a714d784bcebc44636d4d9bac3de60a",
          "sha1": "bbd56a4646c4b0f5907c19f1760990bff66d9cef",
          "md5": "8c4ce4f5a779a952569e4dbdd008fef2"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../search-domain-android/0.1.2/search-domain-android-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-android",
        "version": "0.1.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../search-domain-android/0.1.2/search-domain-android-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-android",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iosarm64/0.1.2/search-domain-iosarm64-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iosarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iosarm64/0.1.2/search-domain-iosarm64-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iosarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iossimulatorarm64/0.1.2/search-domain-iossimulatorarm64-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iossimulatorarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iossimulatorarm64/0.1.2/search-domain-iossimulatorarm64-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iossimulatorarm64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iosx64/0.1.2/search-domain-iosx64-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iosx64",
        "version": "0.1.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iosx64/0.1.2/search-domain-iosx64-0.1.2.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iosx64",
        "version": "0.1.2"
      }
    }
  ]
}
