{
  "formatVersion": "1.1",
  "component": {
    "url": "../../local-storage-data/0.9.1/local-storage-data-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "local-storage-data",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosArm64Main-0.9.1.klib",
          "url": "local-storage-data-iosarm64-0.9.1.klib",
          "size": 8618,
          "sha512": "b7bf0a7998794c4af6571d4c22f3063a122c17e7e74aa1213f5953afb39d9610cf6e8064f95f4dbdd56908c9c43066b5aa0489414e80d9f7bd4338721e9db74b",
          "sha256": "3b2386c5c740b8e222aff106ee645cfe5b020eccd52ba3e9d50805d16077d3dd",
          "sha1": "6e329220e924dc5fc18dc69deddef93c245f3022",
          "md5": "d5942aa2a1dc6ee01476385bfa8265d0"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosarm64-0.9.1-metadata.jar",
          "url": "local-storage-data-iosarm64-0.9.1-metadata.jar",
          "size": 2471,
          "sha512": "605f8bbcef5acf9c2137203430108d8d98c34876d760429facf82d827764b94d2dcc8532ce44695b3b8929f450b51619ccca82ef9c0941e4aec91f59e30f0ee0",
          "sha256": "c13e00f535143db080d1d638222145bc664f2498b1756d8287d9548b2ccacf7a",
          "sha1": "3e8c94ac453ea1d6231cfb55c345c3c244d48846",
          "md5": "1880d62a7a4fcb504da9065321bcd979"
        }
      ]
    }
  ]
}
