{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stripe-payments-usecase/0.8.0/stripe-payments-usecase-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "stripe-payments-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-iosArm64Main-0.8.0.klib",
          "url": "stripe-payments-usecase-iosarm64-0.8.0.klib",
          "size": 4835,
          "sha512": "06f9bffe9b62d4df3dff7546b2c427e9848e3229ecb43ae6796b2479f1b4060123fdbae8708c982480484243ffba827872a8ed0560f4e5a5f87c6d2b08dafde2",
          "sha256": "f475a09ae2de8350972c850d0931f4561e9774d0c5a6d7904658f86b32274acc",
          "sha1": "0465d16b40b889f4d890194e8fe4087422760af6",
          "md5": "c9990373d31ea68eb11cf3fc81b8ba73"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-iosarm64-0.8.0-metadata.jar",
          "url": "stripe-payments-usecase-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "2438d2aa0c07c32e552aea67c6f374cda040af0b5ca76b35ba2b69f808dbfc620e62fa5b88490bde678deb2420e65ff103ccb22a21febd02f534ee4d447bcaf9",
          "sha256": "48bb80f48412e5dd5dfa101f9c2595cf840fc34c9874b1afdb41d77d3536247e",
          "sha1": "4c1ef8fb6a11f502a4ff9ded8d63cd86571eb795",
          "md5": "ca6d2b218565a4ce8cbb0dfefba78a0f"
        }
      ]
    }
  ]
}
