{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-usecase/0.7.1/authentication-usecase-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "authentication-usecase",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iosArm64Main-0.7.1.klib",
          "url": "authentication-usecase-iosarm64-0.7.1.klib",
          "size": 5008,
          "sha512": "c75cbfe742367b75ff88309a9c6fe02a198bb8f8d31295367f5b4fd69370a6a9bff3153d4577e453407015564d85705a44f3ae244ba0de8c19557b15e4046e5c",
          "sha256": "ded9c0d65a8f813e4bcc62b7b457af91b8c3f84d825b8e61a39486f49dd009ec",
          "sha1": "85d6ebcee9171ac01ebc6a44bbaf9f847f38e5af",
          "md5": "558ac7b47fc728651e984cbd4f412904"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iosarm64-0.7.1-metadata.jar",
          "url": "authentication-usecase-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "9703dc9e01afd597bafaaecb901a5546ca3b438cfbfb46f8ce1e6112fb7b8717414d73cb7c09220d0c46824fa2758b700e3cef7d73045a00b42dd04ef8ab2762",
          "sha256": "7e3c1301090d46cf16a07eac320612a75d1b89edaed2d4d4af39d7547aa66f6c",
          "sha1": "a8b6e04aa5a419ee86b02b58819290b5e96a77f8",
          "md5": "49cd80e1ab397d8f93fa24b4619f0a49"
        }
      ]
    }
  ]
}
