{
  "formatVersion": "1.1",
  "component": {
    "url": "../../local-storage-data/0.8.0/local-storage-data-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "local-storage-data",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosX64Main-0.8.0.klib",
          "url": "local-storage-data-iosx64-0.8.0.klib",
          "size": 8597,
          "sha512": "ee23bef4d6c37e8a7eded758def90f649e91be77e6af0b03d814f90b2c3b65ad29b1fc554e6ef1892373c7d06b70c8c1c3dcd210cfd7a5921fb0ec2bc1a2a196",
          "sha256": "937daf4e761e51a1142d6bf1034c0ae32232142bcb2c321cb2baeeef77e8d8fc",
          "sha1": "6f9b4d2439ed690217d7e8c77a170014581856c9",
          "md5": "8d023f3b0ebba0e380befde2d23e3590"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosx64-0.8.0-metadata.jar",
          "url": "local-storage-data-iosx64-0.8.0-metadata.jar",
          "size": 2471,
          "sha512": "1559aa54e2f83ad58a2e25f115a22acaba06ecd8712230acf7ee6d84109da46aa44966ca3aa143ce71bb12df90dbc960bd806b330f8655fad8f0ffcc0c4c02e5",
          "sha256": "39ba76177fe64c74cf20ebd208ed9802646e0ff13dd7108759a70981f6a020b4",
          "sha1": "026e80138a4b0f3f1a5e9f67f8e08d38099894b8",
          "md5": "bea509564bf865b081cdd9f576fb7d88"
        }
      ]
    }
  ]
}
