{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "searched-locations-history-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-domain-metadata-0.8.0.jar",
          "url": "searched-locations-history-domain-0.8.0.jar",
          "size": 6983,
          "sha512": "0710b3181055ee568687fbc8da575ec6fb42b1e2d53da8eeecc2032d9478e90f6db4e8ccf9f9a8b5489e05b517c04327eb13cee47df34b93290226eec2f59e05",
          "sha256": "d4e5b85c88813e430ee502996f8f0df01b996609a754ca4782de2ed10aa7353c",
          "sha1": "e95431dacc57490257aa42a9374107b509f43d08",
          "md5": "2f7cb2630ea0fd4a80015ba2c4efc607"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-android/0.8.0/searched-locations-history-domain-android-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-android/0.8.0/searched-locations-history-domain-android-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-iosarm64/0.8.0/searched-locations-history-domain-iosarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-iosarm64/0.8.0/searched-locations-history-domain-iosarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-iossimulatorarm64/0.8.0/searched-locations-history-domain-iossimulatorarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-iossimulatorarm64/0.8.0/searched-locations-history-domain-iossimulatorarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-iosx64/0.8.0/searched-locations-history-domain-iosx64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-iosx64/0.8.0/searched-locations-history-domain-iosx64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-iosx64",
        "version": "0.8.0"
      }
    }
  ]
}
