{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile.android",
    "module": "googlemaps-ui",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "googlemaps-ui-0.1.2.aar",
          "url": "googlemaps-ui-0.1.2.aar",
          "size": 146083,
          "sha512": "6f2015de6213dbbc931be878e2561be55960bfdbcaa64d8a360d6ab11d8ac7c43e6435c5807a2f585ff7294f5c71b4c99a8c4aee0050f6bc8cd112593ca8cd57",
          "sha256": "e324b655569b89d01a46ae3ed63b20c9588fe4043de9a2038e06edf8c040e4d6",
          "sha1": "05ba9ed676f869943a2723d07b9fad34103691b5",
          "md5": "0878ab1ebb71e176ae135b563b4ae24d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "core-ui",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-svg",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-compose",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-ktx",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-utils-ktx",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "googlemaps-ui-0.1.2.aar",
          "url": "googlemaps-ui-0.1.2.aar",
          "size": 146083,
          "sha512": "6f2015de6213dbbc931be878e2561be55960bfdbcaa64d8a360d6ab11d8ac7c43e6435c5807a2f585ff7294f5c71b4c99a8c4aee0050f6bc8cd112593ca8cd57",
          "sha256": "e324b655569b89d01a46ae3ed63b20c9588fe4043de9a2038e06edf8c040e4d6",
          "sha1": "05ba9ed676f869943a2723d07b9fad34103691b5",
          "md5": "0878ab1ebb71e176ae135b563b4ae24d"
        }
      ]
    }
  ]
}
