{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-analytics/0.9.1/sdk-analytics-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "sdk-analytics",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-analytics-iosArm64Main-0.9.1.klib",
          "url": "sdk-analytics-iosarm64-0.9.1.klib",
          "size": 28267,
          "sha512": "3d1dce5ab0cae08e05d61b6ff0a80b955b3d29cbb3876b287fdcf72ed8f286e145028b0ff4cde44bc8ebb1f1f9677c4725456d8c74aa31e3abe0cfade9d92e2c",
          "sha256": "95cb25f9bbcfcfb15670bd7e74929f1a52ba6b45a00ba215cd1c8f5dcd479eed",
          "sha1": "bb2d3aa946be93ab8b8ce1bdf8ce8604a8fc3125",
          "md5": "66935c25f1a7805ced576d697d6759e2"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-analytics-iosarm64-0.9.1-metadata.jar",
          "url": "sdk-analytics-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "e77b7b0e4f843722cd65b10d7f623dd704b6e11076ebb50b8ea9ff9d53e1b9193102ffed426be401f191904cd2715aaf6f2fea4d82a510eb106a753189f5fd7c",
          "sha256": "e1bcd68bdaf50aec6bede0f83cd5333aa828e6bad694d0fa0d69bd42f2bef550",
          "sha1": "76ee45012a8c5e319c7f38de1d9c3e2832e9dd5a",
          "md5": "732878c9fa1520bf8a59153d1e3fcf2a"
        }
      ]
    }
  ]
}
