{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-domain/0.9.0/amenities-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "amenities-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iosSimulatorArm64Main-0.9.0.klib",
          "url": "amenities-domain-iossimulatorarm64-0.9.0.klib",
          "size": 12781,
          "sha512": "9a35d219ee7a62e4bfabee54dc1174dcf6b9f555539d8b96e81c0ec8cfdff34bdcfd4cd4e59edbe2093a38a5d2e63fc2abd05b1a5096b73d2f5b01fd2fb05558",
          "sha256": "8a0c0bf0a12a5e6bd626dea98c3e0341104d017fa3868fe925b27f5b4cd4c934",
          "sha1": "3533cacaaf8cbdc142d87c95c001557b7b61c733",
          "md5": "b2b01f08f4e454561dca5ed7d7c5b2e4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iossimulatorarm64-0.9.0-metadata.jar",
          "url": "amenities-domain-iossimulatorarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "1fc87f57c67f1138b2ecad437f37212e0ec93f3bfb6f8dee64f2d153c001a16a2f5379985b62943ab24223bc4b229504a6e826cf3c0f78877d8de388552d97b4",
          "sha256": "3f5b2e084d5692ec70468a76ca587911722131bd29e777ca383c2c9b5b76e63c",
          "sha1": "e65535c063e78ee243984dc2d10541f03cc8aa68",
          "md5": "3926f5ad9d7b4069617dbd71d3b566bf"
        }
      ]
    }
  ]
}
