{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-location-usecase/0.8.0/user-location-usecase-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "user-location-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-location-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-location-usecase-iosX64Main-0.8.0.klib",
          "url": "user-location-usecase-iosx64-0.8.0.klib",
          "size": 4788,
          "sha512": "e9e2114d286cf7d720438d817146c3d56631c6ff81ffa96cc8f7f44fbbaded1bdafb83cd2f40e93b841825965c8f05d9074033c745fe096869ea1c442f9b33b6",
          "sha256": "cd10fec2d689a436c566b8b2912de640a8e67202bc22204f28a6e7045ae41720",
          "sha1": "6ccfa67506d213680a9bcfd36ba5a72ad8bb96bc",
          "md5": "68bcce5376fded9186a24ffb5097ca30"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-location-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-location-usecase-iosx64-0.8.0-metadata.jar",
          "url": "user-location-usecase-iosx64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "822d06074a59edb9621b53fefdcc34ac610e5e1fa7fb8ec189355303a6d895e2215266f5bc56001135435cad6d41b0438800df49b1a6c06e55a0a1be643df221",
          "sha256": "0569bc87063c06fdeffc0e811f95c5b5916cbc8b1a09d5b1be40c573dfe6f033",
          "sha1": "ea33846c99008f7c5a377a3cccc7de273c2e3009",
          "md5": "710d470f46267123da130d61307f9472"
        }
      ]
    }
  ]
}
