{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "amenities-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-metadata-0.8.0.jar",
          "url": "amenities-usecase-0.8.0.jar",
          "size": 2490,
          "sha512": "bf4f597d7a6c08bcbcd7040efe46c6a8907ac8ce7f5122973f6fccc8833983e5d45eef5b9590459d7c0e1fd538c285bd6d65719ea74d09604b47921495ead0de",
          "sha256": "bfba52d2189045cf1dd421f3aed3dce1f3e1891542105f18a7fc5543e0e857c9",
          "sha1": "4b971d127381dbfcb19f61ddca2cd527753580e0",
          "md5": "322717beb427fa52f484f4928b77b9f5"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../amenities-usecase-android/0.8.0/amenities-usecase-android-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "amenities-usecase-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../amenities-usecase-android/0.8.0/amenities-usecase-android-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "amenities-usecase-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../amenities-usecase-iosarm64/0.8.0/amenities-usecase-iosarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "amenities-usecase-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../amenities-usecase-iosarm64/0.8.0/amenities-usecase-iosarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "amenities-usecase-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../amenities-usecase-iossimulatorarm64/0.8.0/amenities-usecase-iossimulatorarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "amenities-usecase-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../amenities-usecase-iossimulatorarm64/0.8.0/amenities-usecase-iossimulatorarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "amenities-usecase-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../amenities-usecase-iosx64/0.8.0/amenities-usecase-iosx64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "amenities-usecase-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../amenities-usecase-iosx64/0.8.0/amenities-usecase-iosx64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "amenities-usecase-iosx64",
        "version": "0.8.0"
      }
    }
  ]
}
