{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservations-usecase/0.7.0/reservations-usecase-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "reservations-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservations-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-usecase-iosArm64Main-0.7.0.klib",
          "url": "reservations-usecase-iosarm64-0.7.0.klib",
          "size": 4947,
          "sha512": "9f1c248aceac83e784ab7a28f5dc4f7d4710dd115319f276e49fbe4242fda7b0dce1812108fd8ddbdcb44a756ffaff0bb551b01bf4536f1dcd4ac32efbc1ca12",
          "sha256": "3ca44691b1a0e60a3c868d818944b83f0cdc3c78619e685f008d1158801f3015",
          "sha1": "fe3b51413d72169027a172f50b00a845b7e47515",
          "md5": "ee7bff3e3b7d791f45aa1dfb4062deb6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservations-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-usecase-iosarm64-0.7.0-metadata.jar",
          "url": "reservations-usecase-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "185c2e2ed197d62efc56777a9e7d1456722dc30fceb6a6c033e28c145d662054795ea4d1a6dd9fc337b4bc147c9d271aad98d395ef7e2565befd6ddc46e5a6e0",
          "sha256": "f3cec096e9524b25939c38dee23ea3d4f286b395cbafa093a5ec3da67537adb7",
          "sha1": "e44ca14ec456bb8db0411ea6463eddc3400b1cab",
          "md5": "e3df36738ce0ecee19f4962907ada93f"
        }
      ]
    }
  ]
}
