{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservations-domain/0.7.1/reservations-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "reservations-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-domain-iosArm64Main-0.7.1.klib",
          "url": "reservations-domain-iosarm64-0.7.1.klib",
          "size": 23292,
          "sha512": "d744ff484dfd160c742602930ed7990be1446e696f6ea409bbee46f28bfc9bc539ab5d43082bc971545da1e8171367f99434ddeaf1b494828980ae7f0208b8e6",
          "sha256": "c83bc1d639a7859a3ab34789455c9dd499ad58265cd2e93d59788f2969fc3269",
          "sha1": "cf0d6f408749bf9e7eeffc1742a7e30677bdb51f",
          "md5": "366cc07c1c54c24214a5df85243841fa"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-domain-iosarm64-0.7.1-metadata.jar",
          "url": "reservations-domain-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "18dc949410dda845322ec972274c78ab949e78587e6361c98f4ced8759ed8282048784bc6c5612fcf3a6dfc595a5a6a2333e939b68bdc3fc1a70d62ce70599d5",
          "sha256": "ff9b22163e5911873f68c7716a98b98baa21d4f01eeaaf8315c72cd136f572cb",
          "sha1": "a0d7886f942a10f549481cd4df5047f2723d7ae6",
          "md5": "8df94ffabfe1f51679ce6be1cb182eb7"
        }
      ]
    }
  ]
}
