{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile.android",
    "module": "sdk-ui-config",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-config-0.1.2.aar",
          "url": "sdk-ui-config-0.1.2.aar",
          "size": 8574,
          "sha512": "645b3e57e71dbed1fa1e82dcaed18ae66703c92de03dbb493e0f9f65013a8d16b771a734ec0a4ef29141a7c507f8df62160f64be12c527feec892c7a4d1d81c8",
          "sha256": "ca2d2e97b3cfc52247f254922aa66c6402e190df827a3ef6b858dae31d219b34",
          "sha1": "40f49efd23b0304c7a3d9d1451651e5e3882cb66",
          "md5": "11c363bcd74477366c66d7a5cd4319ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile.android",
          "module": "core-ui",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-config-0.1.2.aar",
          "url": "sdk-ui-config-0.1.2.aar",
          "size": 8574,
          "sha512": "645b3e57e71dbed1fa1e82dcaed18ae66703c92de03dbb493e0f9f65013a8d16b771a734ec0a4ef29141a7c507f8df62160f64be12c527feec892c7a4d1d81c8",
          "sha256": "ca2d2e97b3cfc52247f254922aa66c6402e190df827a3ef6b858dae31d219b34",
          "sha1": "40f49efd23b0304c7a3d9d1451651e5e3882cb66",
          "md5": "11c363bcd74477366c66d7a5cd4319ae"
        }
      ]
    }
  ]
}
