{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-usecase/0.9.1/pricing-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "pricing-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-iosArm64Main-0.9.1.klib",
          "url": "pricing-usecase-iosarm64-0.9.1.klib",
          "size": 4747,
          "sha512": "48051892cf1d34f1d37dc02c505899275639b9f89a0b6022e801a126097ad17068b7442532fad8771415412079b2e97b24a09181218d5617298c285434248796",
          "sha256": "b8984e519209f71e1a864c80197b40cb7898dc787906684f794332392d8b9aa8",
          "sha1": "e148a12ab4b8f75eb0731304915e6a616c67c22f",
          "md5": "9d36ee7c9ff987ce7301d6ea1f47ebb5"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-iosarm64-0.9.1-metadata.jar",
          "url": "pricing-usecase-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "9d33e3cda5315f3f5f50f096ecacd276656a326ed0a344a2687169716adfe48a5a995cfa25d7790a64c8e77ed07d5755268ae5b49d629ffba78eff9d313a66a9",
          "sha256": "723f469cb931b3f0ef12f7316cd12d954044813d3184781130bfcf4fab4a91e7",
          "sha1": "edc551a864f39d3a75adf174f43471812837eb3a",
          "md5": "4d4f3a361ea2988e6c15c488af494126"
        }
      ]
    }
  ]
}
