{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stripe-payments-domain/0.9.1/stripe-payments-domain-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "stripe-payments-domain",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "stripe-payments-domain-iosSimulatorArm64Main-0.9.1.klib",
          "url": "stripe-payments-domain-iossimulatorarm64-0.9.1.klib",
          "size": 29284,
          "sha512": "7868d84d50349a8c00cf1b568b5c817b629c8b3159e0a0a4fc2875bfefeba6be4a52b10c2735625ff6a00e7b751e9b4fc72a83a923c397e43a4edb559fff8bc5",
          "sha256": "8a2a46480f44e5335aeb5823484bab6d1d338afb77ad626f353fa61c0951303e",
          "sha1": "df835bed2f63c13a00ace2b3633578d316e3593b",
          "md5": "42192da50b6c49b852e4ebe3503673bf"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "stripe-payments-domain-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "stripe-payments-domain-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "3df85b1acd6ee4963abdf261aa32f3bd4ab8eab19806ddc4c8fba82f6f906b2b5b575ec96274210c2ec3fa6385c43b4273177aca52886691e8003c665d36c2e9",
          "sha256": "bc4c2fb1600ddbd7e4e169613ada31ca2334a4b6d369f3bbde6ba0f11528a0b4",
          "sha1": "4b1eedf7790694604cc1fd3241e3ecced6656855",
          "md5": "3183e2a6e01dc6e2f2f37e85fc80b14f"
        }
      ]
    }
  ]
}
