{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-location-domain/0.7.0/user-location-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "user-location-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-domain-iosX64Main-0.7.0.klib",
          "url": "user-location-domain-iosx64-0.7.0.klib",
          "size": 13614,
          "sha512": "5da152def53d261cd9fd6cc971c782b3dbeaffe65d425ab63b90066b37f83b3b3bb3354293e68ba46622dea74c260695ce2c02186a8aa3fa26376cf4fe1d9b75",
          "sha256": "643ba76714e36b1d74fc8351388047983f9d95d40adba89b9b689778fdd90570",
          "sha1": "2c1d07c4cba7ad89ed2159c73b18c67d61c41f5e",
          "md5": "f89e99620ce104cd4d431fe5a5d4c02c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-domain-iosx64-0.7.0-metadata.jar",
          "url": "user-location-domain-iosx64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "fe2b4f57a3af9cc98dc2b664588cb12cbd8d9689b91983b8c948a07cda441a5f10c4fc3256c3e03906b3a9a4fbb380196cfd168deeb152102f2c121b57c3e712",
          "sha256": "5eb6e21de5b4e6e2d7842164bfc76e4bcfbc63f75b405488044e4fd76ad7e677",
          "sha1": "b04eeae96ee865aa590294340e058d3385dcaf12",
          "md5": "62e246efd9c3d81c5ccfa49f9072cf39"
        }
      ]
    }
  ]
}
