{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mobile-sdk-bff/0.7.1/mobile-sdk-bff-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "mobile-sdk-bff",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-iosArm64Main-0.7.1.klib",
          "url": "mobile-sdk-bff-iosarm64-0.7.1.klib",
          "size": 136319,
          "sha512": "206341147065dfad5a9ff3edbf0ef9af4ce2c58d55a0c2736318bcee20ebe03f3f2b358e2e1d1b33ecd7f72e7999d9ddb3d6cd909b87cd3959e024336a475087",
          "sha256": "a935496dffe2be2dd30a98e1d132356b0ab918269847f9bd4d9062e18ef1dadf",
          "sha1": "6b58b89853d1732a7a6c5cb3dac10991bb50841d",
          "md5": "188a553ffebf2dd3278dd50ecdea4cf8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-iosarm64-0.7.1-metadata.jar",
          "url": "mobile-sdk-bff-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "33164e41b71d6cf2823367243bee908434fc1b04683290ec97576495f2699cb6455a87b45065700d7b67c3aac6b9b7ed828445c93e9c670363aa8bb07de3a6b3",
          "sha256": "7a8781629cb68c7c4787651e2dbc14919547d201535a76197040aa046e48579c",
          "sha1": "df3a73b52d8d175010d88efa54f45b74304ad79d",
          "md5": "d41ada37ad8b34dd94a6f8d5294c4cbc"
        }
      ]
    }
  ]
}
