{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-permission/0.9.1/core-permission-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "core-permission",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-iosSimulatorArm64Main-0.9.1.klib",
          "url": "core-permission-iossimulatorarm64-0.9.1.klib",
          "size": 33882,
          "sha512": "45d62bec3fb37142769737865f71552de053d71949faa3a80997a53f1e5ef82e9b857a67e817aa69a6f0a07f9a27e8c22c9d159df37009d204415b94adb880b3",
          "sha256": "93214f7176076cc698db07df7952b253f9bae9d02e8a9f055eb475a5e5a45f26",
          "sha1": "d1ed0d0e7d62644b4cb6ae942c435e206771b637",
          "md5": "fb8307083b49fc70714bfb5a81461f25"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "core-permission-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 3162,
          "sha512": "14b13d9d70c12e8f16b6df479c5ae26d6e5dc1b0d8b5ae48a73afe4fb46e2da375bd199b198accd4d8802672b2ff52c4590700067ced795d3141df9d6ca6ca6c",
          "sha256": "97abe20dc597fd0a64c6b54f1a582a5c51e74eeb9569c578dae0def97c4beecc",
          "sha1": "357674af0d9beab9dbf9eb6b756753679f21a59e",
          "md5": "ec07833a2e0379f10066dc19bf3a4ff6"
        }
      ]
    }
  ]
}
