{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-domain/0.7.0/amenities-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "amenities-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iosSimulatorArm64Main-0.7.0.klib",
          "url": "amenities-domain-iossimulatorarm64-0.7.0.klib",
          "size": 12899,
          "sha512": "2078c0640d50bde5a20bab4ace958a44e51f00591590e8f7efc99bac590462419775c45fc52e5305855c89e18a77d78601b6940bc344b4df211db139f7450b01",
          "sha256": "5daff44af96db6162e9180aced90c9cbb4639c7a90acad8335f936694bb17a37",
          "sha1": "f6c54074d401df512f576aff2984a170f1006e8c",
          "md5": "e8f393b8a9d3c9f4076e0bc94239e2a7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "amenities-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "b64ab3fd1986539f96c259d33d4e045d0a7e8ff2822468b3e4672ba1bb89aced7c2f21fc9d5512cb8f220011082cb1a98ffda948ad0a769c9396c3d5654a3f49",
          "sha256": "1d82f94ca81017364b9cb9c598dd402e115de5bb4322de820469c01ac6c8b7a7",
          "sha1": "0697c81799905af62a0b46e5bcf12b65ce5a76ea",
          "md5": "2ad7f33c9113b71295512b2eaa44ec74"
        }
      ]
    }
  ]
}
