{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "coupons-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-metadata-0.7.0.jar",
          "url": "coupons-usecase-0.7.0.jar",
          "size": 2463,
          "sha512": "ddcf0b44f2a9c459df67a40059bd6774274650b13c589eedf596cc707aaa962c4c1b05782e24d245820b58dcf0915e126fb7afbf9ff992e6ddf1bb7277a71329",
          "sha256": "9df78c02695618342f9def2d3fce0389b16c829870060a13f5b9f19cac862cfb",
          "sha1": "27fd36d351cbdfe16bd3ccd8a90ab4ca4f4ecf89",
          "md5": "cd3c0b43674e01578f4ae5dabe534a39"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coupons-usecase-android/0.7.0/coupons-usecase-android-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "coupons-usecase-android",
        "version": "0.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coupons-usecase-android/0.7.0/coupons-usecase-android-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "coupons-usecase-android",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coupons-usecase-iosarm64/0.7.0/coupons-usecase-iosarm64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "coupons-usecase-iosarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coupons-usecase-iosarm64/0.7.0/coupons-usecase-iosarm64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "coupons-usecase-iosarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coupons-usecase-iossimulatorarm64/0.7.0/coupons-usecase-iossimulatorarm64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "coupons-usecase-iossimulatorarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coupons-usecase-iossimulatorarm64/0.7.0/coupons-usecase-iossimulatorarm64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "coupons-usecase-iossimulatorarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coupons-usecase-iosx64/0.7.0/coupons-usecase-iosx64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "coupons-usecase-iosx64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coupons-usecase-iosx64/0.7.0/coupons-usecase-iosx64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "coupons-usecase-iosx64",
        "version": "0.7.0"
      }
    }
  ]
}
