{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservation-details-domain/0.7.0/reservation-details-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "reservation-details-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-domain-iosSimulatorArm64Main-0.7.0.klib",
          "url": "reservation-details-domain-iossimulatorarm64-0.7.0.klib",
          "size": 52477,
          "sha512": "975e82b5368013fa480f041e5391fbfe6ca678bf1c1e9d63596781da72e49976497e46c6ce7f91fc57ff9758d8599203d61337a9a4f2363246358442d377c56b",
          "sha256": "6da96fefd896881cce8a118ff908f97755a8c7ee5efcd450fb12b6acf4f72525",
          "sha1": "01dc414a7b398a6885d17e492ef2bd36e4f70be7",
          "md5": "57a082a901d55f9fe4c76e5b631b0889"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "reservation-details-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "9e8fb708bc3d6377924cf9bfd77277da2fe427e7bc602ee5d2bc339b90196a4fc677e04cc99160256f8ee332bde4f381ca82008c61b6483401f06cb3e488c3e9",
          "sha256": "0708bc15565e9f3beceeafad252553caf35ac5cd966ac1d9db4a69cf4d13ddeb",
          "sha1": "27ed7c0f34ccb5cc547e25053d055ad6e5e18e55",
          "md5": "ef14598ff18a4e825ab72f537b882a89"
        }
      ]
    }
  ]
}
