{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api-config/0.9.0/sdk-api-config-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api-config",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config-environment",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-iosSimulatorArm64Main-0.9.0.klib",
          "url": "sdk-api-config-iossimulatorarm64-0.9.0.klib",
          "size": 38135,
          "sha512": "c53230a6b0886875039f42ff57d662f08dd430689de976e51668fcd7acfbb1bd1abc298516a3d464dcb4cc95b5cc28fbb31af78706b1a71098da2695417039fa",
          "sha256": "c0af2babde66f6431e6cc8e70fd78df24ed43a34958f3b62598e08c0eab0c4b9",
          "sha1": "a297b90891b0e7e2faafe5ad8462447aadbced00",
          "md5": "1964efd7e9938a2111b6251b4b1e210b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config-environment",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-iossimulatorarm64-0.9.0-metadata.jar",
          "url": "sdk-api-config-iossimulatorarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "b97b2a5fe5afb8252d073f0aea45d113860a95d3765c4653342a903f5dc4189f74f194e109eb302a786d5bfebdb2fea536a05b43c687a0983eafe7d69721554e",
          "sha256": "335767bd60977047a14a285f914d65b8009a8cfebe863813425adf8137a821a6",
          "sha1": "1e86818de4d1c90d9ff2e7d0f533c769d3523368",
          "md5": "87d300bab79802a4f58176f12b7ea6eb"
        }
      ]
    }
  ]
}
