{
  "formatVersion": "1.1",
  "component": {
    "url": "../../searched-locations-history-usecase/0.2.0/searched-locations-history-usecase-0.2.0.module",
    "group": "com.mozio.mobile",
    "module": "searched-locations-history-usecase",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-domain",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-usecase-release.aar",
          "url": "searched-locations-history-usecase-android-0.2.0.aar",
          "size": 2321,
          "sha512": "74eb07bbb0e2daf306079cd71a93fb060e1648fee9a928f1e803d587ba72a0ed7a00a22cb8553e9993e4348921a9fbe7b6eb8ee7398790efad0deb5cdc8f1760",
          "sha256": "e2e5611734a2dbf4d1f83a4d6fc76ff81b647f3d5e34d48c20cf2dfe76a202d6",
          "sha1": "b6adaaa5fe4d55b8715b70bc257a313b2e081f38",
          "md5": "9202da24ace22e1eea48c4ffba8e30c1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-domain",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-data",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-usecase-release.aar",
          "url": "searched-locations-history-usecase-android-0.2.0.aar",
          "size": 2321,
          "sha512": "74eb07bbb0e2daf306079cd71a93fb060e1648fee9a928f1e803d587ba72a0ed7a00a22cb8553e9993e4348921a9fbe7b6eb8ee7398790efad0deb5cdc8f1760",
          "sha256": "e2e5611734a2dbf4d1f83a4d6fc76ff81b647f3d5e34d48c20cf2dfe76a202d6",
          "sha1": "b6adaaa5fe4d55b8715b70bc257a313b2e081f38",
          "md5": "9202da24ace22e1eea48c4ffba8e30c1"
        }
      ]
    }
  ]
}
