{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-permission/0.9.0/core-permission-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "core-permission",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-iosArm64Main-0.9.0.klib",
          "url": "core-permission-iosarm64-0.9.0.klib",
          "size": 33816,
          "sha512": "60dfcde5214ee77db54b0ce23af95b7f613c84b7121d731641bfbe8f2fb09b7ae575f0a04d1a8f3b87dade6f0ac5788ea182f6ddef4da70dc562368b7c8cc99f",
          "sha256": "3ddd3f37016737fef46cfd38df87bca3b93bf7fa3c2a5605ed4a4925a6252212",
          "sha1": "f035abe695b8b5d96be8ae1b3629dc5cab92507f",
          "md5": "ddcffb55c6aafbdbe53ef0341122b709"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-iosarm64-0.9.0-metadata.jar",
          "url": "core-permission-iosarm64-0.9.0-metadata.jar",
          "size": 3162,
          "sha512": "873b5a2fbbd89fb38319c12377c7c8937f1cc74ab260abb531ae2a9d894d13edc2fb8852e4f0b7e47c0bdea49d594ca001c8cd6a47812937dcebed70b3992e52",
          "sha256": "6f5260904663716e54c066b902c209eedd056df973998cadd41dc47c3b837370",
          "sha1": "fd950b81989845c0f698add96b8580732f28556f",
          "md5": "3ad8700fd9415e9db6dc05317b6c75b0"
        }
      ]
    }
  ]
}
