{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mobile-sdk-bff/0.9.0/mobile-sdk-bff-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "mobile-sdk-bff",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-iosX64Main-0.9.0.klib",
          "url": "mobile-sdk-bff-iosx64-0.9.0.klib",
          "size": 132938,
          "sha512": "e072bbcfe86c94fd68b6f816ccb2682b4c3f5eb99b7621995f21f43947e7a1d5ff84faf3ed2b6c5ffc50e76c51fe1cfd8ab1fc277c2896546d8851764f365614",
          "sha256": "32ceae6318feb256757666951547846c8bea1757d20c3e410abad7f08f2b08ee",
          "sha1": "2ef4f3fa408c90d54a37bac74357ff8928bb796e",
          "md5": "ce530b020650533f90f65d2ae6f9a810"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-iosx64-0.9.0-metadata.jar",
          "url": "mobile-sdk-bff-iosx64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "4bdcf5bbf053e79382851e2e8119188b05f8c2ae28c23f6c17d5a0e62404d2b7dc55a36d171a8a9c5f016b534f41146ba16470943f2bf4df2556ccb7b80e0490",
          "sha256": "83ee38f5adc1307200837ae31861d34f360768ec33a3da1d72aefe848959dc26",
          "sha1": "3c20938704648c211cf6bd715d77bece688f5c0a",
          "md5": "96b70022afcbc9a691db9587335ac0af"
        }
      ]
    }
  ]
}
