{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservation-details-data/0.7.0/reservation-details-data-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "reservation-details-data",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-data-iosSimulatorArm64Main-0.7.0.klib",
          "url": "reservation-details-data-iossimulatorarm64-0.7.0.klib",
          "size": 210429,
          "sha512": "1efcb7e40d4cade67932b1a70ab22deac8e452d019279ef4551e391bb9d4145221cbe71430232520668798265a958fe9e96590313766861f745613b04df6627a",
          "sha256": "e2e015e88644b99ecd146d4f280b970976d277b2c32a4959848bad43b98e0841",
          "sha1": "b7c99bbcf51bebf9c12abf7f20c09b820b9cc732",
          "md5": "2d63507c698ec60feafeefa40c10a0c3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-data-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "reservation-details-data-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "3db013276b92ff5e349ab64f9b32e4bfd88197add352a00ce1d47149e09d5cba54e4c982d1f9a659ecd25a0c97b46f9150b6e9a99582bc1291ac6e78c63f2b10",
          "sha256": "baf3cb2a5d8b1ef2b36e5e69755514e0de8590a2921a35f19eaf4c8184fd328f",
          "sha1": "533a930525473a6bcffb1439ac118a406d31c152",
          "md5": "17698c69c488be248d62bf257b591e72"
        }
      ]
    }
  ]
}
