{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mobile-sdk-bff/0.9.1/mobile-sdk-bff-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "mobile-sdk-bff",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-iosArm64Main-0.9.1.klib",
          "url": "mobile-sdk-bff-iosarm64-0.9.1.klib",
          "size": 132969,
          "sha512": "9e2755a34fc29c65e573fc31dd97ae5d4db13a08a2d608428f71bc4f22da352f2cf0d02cd617c5f3c98d85c8185dfa43cef61aca477eb704c17aecf34ce698ac",
          "sha256": "a0b7c84a1e3e5a75858eac9b8b060125481a820071e0d21a4ded4a5c7e066ca5",
          "sha1": "ac2acc917b81b6b3fbd773ed5f28dd18da93b2ee",
          "md5": "28af647991b795044aa6848005735330"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-iosarm64-0.9.1-metadata.jar",
          "url": "mobile-sdk-bff-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "3add121697e63cfde7be691a5dbb644ba866b0dc33e89e4ae73961f16499f98b5de29a39fdc556af49ea9777bb2fedc3b10646f9d84da5bda662477a0f94117b",
          "sha256": "30bc22a9c5e1bd3ecf1a81311ae9916ebc4586f7d669c2dec55ffc9cc50a65ff",
          "sha1": "70cd4dc0a8f1579078b6b2d9e0f6cabc5ff84b3e",
          "md5": "ee2eea253025cae637a92c0fd80ba572"
        }
      ]
    }
  ]
}
