{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-usecase/0.9.1/pricing-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "pricing-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-iosSimulatorArm64Main-0.9.1.klib",
          "url": "pricing-usecase-iossimulatorarm64-0.9.1.klib",
          "size": 4811,
          "sha512": "9dd5129ca1a8983ebf7a94b6ab8810f1b03e4d43ba0f6a374cdd3dc813044bc7b1470571a0d21e59dc6c4c1cc63248b07f01a731da13759e309852689b385fa9",
          "sha256": "e3d1c79c737afa6f3a865db4dcdeed91605ce9bba15755ea21b16a9778ad574e",
          "sha1": "32df9556b0ad67da952b1965ddd335869d1bed64",
          "md5": "05d131f2e98fd7159a03f8b8bb4b95c7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "pricing-usecase-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "9d33e3cda5315f3f5f50f096ecacd276656a326ed0a344a2687169716adfe48a5a995cfa25d7790a64c8e77ed07d5755268ae5b49d629ffba78eff9d313a66a9",
          "sha256": "723f469cb931b3f0ef12f7316cd12d954044813d3184781130bfcf4fab4a91e7",
          "sha1": "edc551a864f39d3a75adf174f43471812837eb3a",
          "md5": "4d4f3a361ea2988e6c15c488af494126"
        }
      ]
    }
  ]
}
