{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stripe-payments-usecase/0.9.1/stripe-payments-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "stripe-payments-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-iosArm64Main-0.9.1.klib",
          "url": "stripe-payments-usecase-iosarm64-0.9.1.klib",
          "size": 4835,
          "sha512": "06f9bffe9b62d4df3dff7546b2c427e9848e3229ecb43ae6796b2479f1b4060123fdbae8708c982480484243ffba827872a8ed0560f4e5a5f87c6d2b08dafde2",
          "sha256": "f475a09ae2de8350972c850d0931f4561e9774d0c5a6d7904658f86b32274acc",
          "sha1": "0465d16b40b889f4d890194e8fe4087422760af6",
          "md5": "c9990373d31ea68eb11cf3fc81b8ba73"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-iosarm64-0.9.1-metadata.jar",
          "url": "stripe-payments-usecase-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "90ca848470f788c19827a949d23587f3dc1232afa5a662279aa5e84b3f041ed8cca73c0381d65608e78dece09581e679df1b89821a3b1d5f993de3e17e117eb3",
          "sha256": "d6d19dca212b094643c617a38985dde11a03bdd0ccffe0dcc53ffd61686b0ff6",
          "sha1": "2da38037a97af89cda58ab20a3c795bc4f8f4a1a",
          "md5": "091fa49539f53007fc3ee67f6bb890bd"
        }
      ]
    }
  ]
}
