{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-domain/0.8.0/countries-info-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosArm64Main-0.8.0.klib",
          "url": "countries-info-domain-iosarm64-0.8.0.klib",
          "size": 15137,
          "sha512": "7be8be559e05242006a6ee8fe8321c7bea230ffd9b0cc915723f3128585e3932e43008de98f2f5f87ecfcd61ac5df541b865b987a6d7550e37e358820bf58a74",
          "sha256": "7fb9a6d7d66ba7d5a0de4d382e8ec27eff26854abea9441b7c1c183c103c62c6",
          "sha1": "be3761bba974d18cb96ae57ceabb4a423520baa8",
          "md5": "8f6ea7fac53f21426883f4b1c232e904"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosarm64-0.8.0-metadata.jar",
          "url": "countries-info-domain-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "9eb585611646f17851870fb295f0ecc7792596df781b2afeda367846459b3859f4e426a15bdf49c4a66b27ad368ee91d317f0de0b6c942f14921222d956e3558",
          "sha256": "a9eb4ec5a5bcfaeaae3c8774b24a35a840989dfa5d53b3f6e4c1fa39586aaadb",
          "sha1": "54bd402112d3372cfe1167030332d26290360155",
          "md5": "abeb9072cd7288214a527ae5c463f56a"
        }
      ]
    }
  ]
}
