{
  "formatVersion": "1.1",
  "component": {
    "url": "../../searched-locations-history-data/0.9.1/searched-locations-history-data-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "searched-locations-history-data",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "local-storage-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-data-iosSimulatorArm64Main-0.9.1.klib",
          "url": "searched-locations-history-data-iossimulatorarm64-0.9.1.klib",
          "size": 11173,
          "sha512": "0c132f6e5eb411f304c906468b00a0f2e8bd700c8fa301ea12a7d6c95dcae7e89811c64dba913e4d3669ee5190e33b58044ee803c17d460ec4cb72105c048e24",
          "sha256": "997fd718b86c299f9723437d1acd93a5f72e718c5cdf00fa9d6b376121202f38",
          "sha1": "e4dfb363935cd427ac64b334fc194f789158f964",
          "md5": "43afd3337b240a51ba7edd36c78e4104"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "local-storage-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-data-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "searched-locations-history-data-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "3df85b1acd6ee4963abdf261aa32f3bd4ab8eab19806ddc4c8fba82f6f906b2b5b575ec96274210c2ec3fa6385c43b4273177aca52886691e8003c665d36c2e9",
          "sha256": "bc4c2fb1600ddbd7e4e169613ada31ca2334a4b6d369f3bbde6ba0f11528a0b4",
          "sha1": "4b1eedf7790694604cc1fd3241e3ecced6656855",
          "md5": "3183e2a6e01dc6e2f2f37e85fc80b14f"
        }
      ]
    }
  ]
}
