{
  "formatVersion": "1.1",
  "component": {
    "url": "../../searched-locations-history-usecase/0.5.0/searched-locations-history-usecase-0.5.0.module",
    "group": "com.mozio.mobile",
    "module": "searched-locations-history-usecase",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-domain",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-usecase-release.aar",
          "url": "searched-locations-history-usecase-android-0.5.0.aar",
          "size": 2326,
          "sha512": "a1e350a008d75a0808fe1912148cc3254bfb92df6f21c67bcf6a20b0303992485924fd10dede786e61b6dbfc3f45f6c7751d50954f57fd6504d8c4d40e8d62b9",
          "sha256": "21fa04d4e8eb1f9c5903a67b16009c80317e350abdd3cd069f01910133a293e6",
          "sha1": "5ce6376535e525d817a2442f52eb9cea2bdf664a",
          "md5": "4363b59b006168f27456209190e44d54"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-domain",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-data",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-usecase-release.aar",
          "url": "searched-locations-history-usecase-android-0.5.0.aar",
          "size": 2326,
          "sha512": "a1e350a008d75a0808fe1912148cc3254bfb92df6f21c67bcf6a20b0303992485924fd10dede786e61b6dbfc3f45f6c7751d50954f57fd6504d8c4d40e8d62b9",
          "sha256": "21fa04d4e8eb1f9c5903a67b16009c80317e350abdd3cd069f01910133a293e6",
          "sha1": "5ce6376535e525d817a2442f52eb9cea2bdf664a",
          "md5": "4363b59b006168f27456209190e44d54"
        }
      ]
    }
  ]
}
