{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-usecase/0.8.0/pricing-usecase-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "pricing-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-iosSimulatorArm64Main-0.8.0.klib",
          "url": "pricing-usecase-iossimulatorarm64-0.8.0.klib",
          "size": 4811,
          "sha512": "9dd5129ca1a8983ebf7a94b6ab8810f1b03e4d43ba0f6a374cdd3dc813044bc7b1470571a0d21e59dc6c4c1cc63248b07f01a731da13759e309852689b385fa9",
          "sha256": "e3d1c79c737afa6f3a865db4dcdeed91605ce9bba15755ea21b16a9778ad574e",
          "sha1": "32df9556b0ad67da952b1965ddd335869d1bed64",
          "md5": "05d131f2e98fd7159a03f8b8bb4b95c7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "pricing-usecase-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "1fe53e58bef1d4b37642f05ec8d877b7339b8f93d7a49e88e6b1d69e5144143d7f460125cc304308ba2101e06b66288eec8aad5ce764dc763f6295961df6d899",
          "sha256": "1b456ce079d4fe720e4682f13a5fa3208cf5713b43b16027e112711f66c6ff37",
          "sha1": "7986da604c7be9a5824a7895b0e3e41387f5dace",
          "md5": "850ccdd0ab024d29d5f71e632952bddc"
        }
      ]
    }
  ]
}
