{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "core-permission",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-metadata-0.2.1.jar",
          "url": "core-permission-0.2.1.jar",
          "size": 12463,
          "sha512": "6c255a966b96bbdf25d0e3d26f5b6c1ef045fc9d4dcf48f6aba81f4e84c638eb3dd55781b62f4ee31711023d85fb74e3ac5fd16037b57d264f33222d23a367ec",
          "sha256": "a062dd161d5cde80a1f11fd0b2f8408dbb494d2062cbfed42135b66f7a37d282",
          "sha1": "9b17d4d629653224699e858de707d3fcbc5ba620",
          "md5": "fb94f493cfb5242c76130aa9cd51220c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-permission-android/0.2.1/core-permission-android-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "core-permission-android",
        "version": "0.2.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-permission-android/0.2.1/core-permission-android-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "core-permission-android",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-permission-iosarm64/0.2.1/core-permission-iosarm64-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "core-permission-iosarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-permission-iosarm64/0.2.1/core-permission-iosarm64-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "core-permission-iosarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-permission-iossimulatorarm64/0.2.1/core-permission-iossimulatorarm64-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "core-permission-iossimulatorarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-permission-iossimulatorarm64/0.2.1/core-permission-iossimulatorarm64-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "core-permission-iossimulatorarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-permission-iosx64/0.2.1/core-permission-iosx64-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "core-permission-iosx64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-permission-iosx64/0.2.1/core-permission-iosx64-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "core-permission-iosx64",
        "version": "0.2.1"
      }
    }
  ]
}
