{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-domain/0.9.1/authentication-domain-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "authentication-domain",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-domain-iosSimulatorArm64Main-0.9.1.klib",
          "url": "authentication-domain-iossimulatorarm64-0.9.1.klib",
          "size": 44194,
          "sha512": "d7f6ff177d9c89f07fb2a21c66a13558613985006232971cf2dbf701650583abba202c0c007dfdd67892aac89a65c4c40a61ed3d2f43aa0029c15d97d02d8707",
          "sha256": "a3f98b8d195b38baf99e32d9e439800c071bb3e79f7c257a686e022ccfb2d532",
          "sha1": "381beb70f2d41de21f69d69e8550a258ff06161d",
          "md5": "b8e133a2a20929555653a5235241aa81"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-domain-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "authentication-domain-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "9554dc3196add4e3ebd385a095aa4636ec84497d0c2d0c7e555ce9573b38fe73f4e06f39d07e2946b13043c57776e7dd44b362aab7f89e56495d27a4116cb857",
          "sha256": "196b88340875e34dad7b4c6768c79a3ee98f951b7617568a54d22506d075ea24",
          "sha1": "68beba08249d01fe29eb38ac70e67efbe7f27a80",
          "md5": "310e20bf6a7d2f54ee9ac7d31b15886b"
        }
      ]
    }
  ]
}
