{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-permission/0.7.1/core-permission-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "core-permission",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-iosSimulatorArm64Main-0.7.1.klib",
          "url": "core-permission-iossimulatorarm64-0.7.1.klib",
          "size": 34114,
          "sha512": "205ba8e1da357f60958ff2496ada6e745854a277382cb37ac74b7d769e8a5d3f38bfef0c9b9c36c9fb1a47fd97447d66468585efb766753efcc915447e42e079",
          "sha256": "904a7936db85dd734c32f089612c8ad5e3a266f0064ba4b7640e1f33b7614682",
          "sha1": "ddac25186078ddd68c13e9cecd056df3a805d90f",
          "md5": "de2a7164f9af3f179a8212e9baf19736"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "core-permission-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 3170,
          "sha512": "b0424782b488a0ed147ab4bff5ddc0c30d414bf6db716aee62dc79a05c00c6ab65f4534077d12bd137cc5374bc489f3b00045ed012a3735454bf6f6a5d786e4f",
          "sha256": "15d31748e61b97008f6a68ca72ecb6e5890882f481e106abbd2158e4288c88f4",
          "sha1": "3c3154d04783034c795eb93235f14abd89e41771",
          "md5": "cc2620adcd3346d92ecb1f0f007dbe4d"
        }
      ]
    }
  ]
}
