{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-usecase/0.9.1/user-profile-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-iosArm64Main-0.9.1.klib",
          "url": "user-profile-usecase-iosarm64-0.9.1.klib",
          "size": 4865,
          "sha512": "b42e7c97eec6dcab7634ea4048500d85e2f7f918539edfcde9bdf8b9883c94b44742e47e7867f05aebf49c4cdf58f2aace133531272835ebc798761fd85b1677",
          "sha256": "8d613ab5c929dfe75328aeb7304d9a3b9b4d6aa915cb34b26a998346c608c767",
          "sha1": "8bd8e6ed13e3e0cc3bd26cd6b32cc6426e39196d",
          "md5": "93cff77f813e73e005d6b935d347cdcd"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-iosarm64-0.9.1-metadata.jar",
          "url": "user-profile-usecase-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "0d9fc7600b61b5cb8b05c004b09a1b940d9cbda3113e777423a3842e2e7b1cb1ecae89e55045efd2500d8be518ba9b2d29b66a244f20783bf835659f6be1dba8",
          "sha256": "c588f02c24bb70a9d9d32c284c0b861905314ab33b5d6c5135c453f8fa138eab",
          "sha1": "c3f67c81aa50cbb922dd52528aae5566a6969538",
          "md5": "efc1eeed03038a300bd6867646cf1a12"
        }
      ]
    }
  ]
}
