{
  "formatVersion": "1.1",
  "component": {
    "url": "../../search-domain/0.7.1/search-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "search-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-iosSimulatorArm64Main-0.7.1.klib",
          "url": "search-domain-iossimulatorarm64-0.7.1.klib",
          "size": 57561,
          "sha512": "773abbb7297967c8b7812e7bd694540a23749e211457ca40dea3dd69de23fd40d2b726b7bed9a1a7ff17ef6357007f688db2030f5f649a52300f5817375775a6",
          "sha256": "6ecc3e206ba2427efe8112c6dff90b2739f4082fa68a9b73fa025b5b0635afd8",
          "sha1": "dd9e9524622584f5328fb3e230eec2a9a53de8b4",
          "md5": "acf9157bc20955f465a74f82690f57a5"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "search-domain-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "bdb3f6fafc0e20c72a50e6cb29b3238ed86a9317cc406f8840b4370be6b5e5c646340da995a85ea8586dab172cb20cfde7370d1fdc083f480d8a6a3ac15e4480",
          "sha256": "e36db2446396562bc1ba375c9edd3f72903d43b1b182601d99ca7bdc82e28c2c",
          "sha1": "a31be6c31f24a235236de5b1a3e4fcb6b283adb6",
          "md5": "c04151bf5c72c2a06bf78060092a348e"
        }
      ]
    }
  ]
}
