{
  "formatVersion": "1.1",
  "component": {
    "url": "../../local-storage-data/0.9.0/local-storage-data-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "local-storage-data",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosX64Main-0.9.0.klib",
          "url": "local-storage-data-iosx64-0.9.0.klib",
          "size": 8597,
          "sha512": "ee23bef4d6c37e8a7eded758def90f649e91be77e6af0b03d814f90b2c3b65ad29b1fc554e6ef1892373c7d06b70c8c1c3dcd210cfd7a5921fb0ec2bc1a2a196",
          "sha256": "937daf4e761e51a1142d6bf1034c0ae32232142bcb2c321cb2baeeef77e8d8fc",
          "sha1": "6f9b4d2439ed690217d7e8c77a170014581856c9",
          "md5": "8d023f3b0ebba0e380befde2d23e3590"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosx64-0.9.0-metadata.jar",
          "url": "local-storage-data-iosx64-0.9.0-metadata.jar",
          "size": 2471,
          "sha512": "0ab5542d6658576f43ec8d9a787a0fe732377b6128abf5609658814850efb612b72b8d3624ac320486aad6487fcf57b4ec6ced010ae928c78fe1547d5e818dad",
          "sha256": "44d3e92afc708b73c149d7089a8c337ff26f8d61f02e3b67eaebf6bf7fb86238",
          "sha1": "662678be2ca53458d8c3371f56866878d7c62b5f",
          "md5": "92ec8f3c2ffeebaf51a928ed69e10886"
        }
      ]
    }
  ]
}
