{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservation-details-usecase/0.7.1/reservation-details-usecase-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "reservation-details-usecase",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-usecase-iosSimulatorArm64Main-0.7.1.klib",
          "url": "reservation-details-usecase-iossimulatorarm64-0.7.1.klib",
          "size": 5175,
          "sha512": "9067083b8d763240f566b205320e811a79457175550cc0c11505524ac3ffa755044209234daba00988f45454be11c4afb69a9559b0a714538af145f4601771d0",
          "sha256": "67d53519f1cdbed9079f23a6067e06e47b64685d4778a9d33299362e8dadba0e",
          "sha1": "56371e21ee7378a121b50ae842390e0ac64a26b3",
          "md5": "f63f0d3cc86d6b52de1d08a04b8e91b5"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-usecase-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "reservation-details-usecase-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "5c2609c90c11671e4592b2044d264505fa6e016c983c453bd18752df955b7d785de73bf814fa1f21e6deda84dce4c7b19606439d6346592c26cfa971100ec448",
          "sha256": "ff731fc9d9d8e707b66cebe5cd566065bd216fe76eded62d0aa7e9e19929c4f2",
          "sha1": "76f55bcfc9a910d20b125f3c7d765563728c45ea",
          "md5": "eeab0b033c0216dfffcf290924a1d843"
        }
      ]
    }
  ]
}
