{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-data/0.7.0/countries-info-data-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-data",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosX64Main-0.7.0.klib",
          "url": "countries-info-data-iosx64-0.7.0.klib",
          "size": 16409,
          "sha512": "8a97dee0da86168271f3aafac291d35e9c0cd625e57083affbca2568104db182ae71b33fb164672e65a39d249df51a7ae535ade2c98d9ed359a474a24cce7f41",
          "sha256": "ed398d0fc11410ec1173482c2903a1033db727e3e7b15c6b9a66526bc95198d4",
          "sha1": "25383211fad24549a9e59413a68cd6100af06f38",
          "md5": "947aaaa7a0426a9b91d6c0565e883e77"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosx64-0.7.0-metadata.jar",
          "url": "countries-info-data-iosx64-0.7.0-metadata.jar",
          "size": 3304,
          "sha512": "fdcd90e84a1c1079372975f0a233bcf5d999f49d823f7be4f7d0d68eac0f325341fd18a2b2428de0a25962c4809b430e25cd4c4bbedec34fd760c7cc8a4be07a",
          "sha256": "1631f6604fea1cb8cfa1d9ccecfa396f9d96ed68de7870e25c71dcc68e049c4f",
          "sha1": "0254d9902a819de3881309380b7acbed72e096e9",
          "md5": "85ef40044e1dc7519fec918589002f41"
        }
      ]
    }
  ]
}
