{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-domain/0.9.0/pricing-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "pricing-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosSimulatorArm64Main-0.9.0.klib",
          "url": "pricing-domain-iossimulatorarm64-0.9.0.klib",
          "size": 23211,
          "sha512": "60af00e075f2cb76f8da7affcc75eb9290a38876202c16799b1f911cf578edb20641c7b65cd43e393997159cfb1aad4f89e98ddcfe7fcdf21723f4704cb72f61",
          "sha256": "e07ba48aae814ae1ade70ba270396ecbdd55b1f44cdfa78cfd29263b1eb696f7",
          "sha1": "9659752f724d1f3fece3b31b838f57faa3fce0d3",
          "md5": "3f49d3cf25e76c2c3d149b154ea81057"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iossimulatorarm64-0.9.0-metadata.jar",
          "url": "pricing-domain-iossimulatorarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "bd079d0e1c02d6c3f407bcb3be26bff829fa262f4165a2745132d566ca1b847aad41f2d113aed74f0172c2013fd383b8b4b898e8eb26a5ed07a086aa4121e51d",
          "sha256": "67b13ff7673865953f1d0d69e1f278e3a0c9ee2efa30dbdc8373301d16c99844",
          "sha1": "600a31749b4f3c968826eff71f8d9f66c5bd0e3d",
          "md5": "5601d1cd4683f4ba12b48c5eb8ba1c12"
        }
      ]
    }
  ]
}
