{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-coroutines/0.2.1/core-coroutines-0.2.1.module",
    "group": "com.mozio.mobile",
    "module": "core-coroutines",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-coroutines-release.aar",
          "url": "core-coroutines-android-0.2.1.aar",
          "size": 14744,
          "sha512": "39f1458bfbdd0beb7ee79336c23884070e3e0d32135a89278cba8c1331ced07a4fdf582647c414a11b1f25e0a8b10dfcda7239ec7ae325f424c5d3bcb306cb2a",
          "sha256": "41a4e606ab17562a31dc1d75c1d46bf89ace12f0f15165ec5a1913d3e1a6e6fd",
          "sha1": "187722e2c8b0ab3b5e92ea7ae345608d9c505e40",
          "md5": "c9eea5bb61be971263aed074cbbb6d9f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-coroutines-release.aar",
          "url": "core-coroutines-android-0.2.1.aar",
          "size": 14744,
          "sha512": "39f1458bfbdd0beb7ee79336c23884070e3e0d32135a89278cba8c1331ced07a4fdf582647c414a11b1f25e0a8b10dfcda7239ec7ae325f424c5d3bcb306cb2a",
          "sha256": "41a4e606ab17562a31dc1d75c1d46bf89ace12f0f15165ec5a1913d3e1a6e6fd",
          "sha1": "187722e2c8b0ab3b5e92ea7ae345608d9c505e40",
          "md5": "c9eea5bb61be971263aed074cbbb6d9f"
        }
      ]
    }
  ]
}
