{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-location-domain/0.9.0/user-location-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "user-location-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-domain-iosSimulatorArm64Main-0.9.0.klib",
          "url": "user-location-domain-iossimulatorarm64-0.9.0.klib",
          "size": 13588,
          "sha512": "c505183e18a517fa3003c6ccb0ccd917bc8c51b3c00f0324eae36a2a43734e7452481dd12d6bebd515321461ae62f98da210a4e117f24afaa604655665bb5005",
          "sha256": "331d41d03d255817c3f46dc01394e8760fc091f810d33733545a810ed40a38c1",
          "sha1": "3d303393a8e2e698a2a74909765f1bdbb36839f4",
          "md5": "9f4a484ac9bcb95ac78262af2d46efa0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-domain-iossimulatorarm64-0.9.0-metadata.jar",
          "url": "user-location-domain-iossimulatorarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "8d08b984c933284421aec54a4b696546b40cf2c02a597a36377fc2d0ce196d1bea178e38a8872efc4f87c7bb02822f6ccdc95dc34bf897fc73177fdc7422d38e",
          "sha256": "8dbe6d16adff6f4722e051ae792f67c6b50191db96c0053b8c9dca4d4732f894",
          "sha1": "f9cebd356e9b403455345f52793e0e97411c5909",
          "md5": "e1530108a01094e246adaeaf24c59ea7"
        }
      ]
    }
  ]
}
