{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-location-domain/0.7.1/user-location-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "user-location-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-domain-iosArm64Main-0.7.1.klib",
          "url": "user-location-domain-iosarm64-0.7.1.klib",
          "size": 13627,
          "sha512": "ffa4589b2c91e72c1cc439bd48501a33f72b981c80b96fb5325e4b34fc521b0ad005a886bcf0412640c2f9add580359b7cfb62874b81b7f21e001deac06d0965",
          "sha256": "50cfae47eca0f58dc699f43941e2d3a80419230438836fad6e94f5fe15bbc8dd",
          "sha1": "4f1e0a767e2abc30b2687e4e5bb2e20f4db90d65",
          "md5": "91f67547161c9265dd4a0fe2efb47629"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-domain-iosarm64-0.7.1-metadata.jar",
          "url": "user-location-domain-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "c958e01f30b50396c6da6e312af7f067f59e2483e76cd45007bd82b62d57ebc6dbc33c649b13b10ea3acba7d121086e96e3ffb9ff9c8f1c396a6b30b4b4bd684",
          "sha256": "6def8355fe18d19344fecf93004405f889efa104cd0c637d795c3dfc16f91638",
          "sha1": "600466571a14743d06714c72041a0d392833308c",
          "md5": "6d5dcf6d88d3157bb5979fc31502bdba"
        }
      ]
    }
  ]
}
