{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-usecase/0.9.1/pricing-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "pricing-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-iosX64Main-0.9.1.klib",
          "url": "pricing-usecase-iosx64-0.9.1.klib",
          "size": 4734,
          "sha512": "4799bda0ea5b4d8989b262213fd346a21a896fe5594e6c2bcb187e8705ba7f98677db0ce0775eb4b861788732b4bf91593b8bf4338a64fa2a1556205ab67cb16",
          "sha256": "3315e6fa750c9ebdc21c02e3c91d0b94b59bd1987d866f9cc9b32316cfc93cfc",
          "sha1": "f79dfea9ba137dc55e0661d587628c19d964c1de",
          "md5": "19f4ac690731f287bb2ba6628957a1e8"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-iosx64-0.9.1-metadata.jar",
          "url": "pricing-usecase-iosx64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "d5dc1b5ebc9da1a7d1842447af973bfe34a1f1ce9df01d0467037138a2b1503250d560f269bca0fbabb6dd043b43fd1d15a24bba63b3b83c52f41d576521adf6",
          "sha256": "fe7c58202766871c2828adf454e3ead93a266628284960b1f7fd35e80590e0c2",
          "sha1": "4431b7cf43de60b0980f7f051bbfcde34451b5b0",
          "md5": "8cd93f1d804bf5b58adf3408a30aab1d"
        }
      ]
    }
  ]
}
