{
  "formatVersion": "1.1",
  "component": {
    "url": "../../search-data/0.8.0/search-data-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "search-data",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "search-data-iosSimulatorArm64Main-0.8.0.klib",
          "url": "search-data-iossimulatorarm64-0.8.0.klib",
          "size": 159065,
          "sha512": "1cf7be92e2bdd76104329877552f5c55c18ed54c9ad12336981a0d3da0e5cf3ad20f99afe030d222e86a22f1b94b12c0d1eca6c647dd94e8872cd7ec1e8c1e38",
          "sha256": "4b5d339a541182abcf1fe4f832cf4acf75fec775987fdb2e42e40d3487a1e3cd",
          "sha1": "30ae0331e2f420d1129f3929760ebc272749437b",
          "md5": "f7a19c67e67a2e6ef1ad0d29aa2fd1a9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "search-data-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "search-data-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "2e2f68eb2f00096e073156ccdd12a3a1380cf3225952cc1ee7e0be3cffc8e12c857d378c773f2b2606b20e810f3048a9f4724e97af33ef211296c6e46f4e3bb8",
          "sha256": "f6ecbb457b43b1f0b0e60bfa94dcdba47a07ba1f315e88fc7252d824e6145f0d",
          "sha1": "3bc8f1ffd09c10717932142dc75dbe8035fb0b1d",
          "md5": "a3114321dbaa420c2e46ee3ff1191f72"
        }
      ]
    }
  ]
}
