{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-data/0.9.0/user-profile-data-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-data",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-data-iosArm64Main-0.9.0.klib",
          "url": "user-profile-data-iosarm64-0.9.0.klib",
          "size": 54968,
          "sha512": "496166bb3d67af7f24c1a0037a65a173c7f5507132ddd658705fae85afd9faa8701f1e298f3dce2ed2f6e758af983c9bfaef918701cfd58e94ed2f0b5579c77f",
          "sha256": "b78dbccb2a1b224f54053c07c6a420677e12d647e92869688f019cbf0cbf1f5e",
          "sha1": "e3b019883d3b14d3f371c99b7595d52ee1107bea",
          "md5": "c7afd84134ee29b6b51a9de92841167a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-data-iosarm64-0.9.0-metadata.jar",
          "url": "user-profile-data-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "4f68f7e5990db6716c18e4db672b2fe15ee3989eb3667c2c69d055faaf3ec3567490fef1b22afaf8f80c1411c89ae7998c275303b30de818df30e1f657daea9c",
          "sha256": "05f10f2e23ed5b93d5b53a606f34ae6e11e4b4d51651842fd1d07b2c8a50515d",
          "sha1": "a3b555009c217d4ec4881dad42a0eb5d86239e4b",
          "md5": "eca772c1563daec430b0ddcae2c4f053"
        }
      ]
    }
  ]
}
