{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "locations-usecase",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "locations-domain",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-data",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "locations-usecase-metadata-0.5.0.jar",
          "url": "locations-usecase-0.5.0.jar",
          "size": 2497,
          "sha512": "528df63004a7d67f7a818e457d2c05bf817ba32fe053df58ee27ec3beb7cb6c8f338fb434fb2da8dbec9af010ac23c98f22e7ede1d94c46ce4f4ed5de6c62bb0",
          "sha256": "b7fe2621b1ee4ae5df4a4426ee135159eceef8d064d6735613548ab7bcbe89ad",
          "sha1": "cb8f63a4230feb30b5f59cfb7e10a304c2d149ed",
          "md5": "178089a299b11cdc1ea78890b69538c0"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../locations-usecase-android/0.5.0/locations-usecase-android-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-usecase-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../locations-usecase-android/0.5.0/locations-usecase-android-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-usecase-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../locations-usecase-iosarm64/0.5.0/locations-usecase-iosarm64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-usecase-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../locations-usecase-iosarm64/0.5.0/locations-usecase-iosarm64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-usecase-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../locations-usecase-iossimulatorarm64/0.5.0/locations-usecase-iossimulatorarm64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-usecase-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../locations-usecase-iossimulatorarm64/0.5.0/locations-usecase-iossimulatorarm64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-usecase-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../locations-usecase-iosx64/0.5.0/locations-usecase-iosx64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-usecase-iosx64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../locations-usecase-iosx64/0.5.0/locations-usecase-iosx64-0.5.0.module",
        "group": "com.mozio.mobile",
        "module": "locations-usecase-iosx64",
        "version": "0.5.0"
      }
    }
  ]
}
