{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-location-usecase/0.7.1/user-location-usecase-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "user-location-usecase",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-location-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-usecase-iosArm64Main-0.7.1.klib",
          "url": "user-location-usecase-iosarm64-0.7.1.klib",
          "size": 4953,
          "sha512": "819094762a606ac313a5085aa95d9eb92458521aa9839f2b51a9f47b76bc6c383d8f4993443eb5651e30782e8dbb8708d4cabfe2779ddf8f20e4fc853876c008",
          "sha256": "7334b2fa4af2f280b263b5d15e31633b4d3f63d65c5966d265b7652ffbc01a2b",
          "sha1": "f511938267478237a5f652e6c9d899cd9aeaec93",
          "md5": "972773b97d62a60d5bc5775c6aa219f6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-location-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-usecase-iosarm64-0.7.1-metadata.jar",
          "url": "user-location-usecase-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "19916528eabab478a386fcf789920ecafd376f850e27b90ffdf25acd7553b17d709b0155f8e977a2f924216ccf98bbe13f03275f2985acd55159bbaee8a22572",
          "sha256": "fcfc675fa7874f17c46d5fc81cd813694ab6c15673109fc08f55a790636346fb",
          "sha1": "769d2dcb039f19676f0a305933b3ab540756c9b0",
          "md5": "51370f4514ecde8ebd9ebffd0b605f84"
        }
      ]
    }
  ]
}
