{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-usecase/0.8.0/amenities-usecase-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "amenities-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosArm64Main-0.8.0.klib",
          "url": "amenities-usecase-iosarm64-0.8.0.klib",
          "size": 4766,
          "sha512": "478798af66f8bd64d030f4be04eeb58a667941a2ce8cef1fae10d54fff9587d7db3062bd8c9aa491419d2f6d986be2b7d36de4d42bcbef2fb671bcf9431e4675",
          "sha256": "ffe9576dc7d56702b13a08654159b925e6fb3160c2dcde1f935bbcf7d13a81b5",
          "sha1": "7c94614c3f49811726f2e13641a525994d090c95",
          "md5": "f4df1f4ba050e33e0c6c1ea114189816"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosarm64-0.8.0-metadata.jar",
          "url": "amenities-usecase-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "7b8c8f9565f0be564fb10b4ff36c94017d6631d216b40e54ddccf9c326b92c7216c22c757497a0d9b4cda8b525f0c9265db135e7a25c4903669444f952ad088c",
          "sha256": "5f41d25d7b6342b063d04b3a28763a459c56d48363a43fb684f53b660d5e6f27",
          "sha1": "d4f2aea71b92f79a4be18704a836bf28267c51ad",
          "md5": "d6ea97ce63a2a85944c5213c81b4c970"
        }
      ]
    }
  ]
}
