{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservation-details-domain/0.7.1/reservation-details-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "reservation-details-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-domain-iosSimulatorArm64Main-0.7.1.klib",
          "url": "reservation-details-domain-iossimulatorarm64-0.7.1.klib",
          "size": 52477,
          "sha512": "975e82b5368013fa480f041e5391fbfe6ca678bf1c1e9d63596781da72e49976497e46c6ce7f91fc57ff9758d8599203d61337a9a4f2363246358442d377c56b",
          "sha256": "6da96fefd896881cce8a118ff908f97755a8c7ee5efcd450fb12b6acf4f72525",
          "sha1": "01dc414a7b398a6885d17e492ef2bd36e4f70be7",
          "md5": "57a082a901d55f9fe4c76e5b631b0889"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-domain-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "reservation-details-domain-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "ffc6856c921a0bf85750276eace89192e872600b417f932f1915c341fd923bb020308f88baa4d761dd210a1fb28b58d3b9586f2cd487b26e60cea86502659697",
          "sha256": "0913eed9c153b9e531b6284c12b1dc41c27d85a6dbec037fd05c1115c9daa4fc",
          "sha1": "458830880182d1fe70790b04b09c6a15c86982f6",
          "md5": "4ddb03de8ba13bc627648d60f9d743f3"
        }
      ]
    }
  ]
}
