{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-analytics/0.7.0/sdk-analytics-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-analytics",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-analytics-iosSimulatorArm64Main-0.7.0.klib",
          "url": "sdk-analytics-iossimulatorarm64-0.7.0.klib",
          "size": 28393,
          "sha512": "a7ea94e5966fbc9d9a40e33182bdeef602506dbdb9fc3e857aba7971f94c7de49bfccb41e8984482e810b05b416ae7093ba23328f09f5cdc3e513afeef7c32d0",
          "sha256": "bfc23c540f3c58f781e11df0e4a9c3245b385e592f468ab90a2bd3f7903215ce",
          "sha1": "4bbf1bfffc10d09d89388d2c067844f7265ce2e7",
          "md5": "d90d4f8f3f8eed309bf5d923f5a411aa"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-analytics-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "sdk-analytics-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "0ec2b107cf89411591083cbc9cf05adfd65a7ed72041f2f71f212947787d54886b26153008b960397008e48847ffd8c113f67c543707325149e23e766c15fd9e",
          "sha256": "8342fbe0ce61782a3cc5e117e75af46af2c81b3c7226194c8136ce25ffeae221",
          "sha1": "e07e2bc60acdc481b219c1d41679541e280f34c0",
          "md5": "b5dee93e2d2a2a1efed0df40315f76b9"
        }
      ]
    }
  ]
}
