{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile.android",
    "module": "authentication-ui",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-ui-0.7.1.aar",
          "url": "authentication-ui-0.7.1.aar",
          "size": 350207,
          "sha512": "8ac59aa5718ec70198d328687df45202864e883997353c94d7ae99f1885de051db317e715510a12011b5092efd9dee6be343449035775003672f2083010a1248",
          "sha256": "0b3e42b652adbe75b4b6ecbec519ff65aeee90d94e044a13b7e7f2038019b79e",
          "sha1": "04e79e36ce3f0f6ddd8c2437a31c8130cc6c2297",
          "md5": "e8f025ebcb5dd810dfe7b5958b2b33c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "core-ui",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "country-phone-ui",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-di",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.7"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-ui-0.7.1.aar",
          "url": "authentication-ui-0.7.1.aar",
          "size": 350207,
          "sha512": "8ac59aa5718ec70198d328687df45202864e883997353c94d7ae99f1885de051db317e715510a12011b5092efd9dee6be343449035775003672f2083010a1248",
          "sha256": "0b3e42b652adbe75b4b6ecbec519ff65aeee90d94e044a13b7e7f2038019b79e",
          "sha1": "04e79e36ce3f0f6ddd8c2437a31c8130cc6c2297",
          "md5": "e8f025ebcb5dd810dfe7b5958b2b33c7"
        }
      ]
    }
  ]
}
