{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservation-details-usecase/0.9.0/reservation-details-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "reservation-details-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservation-details-usecase-iosArm64Main-0.9.0.klib",
          "url": "reservation-details-usecase-iosarm64-0.9.0.klib",
          "size": 4951,
          "sha512": "78b2766d8b2b2bc899ae55fc8a6a511dfb9abf6c2f7cc1b555729fd7ed9b70ade82ace2c5c45b2949bf6d42233297741fe929962ae3d35b0b726ad93ba00cabb",
          "sha256": "375812d8998d526c6bcfa9a953e03c9670a2e1fbaa216702173bd90e6528827b",
          "sha1": "08b932e8d0879e3a29e70f8f90c3b824b9089f23",
          "md5": "63cbbe39c599c5aca909444e20c3389f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservation-details-usecase-iosarm64-0.9.0-metadata.jar",
          "url": "reservation-details-usecase-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "317fbbc78bd936dc53d6627fdbbd1a3ff3c6de4ae03dbf2f1f280afa6e046a210e25326b303fa4b12c93ba2af9f1dbf19ae8c4e96a3120c0ba69fd714f6a0a6e",
          "sha256": "34d0d9c86cf86276e4fcbad17a384fc12479cb3651a387feea4c4528e2aa0f47",
          "sha1": "3b92309cd5dde0387b6942c0cd611905726dcf21",
          "md5": "e477d78880c290798ffbdabf2168eb38"
        }
      ]
    }
  ]
}
