{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-domain/0.9.1/amenities-domain-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "amenities-domain",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iosSimulatorArm64Main-0.9.1.klib",
          "url": "amenities-domain-iossimulatorarm64-0.9.1.klib",
          "size": 12781,
          "sha512": "9a35d219ee7a62e4bfabee54dc1174dcf6b9f555539d8b96e81c0ec8cfdff34bdcfd4cd4e59edbe2093a38a5d2e63fc2abd05b1a5096b73d2f5b01fd2fb05558",
          "sha256": "8a0c0bf0a12a5e6bd626dea98c3e0341104d017fa3868fe925b27f5b4cd4c934",
          "sha1": "3533cacaaf8cbdc142d87c95c001557b7b61c733",
          "md5": "b2b01f08f4e454561dca5ed7d7c5b2e4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "amenities-domain-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "1e418b25a240d632d938f78ecfe1d1a46945e5bcf10276af1d34134ca0cc82c3b3e715970fbb98c6d6eb6328775ee5147ed8083bb1dc011268374be8156afd6f",
          "sha256": "392600d53c21959949caa8f87b7beb5d20444e162ce3784c21d5abce6856af92",
          "sha1": "5f30ef1022262e22c1e28fd0480d01e13b2d2950",
          "md5": "158478081ee09b6f39166e2a0df40706"
        }
      ]
    }
  ]
}
