{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "user-profile-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-metadata-0.7.0.jar",
          "url": "user-profile-usecase-0.7.0.jar",
          "size": 2515,
          "sha512": "f89d3aea12f5ac25498fbccfc80e50dc5316ad8fa1c08937dfd4dafc9f9668f3c6cb6531eb32f2dde9194b4228165ed52e38049aed243bdbab82fd0002814045",
          "sha256": "27c607c4de8f8bd731e64f0f538737c95242bdb762607aeaf6e00380f6d60ad3",
          "sha1": "7b62aeff4d2d10409c9e41d23ea7e42e0598c22d",
          "md5": "3fe5821d65b057af72c3e3964063d9df"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../user-profile-usecase-android/0.7.0/user-profile-usecase-android-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-android",
        "version": "0.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../user-profile-usecase-android/0.7.0/user-profile-usecase-android-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-android",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-profile-usecase-iosarm64/0.7.0/user-profile-usecase-iosarm64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-iosarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-profile-usecase-iosarm64/0.7.0/user-profile-usecase-iosarm64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-iosarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-profile-usecase-iossimulatorarm64/0.7.0/user-profile-usecase-iossimulatorarm64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-iossimulatorarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-profile-usecase-iossimulatorarm64/0.7.0/user-profile-usecase-iossimulatorarm64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-iossimulatorarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-profile-usecase-iosx64/0.7.0/user-profile-usecase-iosx64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-iosx64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-profile-usecase-iosx64/0.7.0/user-profile-usecase-iosx64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-iosx64",
        "version": "0.7.0"
      }
    }
  ]
}
