{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stripe-payments-domain/0.7.1/stripe-payments-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "stripe-payments-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "stripe-payments-domain-iosArm64Main-0.7.1.klib",
          "url": "stripe-payments-domain-iosarm64-0.7.1.klib",
          "size": 29573,
          "sha512": "00b0b55dca1897fbe06427b179e2a02f30deba4bd1ae7bb943cbb411bed0f9374703c93041f7a838382136be215ff616351e2b8a85abea6d1165a3a342ae8611",
          "sha256": "21c4ab8f8536ba31bf49d20b2afad74f9148504a3bebfacc0ca9df8a7a41e415",
          "sha1": "f2dc0ffea69a9970fabe719390c51571125412f0",
          "md5": "be451f965be153c6f7c136c4771ba204"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "stripe-payments-domain-iosarm64-0.7.1-metadata.jar",
          "url": "stripe-payments-domain-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "1407122f5129f71a53f8a1eb7be7aff24076924a2385d699d48ec10b1f064b2ac9ed8635d8fdf9b26d4869df086e0938a58d48ad2cd458ac9dd9c8ea99d91713",
          "sha256": "6cea8e8305ec2611a4f1d099cfc9f0964d9f560c387f95fe287f918a3b8f16bf",
          "sha1": "1786131e48c77e3c2d40351a269c0d5316054390",
          "md5": "faed7d455e3ce557c4ca0f552b13e516"
        }
      ]
    }
  ]
}
