{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-data/0.7.1/amenities-data-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "amenities-data",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-data-iosX64Main-0.7.1.klib",
          "url": "amenities-data-iosx64-0.7.1.klib",
          "size": 22588,
          "sha512": "d631c2209949b31dfd9be89dd0f99feef76ef8bd15032268b2adb68070e5efb04cd89b1c1c312719cf840e1d30670d2229130d53ee4d3e26e1e079d017b3cce5",
          "sha256": "dd7e4e4dd80c6f77a90fb8f02d38d23d95c8e46962b38fd4eabf0bc03daa1145",
          "sha1": "5ded2ef793d73902d22a5a96fb31b8364248a6a6",
          "md5": "f001b0da9ac37e3fa8ae905b07470687"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-data-iosx64-0.7.1-metadata.jar",
          "url": "amenities-data-iosx64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "6e07b89760e7661c46dd6959f0ef7d3296f41fcf7c8ba28cb2321c17f4b09aaf39ad542e0907470d419f89eb74b951f2b115c45f5fdb60e4c57fec4322b5f019",
          "sha256": "70dfa48f9a2588db59163b008d0e55641ef98e6e78104d53e1c8fcb61463e438",
          "sha1": "16400a3876ec968f53cf8ebf41e9d27ed86b635a",
          "md5": "bdf21f65934c30e1e901ab256059a606"
        }
      ]
    }
  ]
}
