{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "pricing-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-metadata-0.7.1.jar",
          "url": "pricing-domain-0.7.1.jar",
          "size": 8510,
          "sha512": "06eeca0aa34c62dcfe62b683ce64dfeb6548c4025a57e7f841246cf68ec26dba26bbbbcd5c848c87fbf437f1b544cec309dd3a15d0cf917040a015602621e36d",
          "sha256": "6b9c3f83aa75016b2c64ba7904b8ba866ab90c1e2c699cd9d5ead12f2e6e7d7e",
          "sha1": "e446a75d5f55c850a07d6bf6bf3564271b192f5d",
          "md5": "0b905aacb55c2e6c3a9c95702d9e9c7e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../pricing-domain-android/0.7.1/pricing-domain-android-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "pricing-domain-android",
        "version": "0.7.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../pricing-domain-android/0.7.1/pricing-domain-android-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "pricing-domain-android",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-domain-iosarm64/0.7.1/pricing-domain-iosarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "pricing-domain-iosarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-domain-iosarm64/0.7.1/pricing-domain-iosarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "pricing-domain-iosarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-domain-iossimulatorarm64/0.7.1/pricing-domain-iossimulatorarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "pricing-domain-iossimulatorarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-domain-iossimulatorarm64/0.7.1/pricing-domain-iossimulatorarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "pricing-domain-iossimulatorarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-domain-iosx64/0.7.1/pricing-domain-iosx64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "pricing-domain-iosx64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-domain-iosx64/0.7.1/pricing-domain-iosx64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "pricing-domain-iosx64",
        "version": "0.7.1"
      }
    }
  ]
}
