{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-analytics/0.8.0/sdk-analytics-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-analytics",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-analytics-iosX64Main-0.8.0.klib",
          "url": "sdk-analytics-iosx64-0.8.0.klib",
          "size": 27365,
          "sha512": "5e726536fe80027809dfc47692e750caa5a91c38a00fa70a09311b8c801bcd09acce69158958052a623861449b0b90155316e0db9aea6e8093d87c127e2cd2da",
          "sha256": "e9e0949db670efc598024a3309ad80b0fd5b92cf3b9dcfe9e914311b638ecca2",
          "sha1": "9ff53f6bd5414393de76e4d4382146f82e2ae881",
          "md5": "35b259fe5357948156a1610e60a49798"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-analytics-iosx64-0.8.0-metadata.jar",
          "url": "sdk-analytics-iosx64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "117cb4b59730362ce8ac9a56c7a73571ddb57fd9d521ed0f846fc87ade12f8a4aa5f32166b6c27fccb6c7bcabeea219ca510b2b1e37d76ea3a8fa6a7710a2731",
          "sha256": "d677cc6ef4f7784b85469cc221856d8eb73d5ebc8f55e9e5d45bf1381cdf3cfb",
          "sha1": "608f9ed7ae6272e9b75c7ac4918fb287bd968b35",
          "md5": "71686f20cf3ffb8118cdd351cb2d4976"
        }
      ]
    }
  ]
}
