{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservations-usecase/0.9.0/reservations-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "reservations-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservations-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservations-usecase-iosArm64Main-0.9.0.klib",
          "url": "reservations-usecase-iosarm64-0.9.0.klib",
          "size": 4799,
          "sha512": "60ec6ca1b25654eee0172bb85a6914041955a9a36d60f2f894375f0b915ef2fa04b84379e942936aba59ad11b644b34b80d328c5dbd5ab9849779d8d4b9e214d",
          "sha256": "5f62ef840bdc91fb831bd6c228595f18b516951a564555fa544c98743804325f",
          "sha1": "7fb82b0f7401e3636bec1a80516518e0bb2d7a11",
          "md5": "c0461423a26940f384301acc9e3031f5"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservations-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservations-usecase-iosarm64-0.9.0-metadata.jar",
          "url": "reservations-usecase-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "6cf09bc3266b4c0428c37793d7bb978349da94817425f7ac9662fda03baf57ec6449a710e2e1a445882cb3b2e8e18520ed1f93e5435de7a9a53914b721caa95e",
          "sha256": "db8ba8462339992575e60afafe9037b5c4866efcaca278dd2637ab8ff183b34d",
          "sha1": "dcde5afd1f9c3174406f1df30847c5ba43dd811d",
          "md5": "c447814f9afdabac162f6fa243a2cf72"
        }
      ]
    }
  ]
}
