{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stripe-payments-usecase/0.9.0/stripe-payments-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "stripe-payments-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-iosSimulatorArm64Main-0.9.0.klib",
          "url": "stripe-payments-usecase-iossimulatorarm64-0.9.0.klib",
          "size": 4900,
          "sha512": "a585f347c65ed9059815e9836d26984ca811a14459bc1f14a56b9d949ed2025bc4f1a1c5abd4a8b9fd2433c2d4b361b0f78cb6b4c36b6021846c6580f4f94ac5",
          "sha256": "8233078e764200c757f4412c36aa49ac23acfe258d2082b2c4c85b0735e581a4",
          "sha1": "bbd8b593ec3ea197d2f2d560713f88464cadb1e8",
          "md5": "290d58866c214359675d41d15326b283"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-iossimulatorarm64-0.9.0-metadata.jar",
          "url": "stripe-payments-usecase-iossimulatorarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "4f68f7e5990db6716c18e4db672b2fe15ee3989eb3667c2c69d055faaf3ec3567490fef1b22afaf8f80c1411c89ae7998c275303b30de818df30e1f657daea9c",
          "sha256": "05f10f2e23ed5b93d5b53a606f34ae6e11e4b4d51651842fd1d07b2c8a50515d",
          "sha1": "a3b555009c217d4ec4881dad42a0eb5d86239e4b",
          "md5": "eca772c1563daec430b0ddcae2c4f053"
        }
      ]
    }
  ]
}
