{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-usecase/0.7.0/amenities-usecase-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "amenities-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosSimulatorArm64Main-0.7.0.klib",
          "url": "amenities-usecase-iossimulatorarm64-0.7.0.klib",
          "size": 4976,
          "sha512": "5fcac54e3858cd485f37cb4d5852a14c840de5a78235d00a0972122459769160267f87232519d74e58d3abc7229b77c79b21d30a50d915189442abccbfbb2a8b",
          "sha256": "10842dd98cbbd21e7f615c85deaa6a73f6ec07a1723265314c6fef12c1fa462c",
          "sha1": "4e280c99b6fcb4f8b1d60f486d1afc70fe959262",
          "md5": "045d46785c008ce5bd2bf7dba3509237"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "amenities-usecase-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "293692818dee1641197fea5e22831a4c62b03e629caff71840cb2b54fed745cddaa5800a53eb987df38a360aa7a3f5ab339a9aa80363a09101bd5ea775b1745b",
          "sha256": "f24d8bc91ae4fa9b876408ea5ba99ffd704493c379324d07e186aa556db02e22",
          "sha1": "540680740f51a59b584f844a3877c5f48d91ec3a",
          "md5": "206d20b26b7b7e6b16ff2bb40cb194b9"
        }
      ]
    }
  ]
}
