{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-di/0.9.0/sdk-di-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-di",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "sdk-di-iosX64Main-0.9.0.klib",
          "url": "sdk-di-iosx64-0.9.0.klib",
          "size": 7223,
          "sha512": "baaa436b949da58b3a602dbd3e48653f0d35b34a8f1bbda6ac3d07eaebb1daf8d08a5b35706e4c9f835d616a2917a06ad5fa9dc67153598a27e751c500f9da42",
          "sha256": "959b4f8b6b2f83876d2d60601deeefcf276d2b3716d7c8f44bda5dd665c873e3",
          "sha1": "ccb5d523d5040a33041b8a1b95ca1bb0d6fa3e69",
          "md5": "afcb55091ad0173b58289c7c033e5d01"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "sdk-di-iosx64-0.9.0-metadata.jar",
          "url": "sdk-di-iosx64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "b97b2a5fe5afb8252d073f0aea45d113860a95d3765c4653342a903f5dc4189f74f194e109eb302a786d5bfebdb2fea536a05b43c687a0983eafe7d69721554e",
          "sha256": "335767bd60977047a14a285f914d65b8009a8cfebe863813425adf8137a821a6",
          "sha1": "1e86818de4d1c90d9ff2e7d0f533c769d3523368",
          "md5": "87d300bab79802a4f58176f12b7ea6eb"
        }
      ]
    }
  ]
}
