{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-usecase/0.9.1/amenities-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "amenities-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosArm64Main-0.9.1.klib",
          "url": "amenities-usecase-iosarm64-0.9.1.klib",
          "size": 4766,
          "sha512": "478798af66f8bd64d030f4be04eeb58a667941a2ce8cef1fae10d54fff9587d7db3062bd8c9aa491419d2f6d986be2b7d36de4d42bcbef2fb671bcf9431e4675",
          "sha256": "ffe9576dc7d56702b13a08654159b925e6fb3160c2dcde1f935bbcf7d13a81b5",
          "sha1": "7c94614c3f49811726f2e13641a525994d090c95",
          "md5": "f4df1f4ba050e33e0c6c1ea114189816"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosarm64-0.9.1-metadata.jar",
          "url": "amenities-usecase-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "5d932dee3613387bce447bcd4828c60d5fd5ca4e148a62ab0175ecdf3b4b107a3d77882ea43c12770da4f5faeaa3c7ca784e2a251e2fd7f60bc7faa53442df0e",
          "sha256": "8aa20184aa17240b863e75c9b008ef5a6337169bc093fb00189ab073b7e9d450",
          "sha1": "2d1500903ca1b6303fbdc428887b200870b0c20d",
          "md5": "7272f124cb185a18ba601ac077c1de27"
        }
      ]
    }
  ]
}
