{
  "formatVersion": "1.1",
  "component": {
    "url": "../../locations-usecase/0.9.0/locations-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "locations-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "locations-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "locations-usecase-iosArm64Main-0.9.0.klib",
          "url": "locations-usecase-iosarm64-0.9.0.klib",
          "size": 4774,
          "sha512": "7b6be1183222afff07147b2a93ef28fb267f840579437d84ccf749f761f7dbb3a0a5d58ba8b66c55e33d0c6a608e3c0d61bee015ab3ca1a757f9e2449c0b966c",
          "sha256": "339b0327e2b851c4fdc87604ab976e59728be6a6e6eefc06da7350037d4d08cf",
          "sha1": "f9b37920d58f663d03df8ba45daf8b3e402aedcd",
          "md5": "4186fd03ac31ca3421af4e36aef3e368"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "locations-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "locations-usecase-iosarm64-0.9.0-metadata.jar",
          "url": "locations-usecase-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "5835de46698c7924f143dd4fbfa1734e45d63d752d94dbe440d5b8b222fbb22ce03585867c3b07db6482e012cd07e9d8ba83b7dab033a7b171d967c137763662",
          "sha256": "547e3c459ff44d89c6dc9135c6623977889fc6d878d0c8e206a94a6c54c8f9a6",
          "sha1": "5cda3bdc52850ac9ccc2378a178171a7166602c4",
          "md5": "481533bf1845a5ec5f2a7aac95ca1abd"
        }
      ]
    }
  ]
}
