{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "search-domain",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-metadata-0.2.1.jar",
          "url": "search-domain-0.2.1.jar",
          "size": 15111,
          "sha512": "ecd0416f5a2655f92fe7372a8076989c4ade15d16710d6bc27fc39bfb5342439e0e9fc2affa796ef8dbdf24580bb922a7ec08e8d40a7934e16c037e9c3653440",
          "sha256": "217bb7bf4fc463c64a776a9f0545b45149603bdb60b84fd583e4852a454657d4",
          "sha1": "bf41588ecaa59bdc4bde61a851afb1c4296c0381",
          "md5": "f43c02fabf859de9555341cebd1abd2b"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../search-domain-android/0.2.1/search-domain-android-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-android",
        "version": "0.2.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../search-domain-android/0.2.1/search-domain-android-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-android",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iosarm64/0.2.1/search-domain-iosarm64-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iosarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iosarm64/0.2.1/search-domain-iosarm64-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iosarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iossimulatorarm64/0.2.1/search-domain-iossimulatorarm64-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iossimulatorarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iossimulatorarm64/0.2.1/search-domain-iossimulatorarm64-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iossimulatorarm64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iosx64/0.2.1/search-domain-iosx64-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iosx64",
        "version": "0.2.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../search-domain-iosx64/0.2.1/search-domain-iosx64-0.2.1.module",
        "group": "com.mozio.mobile",
        "module": "search-domain-iosx64",
        "version": "0.2.1"
      }
    }
  ]
}
