{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-usecase/0.9.0/pricing-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "pricing-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-iosArm64Main-0.9.0.klib",
          "url": "pricing-usecase-iosarm64-0.9.0.klib",
          "size": 4747,
          "sha512": "48051892cf1d34f1d37dc02c505899275639b9f89a0b6022e801a126097ad17068b7442532fad8771415412079b2e97b24a09181218d5617298c285434248796",
          "sha256": "b8984e519209f71e1a864c80197b40cb7898dc787906684f794332392d8b9aa8",
          "sha1": "e148a12ab4b8f75eb0731304915e6a616c67c22f",
          "md5": "9d36ee7c9ff987ce7301d6ea1f47ebb5"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-iosarm64-0.9.0-metadata.jar",
          "url": "pricing-usecase-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "c55c24873fe5f9ec46f690b108a5a8c55e6c0c05a62a99ceff0e2a80f2932ea36422d8b75a2bb05770fd7794a7c68487a90376aa6d801882a268123ab5d7d47c",
          "sha256": "d3d329575293ad238a1bd348207186f544abe936fdd70429b36dea8aa6eca874",
          "sha1": "71d0332e088e0321fdda73bbe462469eabce3351",
          "md5": "e1b38d66d8c9380e24fe5ba8692cc3d8"
        }
      ]
    }
  ]
}
