{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-location-domain/0.8.0/user-location-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "user-location-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-domain-iosSimulatorArm64Main-0.8.0.klib",
          "url": "user-location-domain-iossimulatorarm64-0.8.0.klib",
          "size": 13588,
          "sha512": "c505183e18a517fa3003c6ccb0ccd917bc8c51b3c00f0324eae36a2a43734e7452481dd12d6bebd515321461ae62f98da210a4e117f24afaa604655665bb5005",
          "sha256": "331d41d03d255817c3f46dc01394e8760fc091f810d33733545a810ed40a38c1",
          "sha1": "3d303393a8e2e698a2a74909765f1bdbb36839f4",
          "md5": "9f4a484ac9bcb95ac78262af2d46efa0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-domain-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "user-location-domain-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "f0515a1140385d331f7c5d9dab8981358d23d657c96ce21ac24e45beb6e896d1fba07fab93c26a9f9cd772fc51a6f764bd18eafce9c7b9a7bc20f7f19c99721e",
          "sha256": "3a1e3ed6263b50ba5dca5052379d0be1f99568148b8ad747999034cdf3ac6679",
          "sha1": "ddc8a98c93bf8512ca33775638fde3587d7682dc",
          "md5": "2ec4916105f58d667085a5bcf71bc72a"
        }
      ]
    }
  ]
}
