{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-domain/0.7.0/countries-info-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosX64Main-0.7.0.klib",
          "url": "countries-info-domain-iosx64-0.7.0.klib",
          "size": 15263,
          "sha512": "83b4f532f0ef313127bf081b90b297320543e65ef9be65c7b16e15fa1f0a2057f33e63af5cfb46cb8fdffe870b1532b9efb1dbc278b839d342beadcb56ceab43",
          "sha256": "4bc417b50ef2ed967f1dacda550c65b2a2d9372aba027ad0fa087329394c6374",
          "sha1": "e7eef375d6c5b45ad64f6dcad590f9af1ddd71e7",
          "md5": "123222b9384a3436fe611b32053ce099"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosx64-0.7.0-metadata.jar",
          "url": "countries-info-domain-iosx64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "3de90eefdcb60c672edf2061d8b242bdd6e1fb38d4cff3660b7a72a399ad38ecbc08eb0ab2cabf102b129839f000699ad8185ab6f6dc2d07ffb158329bfa071a",
          "sha256": "8146593157de5e2204a61a83365d5b58d78518802d76d33a22f930a0915c1699",
          "sha1": "83ad5cfc278813629380d047a014c9316d8455f1",
          "md5": "19c787cfa38a5e8dc645a13d2df589a8"
        }
      ]
    }
  ]
}
