{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-data/0.7.1/countries-info-data-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-data",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosX64Main-0.7.1.klib",
          "url": "countries-info-data-iosx64-0.7.1.klib",
          "size": 16409,
          "sha512": "8a97dee0da86168271f3aafac291d35e9c0cd625e57083affbca2568104db182ae71b33fb164672e65a39d249df51a7ae535ade2c98d9ed359a474a24cce7f41",
          "sha256": "ed398d0fc11410ec1173482c2903a1033db727e3e7b15c6b9a66526bc95198d4",
          "sha1": "25383211fad24549a9e59413a68cd6100af06f38",
          "md5": "947aaaa7a0426a9b91d6c0565e883e77"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosx64-0.7.1-metadata.jar",
          "url": "countries-info-data-iosx64-0.7.1-metadata.jar",
          "size": 3304,
          "sha512": "901a63cc783baf2a5e1863fdb4738dad8662e36afd1dd32e871363d86b288c9c838db55ff8f895634b39e1d729dcc3b036270700b0cc3d4bd3f5176aa0cedeba",
          "sha256": "e3e58d3fe1b115b0f6f82ec9087353da15c9a26a036d5a84afb7cd8452de6916",
          "sha1": "e310d3b9d45cf397e2aacc5886e76e7001a7435e",
          "md5": "5b9024edc0fe19a28c309f641286f9f7"
        }
      ]
    }
  ]
}
