{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-domain/0.7.0/pricing-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "pricing-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosArm64Main-0.7.0.klib",
          "url": "pricing-domain-iosarm64-0.7.0.klib",
          "size": 23444,
          "sha512": "ecabfc42b8a3b4ebf1f07e8cf0a69cda53cdf70d42e1c948e5f1540ae5abd0dc2859e97c1bfc53544faa8006cba4d727db530a1c0a611be181f89a75789c87e4",
          "sha256": "749e82302c3edcff4a65a545b7aa685cf2121a4b0181ebd51e10dd4d694517b1",
          "sha1": "7c9efa9acc785630e6122e1913b334f7a9821b94",
          "md5": "9e0dd6d602f1c5b266f162b6ce4520c7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosarm64-0.7.0-metadata.jar",
          "url": "pricing-domain-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "dc0406b6a7dbd51704cdeae719726b0d50447c8a87a9d0fd718627b8d48f6ef7b5d449abafb90ad3e0c0dfef76a48be810a64a57484616e0bc8d9126addf7552",
          "sha256": "08284ab7aeb61f87db18e1eb213aa65a87d741a66b33f2032e7d85e4a88bfe93",
          "sha1": "4a79514d2d2c16b5436f80a171568ecc5a6d843e",
          "md5": "f0f7773619a60b22e5de056cf4387283"
        }
      ]
    }
  ]
}
