{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-permission/0.9.1/core-permission-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "core-permission",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-iosArm64Main-0.9.1.klib",
          "url": "core-permission-iosarm64-0.9.1.klib",
          "size": 33816,
          "sha512": "60dfcde5214ee77db54b0ce23af95b7f613c84b7121d731641bfbe8f2fb09b7ae575f0a04d1a8f3b87dade6f0ac5788ea182f6ddef4da70dc562368b7c8cc99f",
          "sha256": "3ddd3f37016737fef46cfd38df87bca3b93bf7fa3c2a5605ed4a4925a6252212",
          "sha1": "f035abe695b8b5d96be8ae1b3629dc5cab92507f",
          "md5": "ddcffb55c6aafbdbe53ef0341122b709"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-iosarm64-0.9.1-metadata.jar",
          "url": "core-permission-iosarm64-0.9.1-metadata.jar",
          "size": 3162,
          "sha512": "14b13d9d70c12e8f16b6df479c5ae26d6e5dc1b0d8b5ae48a73afe4fb46e2da375bd199b198accd4d8802672b2ff52c4590700067ced795d3141df9d6ca6ca6c",
          "sha256": "97abe20dc597fd0a64c6b54f1a582a5c51e74eeb9569c578dae0def97c4beecc",
          "sha1": "357674af0d9beab9dbf9eb6b756753679f21a59e",
          "md5": "ec07833a2e0379f10066dc19bf3a4ff6"
        }
      ]
    }
  ]
}
