{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "sdk-api-config-environment",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-environment-metadata-0.8.0.jar",
          "url": "sdk-api-config-environment-0.8.0.jar",
          "size": 3156,
          "sha512": "e563ecb94414348c404dd8543e9a64404be8329d9f0239820e0dc5fb9038b6a2cece5bd4a96e3bf666705150421e2a7ce561a3c416b4667e1c7b813dce8a5f92",
          "sha256": "dd0c3bed424d6e8c56e8be9c3a8d237fd7ea0c657a7dfa7678568540859f1e0b",
          "sha1": "95c957793650b2c7931e8e7cd5903a8d5c086314",
          "md5": "8a424ec11ed86b8d6034ae68d1a33dfc"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-api-config-environment-android/0.8.0/sdk-api-config-environment-android-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-api-config-environment-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-api-config-environment-android/0.8.0/sdk-api-config-environment-android-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-api-config-environment-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-api-config-environment-iosarm64/0.8.0/sdk-api-config-environment-iosarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-api-config-environment-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-api-config-environment-iosarm64/0.8.0/sdk-api-config-environment-iosarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-api-config-environment-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-api-config-environment-iossimulatorarm64/0.8.0/sdk-api-config-environment-iossimulatorarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-api-config-environment-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-api-config-environment-iossimulatorarm64/0.8.0/sdk-api-config-environment-iossimulatorarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-api-config-environment-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-api-config-environment-iosx64/0.8.0/sdk-api-config-environment-iosx64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-api-config-environment-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-api-config-environment-iosx64/0.8.0/sdk-api-config-environment-iosx64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-api-config-environment-iosx64",
        "version": "0.8.0"
      }
    }
  ]
}
