{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-domain/0.7.1/authentication-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "authentication-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-domain-iosArm64Main-0.7.1.klib",
          "url": "authentication-domain-iosarm64-0.7.1.klib",
          "size": 44736,
          "sha512": "c9e0f1c9adb1e9fc51668f6ab78ba46f968bf98f5ade59834a28105fa419b62224666d426d1d1b7c7a5a8dd2052ff4d8cf78bc0141fd430e9d2fcdb63557d70e",
          "sha256": "c001f8759c2c435ff85f5f681971ae30755fc42be2060675ee86ceec6097f91c",
          "sha1": "dc7f85ba8657824e61adef06bf60741be98538a6",
          "md5": "187698660b45337c57075e745d2cbffa"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-domain-iosarm64-0.7.1-metadata.jar",
          "url": "authentication-domain-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "a4f35ab579380fc8c1933b91d54fb36997b7d9472c3a806a4376268b1d8de0c3481c3a19d41719d46eae33a71826d9333ddf095cc545ec4805cc424b70c91c52",
          "sha256": "6ff6344c9f5ce544f8d3ec7f415d4bc2a5aea9a36040738ae21209907d316f44",
          "sha1": "5d431fe103852bdc1dbad7711a717e708f440c22",
          "md5": "84743d0e7c5795e216c660218199d53f"
        }
      ]
    }
  ]
}
