{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "countries-info-domain",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-metadata-0.5.1.jar",
          "url": "countries-info-domain-0.5.1.jar",
          "size": 6330,
          "sha512": "3bb61acfb0b5dd45128a8c4ff32199307555f98a8b81772a9491cd8b1fbfd33374e1c6a7a763cb55c401e3566de82f43c6f0d3fba808f8eb28a48707dbe1bb41",
          "sha256": "e2c2b19b4635f83660c3a125a4b91dc4c877d30ed55d3d282978a1f0dad1b09d",
          "sha1": "79a1c29514dfd461e67c07ce70de34eac5e4d6ec",
          "md5": "d875e55c22ba6babee4b9dfb423a21fc"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../countries-info-domain-android/0.5.1/countries-info-domain-android-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-android",
        "version": "0.5.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../countries-info-domain-android/0.5.1/countries-info-domain-android-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-android",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../countries-info-domain-iosarm64/0.5.1/countries-info-domain-iosarm64-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../countries-info-domain-iosarm64/0.5.1/countries-info-domain-iosarm64-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../countries-info-domain-iossimulatorarm64/0.5.1/countries-info-domain-iossimulatorarm64-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../countries-info-domain-iossimulatorarm64/0.5.1/countries-info-domain-iossimulatorarm64-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../countries-info-domain-iosx64/0.5.1/countries-info-domain-iosx64-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-iosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../countries-info-domain-iosx64/0.5.1/countries-info-domain-iosx64-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-iosx64",
        "version": "0.5.1"
      }
    }
  ]
}
