{
  "formatVersion": "1.1",
  "component": {
    "url": "../../search-domain/0.8.0/search-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "search-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-iosArm64Main-0.8.0.klib",
          "url": "search-domain-iosarm64-0.8.0.klib",
          "size": 56529,
          "sha512": "ec000b87a22b09d01e1e19645a238b61925086e6da7111b2c60e8c1c232f80d01e9e5911087e8fd3459e30ecb8d38ca591b8083712391a19c707773dad11bd8a",
          "sha256": "315f1ef5a46132c8b1742acf845ea96d39f388e56baba411c616a2f6b0149316",
          "sha1": "f0ed8a6c6073b2d2ee7a9a496681496d4694ee5a",
          "md5": "e6099598bc7c8803a78994f3614daae7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-iosarm64-0.8.0-metadata.jar",
          "url": "search-domain-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "ece9dd87ca1aaf3bf67af35939572c63635ed68b3dd67a1ccde2379c617ba3a67ee431635df348671e7982ab639c9ef0275e8e7f1e29c5ba07452a5a5ca531df",
          "sha256": "9f0400620a772ddd43cdcb915451ec4562b25ec206ea16ef0660cd0a9b761d42",
          "sha1": "b6d5f57af3a94118371a0284c6fa793511957559",
          "md5": "1d6c6eb1079ff43828cc856e8f0960c0"
        }
      ]
    }
  ]
}
