{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api-config-environment/0.9.0/sdk-api-config-environment-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api-config-environment",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-environment-iosSimulatorArm64Main-0.9.0.klib",
          "url": "sdk-api-config-environment-iossimulatorarm64-0.9.0.klib",
          "size": 6786,
          "sha512": "be2fd76db6add2e0a62a56388ed5466d35dac080977eef6ff91ed76a3d3c2f8968ebd4bfb8b3bdae9adb403a016d2de4a9521279e9fbaaad95b1f9f31a38d6d2",
          "sha256": "823a1ed60541deb5ac74b52e382e193db6121ee1a5369759fa1bc7b2e80eb198",
          "sha1": "4317c38ee8e80995cf88cfc21eb0f195a0cf08fd",
          "md5": "05328a11d66f3475d99794671e175035"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-environment-iossimulatorarm64-0.9.0-metadata.jar",
          "url": "sdk-api-config-environment-iossimulatorarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "4caf07e0c6af54c8b8b86c839cd32265483baf38a7f8be7cb2e776827775e183c1272c0c2d9fc3376a1ceab978e6425c8d016b273b7510bcdc3d0ae1d7eea017",
          "sha256": "7f3621a5a5a403e5db1f6d65b6bcadba9aff55d3feb077208658bc276e006374",
          "sha1": "104b7de40e378c032d45618d983af17e470228c9",
          "md5": "6022ddc4068097647d5e5fe5dbbc8efa"
        }
      ]
    }
  ]
}
