{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-usecase/0.7.1/user-profile-usecase-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-usecase",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-iosArm64Main-0.7.1.klib",
          "url": "user-profile-usecase-iosarm64-0.7.1.klib",
          "size": 5013,
          "sha512": "eb6bc384eb7d88d3cec52103f673eecbf0c9eb79a1eec9077ed419043e068d2e411bd9d142c2aed96b7d4724d96cccf358b47c12f6dc41e6cebc8d68ef2b0504",
          "sha256": "5868336b8e7f540e94de30ead8fd98d45da722a091f1349462ed76da327a3ce5",
          "sha1": "93635405ea166393ad901f938a659573a1656191",
          "md5": "b30a7d9f99d4c18bd50bbf15308643bf"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-iosarm64-0.7.1-metadata.jar",
          "url": "user-profile-usecase-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "eb3d4eb27fe93a01cdd9641da47788dba8a8762f6336cbf1fe0bfc9aba25c6a5f1d457a0ee38155b21a34986ae33beb25e8ffd65e7dc07c2c746b53d8664ff95",
          "sha256": "eb7e08432ff56cbcd9c9780eaed045aca1cfad102f4d3f93b7b339c00dcf3b70",
          "sha1": "367d35319c6fbe9342426fc8b20088cd66a55c0b",
          "md5": "e5418b1a48175b6dffc03d2761c5e296"
        }
      ]
    }
  ]
}
