{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api-config/0.7.0/sdk-api-config-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api-config",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config-environment",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-iosX64Main-0.7.0.klib",
          "url": "sdk-api-config-iosx64-0.7.0.klib",
          "size": 39033,
          "sha512": "9901237ea80d28562b957ff66c879951266024b7a1db5524cf736fc578afc68b26d668842060850347fc11f24032f8813d3517179c48fb88d49581ac9bd34e46",
          "sha256": "edeb9fc31b0e0895301f0f1e55471610ba93b477cfda11d5fc3ecd3cbceb534e",
          "sha1": "0fb54cf5f11ce8a524d362eae81c897a7a9cba26",
          "md5": "2c9f62ac22aac9aa3a41c4d7359c0444"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config-environment",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-iosx64-0.7.0-metadata.jar",
          "url": "sdk-api-config-iosx64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "ca49bbb06deae571fe3f3bb357d42110d0319b5f4573f066d05cceee15974421f8e9333390e6f6c88ab28bbd0b4afc7e06f428479331e0607a7d0d6d121534ae",
          "sha256": "adca7e864f6039d90faa35bafdf406c122997b17209244bfd1fc5f8f6d7d4922",
          "sha1": "8e8678f00ba63f4e7bdbb23b5415ee7493d37cf5",
          "md5": "6c88c33dc3524d5773f828d76d51a794"
        }
      ]
    }
  ]
}
