{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-location-domain/0.7.0/user-location-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "user-location-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-domain-iosSimulatorArm64Main-0.7.0.klib",
          "url": "user-location-domain-iossimulatorarm64-0.7.0.klib",
          "size": 13693,
          "sha512": "a9e137fd501345e9f35d74ccd34e26f0c1fbd3f195ef366934b2e44ed14b4a558a75e815bdd61d044c32103cba7cbedf6fab2e1aa88a58b228fe2d476516db4e",
          "sha256": "9c33ead2fe6d5d6e899b93f86a24c33978faecdc7772ced7e5717c1c4ec75c88",
          "sha1": "dd9700781355c62be734747b88d8ae33d582d8c8",
          "md5": "bd99611c5724336d5d895669ca579ff7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "user-location-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "fe2b4f57a3af9cc98dc2b664588cb12cbd8d9689b91983b8c948a07cda441a5f10c4fc3256c3e03906b3a9a4fbb380196cfd168deeb152102f2c121b57c3e712",
          "sha256": "5eb6e21de5b4e6e2d7842164bfc76e4bcfbc63f75b405488044e4fd76ad7e677",
          "sha1": "b04eeae96ee865aa590294340e058d3385dcaf12",
          "md5": "62e246efd9c3d81c5ccfa49f9072cf39"
        }
      ]
    }
  ]
}
