{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-location-usecase/0.9.0/user-location-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "user-location-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-location-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-location-usecase-iosArm64Main-0.9.0.klib",
          "url": "user-location-usecase-iosarm64-0.9.0.klib",
          "size": 4801,
          "sha512": "fdaee4daa5978d5edfa857c90309bb7f41e6b5a87444ccdb0a2e7ee013bffdaa7d7c3d3de30e39d7a507d0efaae3390a7f396d333469be91ddb7c04805c814df",
          "sha256": "c8fb4d719bab020edfbdd9ae9582cb2e97d6ba1804a8007183083e1b4e3d59f5",
          "sha1": "d765c060c5c9bd6f8b312688e52ce3c6d23ef8a4",
          "md5": "17bf6bf327ee017974fc6421639f4339"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-location-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-location-usecase-iosarm64-0.9.0-metadata.jar",
          "url": "user-location-usecase-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "1988848d809aaa0f9f879947c07bef3cb81d7a90a1828f46767bc12100dcd4000d9e5e5bbf61f147347d19bb62ded72d9c1649fc2dacdc753cf1f34b2d209f07",
          "sha256": "09af09f373d942a81ac4a3656224f020edfb525f083ccb7e42141cb098cdf1b9",
          "sha1": "23b81d43d284ec2156852cf21c92475252ad8dc7",
          "md5": "37232abc3d8cd3f40b9bc7f6dfba6460"
        }
      ]
    }
  ]
}
