{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservation-details-usecase/0.8.0/reservation-details-usecase-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "reservation-details-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservation-details-usecase-iosArm64Main-0.8.0.klib",
          "url": "reservation-details-usecase-iosarm64-0.8.0.klib",
          "size": 4951,
          "sha512": "78b2766d8b2b2bc899ae55fc8a6a511dfb9abf6c2f7cc1b555729fd7ed9b70ade82ace2c5c45b2949bf6d42233297741fe929962ae3d35b0b726ad93ba00cabb",
          "sha256": "375812d8998d526c6bcfa9a953e03c9670a2e1fbaa216702173bd90e6528827b",
          "sha1": "08b932e8d0879e3a29e70f8f90c3b824b9089f23",
          "md5": "63cbbe39c599c5aca909444e20c3389f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservation-details-usecase-iosarm64-0.8.0-metadata.jar",
          "url": "reservation-details-usecase-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "f8640c37a4a311ac8efc2433d948a6c6c6e6430ccd859fd331343c9d75d17812c86e7662679ed8803dc17dd39ae4a95f9a50ecd0d1988e7d8269f09391260206",
          "sha256": "6ac94fff841bd696e7b9c6b346ea9d6b4165e308962c1fd47f48139277689d01",
          "sha1": "1471a34e09c07e1fa2589cdd580afdbd6be25ed3",
          "md5": "923541f90ef579c7d73e7028ed2d26d0"
        }
      ]
    }
  ]
}
