{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coupons-usecase/0.8.0/coupons-usecase-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "coupons-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-iosArm64Main-0.8.0.klib",
          "url": "coupons-usecase-iosarm64-0.8.0.klib",
          "size": 4746,
          "sha512": "d74186e439b59092dc508f3797d2b1b51c3bd057fcf94f57f0ebc90371d946344f5d5b179c3eafa4e281682642ce43c41bc8fdd8e4bf37f3404e40363658034d",
          "sha256": "0ff6c58489094cdd907d07e1f75259e8c5c379d5fa5b4146a6393bdd0bc0681a",
          "sha1": "b8172fe0547a7fdb06689cd316adf3017ead4520",
          "md5": "6f49c9cd8c1a6797c8e71896b78c4974"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-iosarm64-0.8.0-metadata.jar",
          "url": "coupons-usecase-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "e76aba302d9d17e554b85b85243b883f26fe12d86cbcfee9d5a595e36d21d26c3a96f6792ab6862e7db9e0d369b891e2b9e545c34ae5e016b9af747cc26bab7e",
          "sha256": "3b49b4e00c23eeed97584737150144791cc50ed8e7c05f9a404bf086fbc156df",
          "sha1": "2c12a3dd3ad089962be500ca70f3df7c2e9d2e20",
          "md5": "422445245953f375ce17671585101592"
        }
      ]
    }
  ]
}
