{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-domain/0.7.1/countries-info-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosSimulatorArm64Main-0.7.1.klib",
          "url": "countries-info-domain-iossimulatorarm64-0.7.1.klib",
          "size": 15341,
          "sha512": "1d8a90a9fe9f941f53f8e288a78745b1a6c5e61d0e96a4a5e3f54456849e053ecda325d596382b780bf7d5c8c885401a56653bc32abcc3b636c16d83f1d332f8",
          "sha256": "3824950e47067a8f68ca7acc156b508bb1423b106d33c61d18a14520e4802f86",
          "sha1": "686d1d248c2b2e8308e9c1e5358b46611155a4a7",
          "md5": "ba238b4b2a157724cffa995d66c2b9c0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "countries-info-domain-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "bb3892d5c8f1a6236d82f17fa4dae2e042215394cfe1c45a0e0c5ca15d692547ee7c3afc2d1599eb2654503b048325f7e9aee2cf3e6316633ac710c8da014bb2",
          "sha256": "ded1e81d1ebee22429a52543f7886d3193a3eb5280b624be844159c3794aa97a",
          "sha1": "159e9affcd034dd134dee4212e66fea09b6d2b15",
          "md5": "cea67134eb46faadd10cc186e6be4b97"
        }
      ]
    }
  ]
}
