{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "local-storage-data",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-metadata-0.7.1.jar",
          "url": "local-storage-data-0.7.1.jar",
          "size": 3563,
          "sha512": "7c89bc5a80972e57a85d21233a95a6e34ee9731cd7a47a0470289eb3ca467b32f445c4d3c519ea5920efad2ba815ae4ef25e10930f819c26b48e7569150b60e7",
          "sha256": "ffe5cb144dd2b2e1ad14fea36451a5430c36fd42ca7c25fba30d171e1be55136",
          "sha1": "e6f9156f6182c6253a41e1939661fd9286a48273",
          "md5": "5a2bffcf10e269d1d5e045a1ad025b04"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../local-storage-data-android/0.7.1/local-storage-data-android-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "local-storage-data-android",
        "version": "0.7.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../local-storage-data-android/0.7.1/local-storage-data-android-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "local-storage-data-android",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../local-storage-data-iosarm64/0.7.1/local-storage-data-iosarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "local-storage-data-iosarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../local-storage-data-iosarm64/0.7.1/local-storage-data-iosarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "local-storage-data-iosarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../local-storage-data-iossimulatorarm64/0.7.1/local-storage-data-iossimulatorarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "local-storage-data-iossimulatorarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../local-storage-data-iossimulatorarm64/0.7.1/local-storage-data-iossimulatorarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "local-storage-data-iossimulatorarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../local-storage-data-iosx64/0.7.1/local-storage-data-iosx64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "local-storage-data-iosx64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../local-storage-data-iosx64/0.7.1/local-storage-data-iosx64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "local-storage-data-iosx64",
        "version": "0.7.1"
      }
    }
  ]
}
