{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservation-details-domain/0.7.0/reservation-details-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "reservation-details-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-domain-iosArm64Main-0.7.0.klib",
          "url": "reservation-details-domain-iosarm64-0.7.0.klib",
          "size": 52411,
          "sha512": "3d3f7ce76908eb48fd7e29361a707ad47969eb25560283f3cd49a2e03d6b27fb23c64e87b9905c3d52dab5064a2a41e30c05184a8dbf020e64e65c7f1e7acfc4",
          "sha256": "d755194d30018cd6c2e35d08d2fc69f7b5651a5975a9d7fa3c7b2f7edeeaed1c",
          "sha1": "c8749b2d44d91a6607f980249965b8794591d1a4",
          "md5": "b266af62f55c6ad24f0f5c91b6eaa8ab"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-domain-iosarm64-0.7.0-metadata.jar",
          "url": "reservation-details-domain-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "9e8fb708bc3d6377924cf9bfd77277da2fe427e7bc602ee5d2bc339b90196a4fc677e04cc99160256f8ee332bde4f381ca82008c61b6483401f06cb3e488c3e9",
          "sha256": "0708bc15565e9f3beceeafad252553caf35ac5cd966ac1d9db4a69cf4d13ddeb",
          "sha1": "27ed7c0f34ccb5cc547e25053d055ad6e5e18e55",
          "md5": "ef14598ff18a4e825ab72f537b882a89"
        }
      ]
    }
  ]
}
