{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-domain/0.9.1/countries-info-domain-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-domain",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosX64Main-0.9.1.klib",
          "url": "countries-info-domain-iosx64-0.9.1.klib",
          "size": 15124,
          "sha512": "cc181c3d7fbb71dfc337a943c8095753c4a356bbee4a9d94a8caac3d31b3b1bc3671e586d5e35a9eb14f6b44eac267dc530ef651d6971902b832808f1f8165f3",
          "sha256": "5c155f8d910441323f5f2b8c2fb81e4cf91b296f0b2c7eafbb693dcc2394e9cd",
          "sha1": "9747e47cf267564b6ddb50dc8ee9c475b7c2279b",
          "md5": "ec9f33acd80534944f514d6079e789f6"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosx64-0.9.1-metadata.jar",
          "url": "countries-info-domain-iosx64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "8fd1c7a054b54042129f2ffb690b95aa12713c3806ecccf534f53529ddffd91e3b699e9af1863306f10abcaf56c6267cfd1d23e388e7e0652a56e45978163095",
          "sha256": "705be580487b71e1ddc0fafc23c551e1b6e5029b672dd1a223b35b4e5c1e94eb",
          "sha1": "9aba02c79b00dbb9a3038cd136184332f4531101",
          "md5": "1ae62d2be00f3d6a5d5723805d4a8fd2"
        }
      ]
    }
  ]
}
