{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-domain/0.9.0/amenities-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "amenities-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iosX64Main-0.9.0.klib",
          "url": "amenities-domain-iosx64-0.9.0.klib",
          "size": 12703,
          "sha512": "4e1c7d7aaeff024870e33c1c6be01ff6eeef60e00ef842a4e678945b07db384699fa170d25a27ef05164a51829050bcce7e2e2e76d8b03e7ef1acd1e4f3f65c9",
          "sha256": "db41e222cc9681e7d145fefe2846b3b8082ed70b125cc8cd48a4dc6f5fb151bd",
          "sha1": "57c68c080663031971385d916d2d1f24342d1b40",
          "md5": "22056c8db1c593a7766df03657cb406c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iosx64-0.9.0-metadata.jar",
          "url": "amenities-domain-iosx64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "1fc87f57c67f1138b2ecad437f37212e0ec93f3bfb6f8dee64f2d153c001a16a2f5379985b62943ab24223bc4b229504a6e826cf3c0f78877d8de388552d97b4",
          "sha256": "3f5b2e084d5692ec70468a76ca587911722131bd29e777ca383c2c9b5b76e63c",
          "sha1": "e65535c063e78ee243984dc2d10541f03cc8aa68",
          "md5": "3926f5ad9d7b4069617dbd71d3b566bf"
        }
      ]
    }
  ]
}
