{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "countries-info-domain",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-metadata-0.1.1.jar",
          "url": "countries-info-domain-0.1.1.jar",
          "size": 6333,
          "sha512": "2656b4902910a80371f0b1b8797c07fb18a30901c60a4790716b869980e976f7d1fef9023512b66549aee2dd8c89d8b71bb8d96c91da083b5ca9a8c83ee75642",
          "sha256": "32d8bb1d23b4161fb13a297ec8309a4d5a52c2799155c0be592b158119581ce5",
          "sha1": "45e28a1131a9d29b44bd05c2eea74bcb44ed3c4c",
          "md5": "dbd629874e68c1c35fdd908c77884446"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../countries-info-domain-android/0.1.1/countries-info-domain-android-0.1.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-android",
        "version": "0.1.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../countries-info-domain-android/0.1.1/countries-info-domain-android-0.1.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-android",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../countries-info-domain-iosarm64/0.1.1/countries-info-domain-iosarm64-0.1.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-iosarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../countries-info-domain-iosarm64/0.1.1/countries-info-domain-iosarm64-0.1.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-iosarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../countries-info-domain-iossimulatorarm64/0.1.1/countries-info-domain-iossimulatorarm64-0.1.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-iossimulatorarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../countries-info-domain-iossimulatorarm64/0.1.1/countries-info-domain-iossimulatorarm64-0.1.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-iossimulatorarm64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../countries-info-domain-iosx64/0.1.1/countries-info-domain-iosx64-0.1.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-iosx64",
        "version": "0.1.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../countries-info-domain-iosx64/0.1.1/countries-info-domain-iosx64-0.1.1.module",
        "group": "com.mozio.mobile",
        "module": "countries-info-domain-iosx64",
        "version": "0.1.1"
      }
    }
  ]
}
