{
  "formatVersion": "1.1",
  "component": {
    "url": "../../search-usecase/0.9.0/search-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "search-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "search-usecase-iosX64Main-0.9.0.klib",
          "url": "search-usecase-iosx64-0.9.0.klib",
          "size": 4728,
          "sha512": "b3bcc66e8b5135101664f780d3797bc8fc74dc3c84c79b506cee8f1a26d9277cbedf012c9e0ead23ad415e2f82f3dcd4020e63c6995270b2ca4cd2aaeb39d4f2",
          "sha256": "0e2faa8c77eb3bf01b049fa251f25f46a10f8236aa4b1aa2ccc5530b132b6a0f",
          "sha1": "3fdfce8b550ac640eab354a038c9e32f39c4161f",
          "md5": "53c669271fe6aa78c63f797cbc2b8229"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "search-usecase-iosx64-0.9.0-metadata.jar",
          "url": "search-usecase-iosx64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "1d8033f83946382dd501757506d22e1b6c5dae6c48077d859ef11bc08ef8742fc2b4f68bcd5f9be4e45a7149687c8ba46f351b0b7dc6541d275ff5fa49f76bb8",
          "sha256": "0a16bbe9d63574663fe85c924e207bcf58f485a08cb06cf8eaf3159e80a2e68a",
          "sha1": "c942307fa70b99b4b5c9659314aa31042a74ed1f",
          "md5": "952463ec2ad309d709f2bbac489abdd9"
        }
      ]
    }
  ]
}
