{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-usecase/0.1.2/user-profile-usecase-0.1.2.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-usecase",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-release.aar",
          "url": "user-profile-usecase-android-0.1.2.aar",
          "size": 2266,
          "sha512": "36f1a37056310fca9ecc636a9c491214b5327b88123e3a1d58ae85f0866b77bc9ec0a09e09a541614a8eca320e25b701267e30faac5abc994ec93de206bbbee4",
          "sha256": "d04935c8e2e1f2c2bbd2de1b1e6f95e8eb3ca0ccb75bebbdae6b8f1fbed0358f",
          "sha1": "4dce4785fb9cdc1e1a471c02538b44b106e526e7",
          "md5": "35b78a808663d6dc1f5620241729bbc4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-release.aar",
          "url": "user-profile-usecase-android-0.1.2.aar",
          "size": 2266,
          "sha512": "36f1a37056310fca9ecc636a9c491214b5327b88123e3a1d58ae85f0866b77bc9ec0a09e09a541614a8eca320e25b701267e30faac5abc994ec93de206bbbee4",
          "sha256": "d04935c8e2e1f2c2bbd2de1b1e6f95e8eb3ca0ccb75bebbdae6b8f1fbed0358f",
          "sha1": "4dce4785fb9cdc1e1a471c02538b44b106e526e7",
          "md5": "35b78a808663d6dc1f5620241729bbc4"
        }
      ]
    }
  ]
}
