{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservations-domain/0.7.1/reservations-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "reservations-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-domain-iosSimulatorArm64Main-0.7.1.klib",
          "url": "reservations-domain-iossimulatorarm64-0.7.1.klib",
          "size": 23357,
          "sha512": "cdd33b6a20dfcc4d5aa6eafab6f9891cee32d505a6c3185a16aa39435975b84397ea73144a6ed524fc206217721094dbe876506bad41fe27ce0accf44773d894",
          "sha256": "99feebed08317c8df8dacdc81b02d2a0601d56915dc776a73dafe55ddb3a9720",
          "sha1": "51abbdbda9e010e427c84814ea2039c147fb3209",
          "md5": "67797304866b0f0a5a3c16cfe9dd804f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-domain-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "reservations-domain-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "18dc949410dda845322ec972274c78ab949e78587e6361c98f4ced8759ed8282048784bc6c5612fcf3a6dfc595a5a6a2333e939b68bdc3fc1a70d62ce70599d5",
          "sha256": "ff9b22163e5911873f68c7716a98b98baa21d4f01eeaaf8315c72cd136f572cb",
          "sha1": "a0d7886f942a10f549481cd4df5047f2723d7ae6",
          "md5": "8df94ffabfe1f51679ce6be1cb182eb7"
        }
      ]
    }
  ]
}
