{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mobile-sdk-bff/0.9.0/mobile-sdk-bff-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "mobile-sdk-bff",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-iosSimulatorArm64Main-0.9.0.klib",
          "url": "mobile-sdk-bff-iossimulatorarm64-0.9.0.klib",
          "size": 133017,
          "sha512": "7c2050b674e968132760a686202e38f869d18095df766f75b80bd58550f4c222b2a08c7916535547e0446288367bc05eefc6bb8908f3422206b7ee4dc5fb4d4c",
          "sha256": "7a7ab90a5a922ab1368c7145fd526c8b76e8605acea8530060cdada3a3f5fc3b",
          "sha1": "38a11480868a00331d94556fe6f01bd076ae4645",
          "md5": "f85ab52c4956a9c50edf6bd2cdcd4f06"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-iossimulatorarm64-0.9.0-metadata.jar",
          "url": "mobile-sdk-bff-iossimulatorarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "4bdcf5bbf053e79382851e2e8119188b05f8c2ae28c23f6c17d5a0e62404d2b7dc55a36d171a8a9c5f016b534f41146ba16470943f2bf4df2556ccb7b80e0490",
          "sha256": "83ee38f5adc1307200837ae31861d34f360768ec33a3da1d72aefe848959dc26",
          "sha1": "3c20938704648c211cf6bd715d77bece688f5c0a",
          "md5": "96b70022afcbc9a691db9587335ac0af"
        }
      ]
    }
  ]
}
