{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-domain/0.9.0/amenities-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "amenities-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iosArm64Main-0.9.0.klib",
          "url": "amenities-domain-iosarm64-0.9.0.klib",
          "size": 12716,
          "sha512": "8fd5da349372f07230738a616cbe16d40e80c2c5f9b9b92cb9fc17eceb05e0f95f5e6a399f5c22b34520bd1008b101fea99fb8b566463a9c1cb5e71b133fb532",
          "sha256": "e477bf3458c22544e255e0eaccc34b1c91b8d1cf81a6e7b15b7ffb33cfe32981",
          "sha1": "58a1bd67fb23750e18732e8c5a735670d26f8fb2",
          "md5": "ad3fbc3bfad90fb35d857a0d51c3834b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iosarm64-0.9.0-metadata.jar",
          "url": "amenities-domain-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "1fc87f57c67f1138b2ecad437f37212e0ec93f3bfb6f8dee64f2d153c001a16a2f5379985b62943ab24223bc4b229504a6e826cf3c0f78877d8de388552d97b4",
          "sha256": "3f5b2e084d5692ec70468a76ca587911722131bd29e777ca383c2c9b5b76e63c",
          "sha1": "e65535c063e78ee243984dc2d10541f03cc8aa68",
          "md5": "3926f5ad9d7b4069617dbd71d3b566bf"
        }
      ]
    }
  ]
}
