{
  "formatVersion": "1.1",
  "component": {
    "url": "../../locations-domain/0.9.1/locations-domain-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "locations-domain",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosSimulatorArm64Main-0.9.1.klib",
          "url": "locations-domain-iossimulatorarm64-0.9.1.klib",
          "size": 33715,
          "sha512": "46a14e62b6d869019ca5ac39aa7a26d77753177c6c5eede65f653dd582fc997413fdd523a8932be33731cf9da9ac841fd6aa80d8bf408c762d74768bb0a7bdd6",
          "sha256": "170b891eefbb56fc451483a97067055f27c177b2c21bf09f6787d30c421bfa1d",
          "sha1": "31e898c5859c4ade06ddc8e457b791cdf743fd15",
          "md5": "57b2091584241ef9d40768c67bcccf0c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "locations-domain-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "2fe1ad84e80bba297d6daea34cd8b4f9d24f89f3bd5624bc7ba9be67e49a92cc971e9fb7818b97cec10fd27c1c5e081a44c1aaecc2b7bd3dd26d8691ec3444c8",
          "sha256": "3969993ba9494afd8658ae0cb35d0c5ccb88d4e69b9dcd083bac2f3372bb40e8",
          "sha1": "574909b8598d9cbea0e372b285f414be0291735f",
          "md5": "4191e3e39e45e9289f17f9d8a43f5cf5"
        }
      ]
    }
  ]
}
