{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-domain/0.7.1/pricing-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "pricing-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosSimulatorArm64Main-0.7.1.klib",
          "url": "pricing-domain-iossimulatorarm64-0.7.1.klib",
          "size": 23509,
          "sha512": "2c00560743f332e6199453bd477b50f6cdfefff94e9368476e9ccbda60cb616091f5ecb5949d9095c4dd3c47c50c621db4ec35bffe8c2824fd842c259d001474",
          "sha256": "01b50f206e4699be43bd546ca2bf83c731bbed6a01fb859fa1ed646a10605357",
          "sha1": "d081c5d2ce0ed198994dee5a04534206e05f52e8",
          "md5": "e577836e13a2e084755abf0b4e72861c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "pricing-domain-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "9bb4a018121aff619484a187b9ca537959ea49a75327c2b31ecbcb9ec4092048c5c318b7f1a87ffe8e357194d7134f62575b1cd6beb7766d5433fcebfd052162",
          "sha256": "8c132f7f6b9708e11fcb6d5910fbfcc3618a87f4edb90d439353ddea2c49f5bc",
          "sha1": "030bd3e4573085856f77cd3abcc6fd833d34d8c6",
          "md5": "c9d4a19eb54d21d4b76648b2174b7900"
        }
      ]
    }
  ]
}
