{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-usecase/0.8.0/authentication-usecase-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "authentication-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iosSimulatorArm64Main-0.8.0.klib",
          "url": "authentication-usecase-iossimulatorarm64-0.8.0.klib",
          "size": 4923,
          "sha512": "5b1ebef0ba5b5e52a83423d605e01d609c33e7d20a5c52d70d1325456b92b71b7f104311652f6ef84018165b7cc9879bc0aab8be205f8798a8e7473a5aa515e6",
          "sha256": "ce84202e532d596cf3e098df28ddc7ce79a270057a766ef26d1c209b0359601b",
          "sha1": "93feb9357505cbf20e124f64bdc53cfbef37bd5b",
          "md5": "87db07211414af366f30642ef8774bee"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "authentication-usecase-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "bcb42e3f4b9351a5f0071991202729661b63ce5579606f6beb95177b4461d1b6848adc6928cc7027d75dea7a361e28a993d2af5c7c6a6da808ba7c658feb521f",
          "sha256": "d73e6f4ed6ccb0679a69c5aa15308b5aa1172465280e0012f070b4ecc5cfb22a",
          "sha1": "91d11f5180599a5610d7bd80e8fc9ad8070a93f5",
          "md5": "068a3aca7740529b05a9930bf3dbf1ea"
        }
      ]
    }
  ]
}
