{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-usecase/0.9.0/authentication-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "authentication-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iosArm64Main-0.9.0.klib",
          "url": "authentication-usecase-iosarm64-0.9.0.klib",
          "size": 4857,
          "sha512": "2fa4a4c71f525f300b3b0ecc2e9924496e6759c83efaf5342e1f90c38309ca9e42b082af6d91e56232841377a39688c9d3e9bda9b786bdc047c718b02f2ee4f5",
          "sha256": "29b9e8c719deaa7c032d43d6f532174d0d5aa68ae912963ba52d03c9cd1debb6",
          "sha1": "76f5362b2c7234445e92a54c2315cf1d4a211936",
          "md5": "0ce96fdb4d658120fbc0e22ef4559322"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iosarm64-0.9.0-metadata.jar",
          "url": "authentication-usecase-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "c9d43229061ebf2effe38e793fdf5e2d9375bcb948a3e731250d418ce974aaf559a644c98085733e85f9b2ec8c983fc0c6f1b04dd5f2699694801e9a6f1c47fd",
          "sha256": "d19249ed5844c6a5e2132ee716d306e9fd7f69ae286c3b6350e40e0d43e5cc9d",
          "sha1": "ecf3c82092a610bf17c4728291d6590b62b64e5e",
          "md5": "b53f7a5e698e3b4810e53a9c794f2629"
        }
      ]
    }
  ]
}
