{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stripe-payments-usecase/0.7.0/stripe-payments-usecase-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "stripe-payments-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-iosSimulatorArm64Main-0.7.0.klib",
          "url": "stripe-payments-usecase-iossimulatorarm64-0.7.0.klib",
          "size": 5060,
          "sha512": "85753820fcbe8912d886578804dc981f2320428076df885370ad9a9dd67b78335eec5aa7f0f652e686583718f3fab77c7652e2060b2c899b2a73eb8e6f518258",
          "sha256": "ade7a9c5417e99349a4113e101bdc274d7f958251df66051201fcfae1a31842f",
          "sha1": "9a540eaadd4147e22e9db44fd0cafe49c0409fbb",
          "md5": "2c2d4bd8a45617bacea8a457e5e48297"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "stripe-payments-usecase-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "c10a877a87534cbec5c6086096c3c05d32447a61985d7d1f05cc8070266fc2c0352d954d585009cd622b8aba69c4eeab278420100bafcf2372e1600b0cc1bece",
          "sha256": "ea278e85f9271524c5d53c692e44ee0806b656ef7733bd0eaf1c1d85eb0e987b",
          "sha1": "b4672e14c8a6c298238a0565df71d5c971d93633",
          "md5": "0e2b57433f5d75d799ff77504f4d2f6b"
        }
      ]
    }
  ]
}
