{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coupons-domain/0.9.1/coupons-domain-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "coupons-domain",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-domain-iosSimulatorArm64Main-0.9.1.klib",
          "url": "coupons-domain-iossimulatorarm64-0.9.1.klib",
          "size": 23865,
          "sha512": "ad21335aa7cb966c24fea3c13a1a4ec730c1e82c2c78c2698d001cc08622dc0a55954c4fa0b28490e7a2a149b4fdf795647d09d65147a01e76535cda9dad823e",
          "sha256": "16ca764607a83af8ff3b50e640cc47cb241d3c6f8b875cba69e3cd1e9a847ed5",
          "sha1": "6257e01c8dee70886cb8ac4c03006dc39597dfa2",
          "md5": "66c43b8a02dcce5f8840411b298b69c1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-domain-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "coupons-domain-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "2dc3a4aaf27754f07638d8f40ebe136101d369c67262ea50c57e380e00aa086633a6db3f176f429f3521deb4bb68288f3c4136501659216cc88da5ed4ad5d3c4",
          "sha256": "463fa56528874b5ac98ee041e50d7dc05f30307197a43861123937c2232a8304",
          "sha1": "600a43d8b159d7ab8d20501fc65a9c1d2323bdb7",
          "md5": "9870b3335c62e44aca7c142cd348157e"
        }
      ]
    }
  ]
}
