{
  "formatVersion": "1.1",
  "component": {
    "url": "../../locations-domain/0.7.1/locations-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "locations-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosArm64Main-0.7.1.klib",
          "url": "locations-domain-iosarm64-0.7.1.klib",
          "size": 34195,
          "sha512": "02b15de9a8d7fb8f5c9773f8de17ae1d2fab772e3ebf9fca2f0170e4c13a9658cbf1eb9bbe0cdac37608ed1ecac1bcf01f1631deb7f23da6882c2fc292b8ac22",
          "sha256": "a10fa74fef645593eeb600c9af4265f1b0b750e803ba154a9b92afcef59cf797",
          "sha1": "d2ad6235eb7a9b4269b434d3a9358b43ac76737f",
          "md5": "2e817496c46a8d022cfd76cfc00f0bf7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosarm64-0.7.1-metadata.jar",
          "url": "locations-domain-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "77b4b11150f2f4839e0becfedccf772d71e7fa5e923a1d41012ca62a5353a4d0d984dbe6ba186a7b72b17f6b0ff0280b493b9be5163c63fca591e3251243d1f0",
          "sha256": "45efbde189b93f4b12069e19a7099551f612e41f2a5d3ee79e44b7f0ebd1d908",
          "sha1": "f87c244183eca71d8facd5032ed166aa1c6483e3",
          "md5": "df2d28be52cd9cb507f6c2920dcdb83c"
        }
      ]
    }
  ]
}
