{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "user-profile-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-profile-usecase-metadata-0.8.0.jar",
          "url": "user-profile-usecase-0.8.0.jar",
          "size": 2517,
          "sha512": "1dfe3844e8341147146aa3f4d5f2faeee2663dcfd830cb47109a816334bc78ea05cc803b9df3c1fbaaa5e501aa62a8bcc3e36c035f993bb66b6018539d66af63",
          "sha256": "bce6755dc579375ce871dcaa0d275ebacdba555b959cca7999fd0dc81997929f",
          "sha1": "2f83362ce83a3ae364ce92598f40cf614a9117be",
          "md5": "21fd0e3d6f5023170a34479caad96870"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../user-profile-usecase-android/0.8.0/user-profile-usecase-android-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../user-profile-usecase-android/0.8.0/user-profile-usecase-android-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-profile-usecase-iosarm64/0.8.0/user-profile-usecase-iosarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-profile-usecase-iosarm64/0.8.0/user-profile-usecase-iosarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-profile-usecase-iossimulatorarm64/0.8.0/user-profile-usecase-iossimulatorarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-profile-usecase-iossimulatorarm64/0.8.0/user-profile-usecase-iossimulatorarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-profile-usecase-iosx64/0.8.0/user-profile-usecase-iosx64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-profile-usecase-iosx64/0.8.0/user-profile-usecase-iosx64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "user-profile-usecase-iosx64",
        "version": "0.8.0"
      }
    }
  ]
}
