{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-domain/0.8.0/amenities-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "amenities-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iosX64Main-0.8.0.klib",
          "url": "amenities-domain-iosx64-0.8.0.klib",
          "size": 12703,
          "sha512": "4e1c7d7aaeff024870e33c1c6be01ff6eeef60e00ef842a4e678945b07db384699fa170d25a27ef05164a51829050bcce7e2e2e76d8b03e7ef1acd1e4f3f65c9",
          "sha256": "db41e222cc9681e7d145fefe2846b3b8082ed70b125cc8cd48a4dc6f5fb151bd",
          "sha1": "57c68c080663031971385d916d2d1f24342d1b40",
          "md5": "22056c8db1c593a7766df03657cb406c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iosx64-0.8.0-metadata.jar",
          "url": "amenities-domain-iosx64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "20b2b3cd40fa625a2b7a4855cb8d1baaad0c2f504bc852348864b4b57f9280ac4a7054ad6725b4e83eeac9a5db890af4f0982794e6663f5fc0a37d9e1945cfaf",
          "sha256": "2fa05459a6117cdf7c798b408f45ff5868c780af36cccf9da7a2c87513260dbd",
          "sha1": "8150218fa0e0986646104f9847cab7921897851c",
          "md5": "e276248f2f02a5c4a430e3d5424c6c75"
        }
      ]
    }
  ]
}
