{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coupons-domain/0.7.0/coupons-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "coupons-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-domain-iosSimulatorArm64Main-0.7.0.klib",
          "url": "coupons-domain-iossimulatorarm64-0.7.0.klib",
          "size": 24192,
          "sha512": "ef44946972eb57f6c9a4d0e41259bd49955b995e3ea3c85289716a7661e58287257e54cc67d53844f3541e01cdf09c1440debb0d0ead6d5a0dfd4b3949214df3",
          "sha256": "b9a35a9d2d8df4850d5eb0de54560508ff546935d0805335c4cecff5fc7e4210",
          "sha1": "85b4ce54be456adedc8048135890fc8fb091d097",
          "md5": "037bb2bc1f98065ccf8b8f2638fa3852"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "coupons-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "8cb649c42853d33f44cbf400fd76317afa84fcbf4a3b76ef316bf622a7426bf172b47d622737e189adda7368ff42b636f1d32a18d51a25f73f297817f9dd5815",
          "sha256": "43bd39d607f4a43277457b9e9682207ae960f8836f1b470dbb8b7f71b682cd28",
          "sha1": "6f0be97d87cb2f1ad9c8a158ab8a7b247301afbc",
          "md5": "fa3e19bca16c999f4de350e0e22406d6"
        }
      ]
    }
  ]
}
