{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-usecase/0.9.0/amenities-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "amenities-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosArm64Main-0.9.0.klib",
          "url": "amenities-usecase-iosarm64-0.9.0.klib",
          "size": 4766,
          "sha512": "478798af66f8bd64d030f4be04eeb58a667941a2ce8cef1fae10d54fff9587d7db3062bd8c9aa491419d2f6d986be2b7d36de4d42bcbef2fb671bcf9431e4675",
          "sha256": "ffe9576dc7d56702b13a08654159b925e6fb3160c2dcde1f935bbcf7d13a81b5",
          "sha1": "7c94614c3f49811726f2e13641a525994d090c95",
          "md5": "f4df1f4ba050e33e0c6c1ea114189816"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosarm64-0.9.0-metadata.jar",
          "url": "amenities-usecase-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "5d9c75664c6a7039fa94d3a36d59f7a5bac6f09cc8a3d0d71eca1aedf33baeb9533d4b572cb8c6973d08da902c076da4917e929d68d37a0526c4ca79f3a5af25",
          "sha256": "bd1e4ca08b555c3c2016bb388729cb4c14a2fde217af3bb8dc4a165ad2a77089",
          "sha1": "a0f5e942a9e91faef3dee56229dc24df5c21c606",
          "md5": "7268842a90bcf901d73bc12d41fbdb49"
        }
      ]
    }
  ]
}
