{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile.android",
    "module": "sdk-ui",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "sdk-ui-config",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-0.2.0.aar",
          "url": "sdk-ui-0.2.0.aar",
          "size": 36198,
          "sha512": "f83fa98b2e9793ccb4e1b3c3ad8e7bb3ab7512d5ebb9dae012314ec27014e853f75ae14a6e7e97f682be1ea229d496c67bba7fd072be68d88c0746b35a4c5f2d",
          "sha256": "bd6b6413cf0a40c2a8b95b8c9f801cfdffdcc5ad47a7e783c46292d7d6a224f3",
          "sha1": "b9d0000c936462456412a09122b3a73439c718fb",
          "md5": "8d980ea7f4b5bee953b1acf955ac4fd1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile.android",
          "module": "core-ui",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "search-rides-ui",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "prebook-ui",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "prebook-bookingflow-ui",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "authentication-ui",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "myaccount-ui",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "main-ui",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "reservation-details-ui",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "com.stripe",
          "module": "stripe-android",
          "version": {
            "requires": "21.20.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "sdk-ui-config",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-0.2.0.aar",
          "url": "sdk-ui-0.2.0.aar",
          "size": 36198,
          "sha512": "f83fa98b2e9793ccb4e1b3c3ad8e7bb3ab7512d5ebb9dae012314ec27014e853f75ae14a6e7e97f682be1ea229d496c67bba7fd072be68d88c0746b35a4c5f2d",
          "sha256": "bd6b6413cf0a40c2a8b95b8c9f801cfdffdcc5ad47a7e783c46292d7d6a224f3",
          "sha1": "b9d0000c936462456412a09122b3a73439c718fb",
          "md5": "8d980ea7f4b5bee953b1acf955ac4fd1"
        }
      ]
    }
  ]
}
