{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "user-location-usecase",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-location-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-usecase-metadata-0.7.1.jar",
          "url": "user-location-usecase-0.7.1.jar",
          "size": 2505,
          "sha512": "f7ed2a01729a2d2f856a1a5e8823a966e3e37100ed393ce7451ac79de40933506b7539209ec5d84d45fe539ff8395a1b1023b5e04ce12e6973bcc628bc669f7b",
          "sha256": "4764d019cbf6893b543f05e3513d34ca226ac9ba5a00863d4d78ac9a30197c77",
          "sha1": "149c81642d5ae61e2c50013de4faf3d1e99c8601",
          "md5": "4f7ac39e024deffc5c7e01e11edd6ed4"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../user-location-usecase-android/0.7.1/user-location-usecase-android-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "user-location-usecase-android",
        "version": "0.7.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../user-location-usecase-android/0.7.1/user-location-usecase-android-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "user-location-usecase-android",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-location-usecase-iosarm64/0.7.1/user-location-usecase-iosarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "user-location-usecase-iosarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-location-usecase-iosarm64/0.7.1/user-location-usecase-iosarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "user-location-usecase-iosarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-location-usecase-iossimulatorarm64/0.7.1/user-location-usecase-iossimulatorarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "user-location-usecase-iossimulatorarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-location-usecase-iossimulatorarm64/0.7.1/user-location-usecase-iossimulatorarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "user-location-usecase-iossimulatorarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-location-usecase-iosx64/0.7.1/user-location-usecase-iosx64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "user-location-usecase-iosx64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../user-location-usecase-iosx64/0.7.1/user-location-usecase-iosx64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "user-location-usecase-iosx64",
        "version": "0.7.1"
      }
    }
  ]
}
