{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coupons-domain/0.9.1/coupons-domain-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "coupons-domain",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-domain-iosArm64Main-0.9.1.klib",
          "url": "coupons-domain-iosarm64-0.9.1.klib",
          "size": 23800,
          "sha512": "e27dc59b2fa411efbdf34e137288ffb258b57dc9c6e424aaf20f5c8302b352f94baf634a10b6cd8708b644c40cc3013932e746b382d5ff86a4f037571623b3f9",
          "sha256": "1c3873be46b7b41491822c9f4384055ab59cc26ea4b7b242e356fea94058c80a",
          "sha1": "8df72a3d1543f2b3bac6b18c9a3d7ab92d2d9aa4",
          "md5": "8f56b1c00ef305b1e5f846a4343dc413"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-domain-iosarm64-0.9.1-metadata.jar",
          "url": "coupons-domain-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "2dc3a4aaf27754f07638d8f40ebe136101d369c67262ea50c57e380e00aa086633a6db3f176f429f3521deb4bb68288f3c4136501659216cc88da5ed4ad5d3c4",
          "sha256": "463fa56528874b5ac98ee041e50d7dc05f30307197a43861123937c2232a8304",
          "sha1": "600a43d8b159d7ab8d20501fc65a9c1d2323bdb7",
          "md5": "9870b3335c62e44aca7c142cd348157e"
        }
      ]
    }
  ]
}
