{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservations-domain/0.7.0/reservations-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "reservations-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-domain-iosSimulatorArm64Main-0.7.0.klib",
          "url": "reservations-domain-iossimulatorarm64-0.7.0.klib",
          "size": 23357,
          "sha512": "cdd33b6a20dfcc4d5aa6eafab6f9891cee32d505a6c3185a16aa39435975b84397ea73144a6ed524fc206217721094dbe876506bad41fe27ce0accf44773d894",
          "sha256": "99feebed08317c8df8dacdc81b02d2a0601d56915dc776a73dafe55ddb3a9720",
          "sha1": "51abbdbda9e010e427c84814ea2039c147fb3209",
          "md5": "67797304866b0f0a5a3c16cfe9dd804f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "reservations-domain-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "cfe704422046898a1ba827fdc58dc6fe11bd50d48f2bb758e33c62869ee74e72f987ff6f3840192306b4dc178be6f6a381d74d838bbc016f4556cd647971bafd",
          "sha256": "0de34919e809625424fe755669169f9e8d4b3620c76911df0cd595343ab09742",
          "sha1": "32dea5c9cf1d5f88cda656f991091fe4d6611acd",
          "md5": "7055f2156a5536fd0059dd51b88ce056"
        }
      ]
    }
  ]
}
