{
  "formatVersion": "1.1",
  "component": {
    "url": "../../searched-locations-history-domain/0.9.1/searched-locations-history-domain-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "searched-locations-history-domain",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-domain-iosArm64Main-0.9.1.klib",
          "url": "searched-locations-history-domain-iosarm64-0.9.1.klib",
          "size": 31174,
          "sha512": "d0a7c45d2856d6e743beedf8a2930456f6b3646357034e4d6e6ca80c265c02518d48fe9365ea6012fbee65704c6875751923d5bf56eca6e2809d2abf9718b192",
          "sha256": "aae5f3187949af0369f83efb79128499c9b7445de3de3fac3eb93bf5d3cabddc",
          "sha1": "920ea9c891ce4f1c7ff8360255ab61c7e285c6c7",
          "md5": "68edee104a43ca2be3f66c666ff500f0"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-domain-iosarm64-0.9.1-metadata.jar",
          "url": "searched-locations-history-domain-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "85ef3ef2f39b928ecb7a74aa942641100559903e62edd4c622968a1d64c8c4158321a1ac642e2d5b4fc2390a4a4420849237ceca4c88024f2a440c780214e278",
          "sha256": "ba6c1675772ac89a597881cffb2621953c1c675df6aa80e0cd86831068bb9912",
          "sha1": "13dd4ed19bc1ba9434db168dd64dd5321be47686",
          "md5": "cf46299b5ab164eb263e8eb72e0e1fd8"
        }
      ]
    }
  ]
}
