{
  "formatVersion": "1.1",
  "component": {
    "url": "../../local-storage-data/0.7.0/local-storage-data-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "local-storage-data",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosSimulatorArm64Main-0.7.0.klib",
          "url": "local-storage-data-iossimulatorarm64-0.7.0.klib",
          "size": 8814,
          "sha512": "1ccd02881379965bd78cf2b3a63f122da90082c4d8a9c97dd120358c75f2b21e459327a9b3468f7ca5be66c710d78ff344cd5956a44a5240f856d95b89e69a4b",
          "sha256": "9d3a68f2cd9630f638f6e7082ea82fa4ea0b882f7e78d3feab72e375889f320a",
          "sha1": "643e3590a70188b62a02ce9fc1c210b1073f7393",
          "md5": "99d58ea7939ed6503179ce84deea4a65"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "local-storage-data-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 2476,
          "sha512": "8ff5cea28fa807bc1fbb352e90caefa1f8aac8aaf3b00e86570ae5ded76050f454a0608b238f278581471104d5b9ba3cac453b460ba2e6e750dd8debb59b2d8a",
          "sha256": "1888dde40baecc41e1d5986b1fef8354846f7fcca119fea3635bd904b181d6ae",
          "sha1": "2e3e6c62137f878068e1fc94c96432b1d69179f8",
          "md5": "3d72836453ab6c3a0bd80d2d6cea2e16"
        }
      ]
    }
  ]
}
