{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-domain/0.7.1/countries-info-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosArm64Main-0.7.1.klib",
          "url": "countries-info-domain-iosarm64-0.7.1.klib",
          "size": 15275,
          "sha512": "3e1e883e7f5e7c4f860244017049bdc861373c9daad6434869a37f9a078b687d5e27e7009d006e4f2977397eb3901636fbdec456bfb4294ab1b7e1c57c214d08",
          "sha256": "9319f85aaecfc109630b196cf7871af443ec03e884744f3ba75805604f2b5918",
          "sha1": "291c3b831b9f9813e5d8e0f54a6d18c19528e0d3",
          "md5": "abc5e4f7b95f9143eb44d0ab8655bd35"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosarm64-0.7.1-metadata.jar",
          "url": "countries-info-domain-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "bb3892d5c8f1a6236d82f17fa4dae2e042215394cfe1c45a0e0c5ca15d692547ee7c3afc2d1599eb2654503b048325f7e9aee2cf3e6316633ac710c8da014bb2",
          "sha256": "ded1e81d1ebee22429a52543f7886d3193a3eb5280b624be844159c3794aa97a",
          "sha1": "159e9affcd034dd134dee4212e66fea09b6d2b15",
          "md5": "cea67134eb46faadd10cc186e6be4b97"
        }
      ]
    }
  ]
}
