{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stripe-payments-usecase/0.9.1/stripe-payments-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "stripe-payments-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-iosSimulatorArm64Main-0.9.1.klib",
          "url": "stripe-payments-usecase-iossimulatorarm64-0.9.1.klib",
          "size": 4900,
          "sha512": "a585f347c65ed9059815e9836d26984ca811a14459bc1f14a56b9d949ed2025bc4f1a1c5abd4a8b9fd2433c2d4b361b0f78cb6b4c36b6021846c6580f4f94ac5",
          "sha256": "8233078e764200c757f4412c36aa49ac23acfe258d2082b2c4c85b0735e581a4",
          "sha1": "bbd8b593ec3ea197d2f2d560713f88464cadb1e8",
          "md5": "290d58866c214359675d41d15326b283"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "stripe-payments-usecase-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "90ca848470f788c19827a949d23587f3dc1232afa5a662279aa5e84b3f041ed8cca73c0381d65608e78dece09581e679df1b89821a3b1d5f993de3e17e117eb3",
          "sha256": "d6d19dca212b094643c617a38985dde11a03bdd0ccffe0dcc53ffd61686b0ff6",
          "sha1": "2da38037a97af89cda58ab20a3c795bc4f8f4a1a",
          "md5": "091fa49539f53007fc3ee67f6bb890bd"
        }
      ]
    }
  ]
}
