{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-data/0.7.1/countries-info-data-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-data",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosArm64Main-0.7.1.klib",
          "url": "countries-info-data-iosarm64-0.7.1.klib",
          "size": 16422,
          "sha512": "a6d1ada3bf4c26be3be8ace397fafac6dbccf8afaef71abbeffc56904f021232dfe80e715ad28b19d83a0d00ac749233707b873b03da88d1320c558ad8dc7bed",
          "sha256": "4bd149225f243a3352a1c2902f7beca15617c265ec36afcadb14dbfbf046e619",
          "sha1": "8119a28d8309c19d8d0b4a481cefa5001c2734dc",
          "md5": "2f0924666e57bfbebfda95981a66fb23"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosarm64-0.7.1-metadata.jar",
          "url": "countries-info-data-iosarm64-0.7.1-metadata.jar",
          "size": 3304,
          "sha512": "901a63cc783baf2a5e1863fdb4738dad8662e36afd1dd32e871363d86b288c9c838db55ff8f895634b39e1d729dcc3b036270700b0cc3d4bd3f5176aa0cedeba",
          "sha256": "e3e58d3fe1b115b0f6f82ec9087353da15c9a26a036d5a84afb7cd8452de6916",
          "sha1": "e310d3b9d45cf397e2aacc5886e76e7001a7435e",
          "md5": "5b9024edc0fe19a28c309f641286f9f7"
        }
      ]
    }
  ]
}
