{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api-config/0.9.0/sdk-api-config-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api-config",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config-environment",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-iosArm64Main-0.9.0.klib",
          "url": "sdk-api-config-iosarm64-0.9.0.klib",
          "size": 38070,
          "sha512": "e3b92c090622e09907f9a61b526aa526eb5cb63b8c4901876c274cbdb4cd2a8b99f7d7bab2e0c53edc929cd6e4c0c3b8d8ec6d7e97188d3decfef8a78bbcc159",
          "sha256": "877f036bd899e87ae9c83fdf3f54af965f388ceb0123533c1a6a991b3c4f863c",
          "sha1": "f1d7bbf20bd7a592276a5a18fc95c73d6b77d906",
          "md5": "4b9e184aabc48712bebedc71206c6942"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config-environment",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-iosarm64-0.9.0-metadata.jar",
          "url": "sdk-api-config-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "b97b2a5fe5afb8252d073f0aea45d113860a95d3765c4653342a903f5dc4189f74f194e109eb302a786d5bfebdb2fea536a05b43c687a0983eafe7d69721554e",
          "sha256": "335767bd60977047a14a285f914d65b8009a8cfebe863813425adf8137a821a6",
          "sha1": "1e86818de4d1c90d9ff2e7d0f533c769d3523368",
          "md5": "87d300bab79802a4f58176f12b7ea6eb"
        }
      ]
    }
  ]
}
