{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-data/0.7.0/countries-info-data-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-data",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosArm64Main-0.7.0.klib",
          "url": "countries-info-data-iosarm64-0.7.0.klib",
          "size": 16422,
          "sha512": "a6d1ada3bf4c26be3be8ace397fafac6dbccf8afaef71abbeffc56904f021232dfe80e715ad28b19d83a0d00ac749233707b873b03da88d1320c558ad8dc7bed",
          "sha256": "4bd149225f243a3352a1c2902f7beca15617c265ec36afcadb14dbfbf046e619",
          "sha1": "8119a28d8309c19d8d0b4a481cefa5001c2734dc",
          "md5": "2f0924666e57bfbebfda95981a66fb23"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosarm64-0.7.0-metadata.jar",
          "url": "countries-info-data-iosarm64-0.7.0-metadata.jar",
          "size": 3304,
          "sha512": "6fbf53c96cc826f8522ab9dfe25732fe46bbabdfe24de28b8a387f4df6e8dbb35aa3b54370a9b8de4696c5921c77325acdb93223c08dd786a181bd524c492058",
          "sha256": "5b03bbc61020ef14108e8d86be5f6b20deef1e3e1378c105416e3a51d016d20b",
          "sha1": "eaeb1cbf5817061dd5daf93d483dc5c4cef82859",
          "md5": "3754e8fa3b05672b8a34e3090c35154a"
        }
      ]
    }
  ]
}
