{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-domain/0.9.1/pricing-domain-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "pricing-domain",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosX64Main-0.9.1.klib",
          "url": "pricing-domain-iosx64-0.9.1.klib",
          "size": 23141,
          "sha512": "749edff6e05f7cb922f0ac24b8558148d2e9e77f9e9f73065a7901c02ef067e26345937352d6d5776090c39878cb127a07bd1067485a811431f7dbe28020256d",
          "sha256": "9b4229b6d98e433028f71086eaf25b801a320d7f6238ae0f71833a65fc3bb2bf",
          "sha1": "c8114e7e22504853acc77a790f6bce208ea7f303",
          "md5": "06ee2404eb98d5c68d7e729b838f4423"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosx64-0.9.1-metadata.jar",
          "url": "pricing-domain-iosx64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "b1feb116f3dce9605b6123288d49ec0ca7c5aa486fa587ad56148ff5a1fc65c592c778f1d16eb3450fbb6fd90e3e788542c1c578c7c946fd912831a369cab9f0",
          "sha256": "88d14537637512cde234b90f1d37ad9dc98f9f878f26d3d455b9284dec878e30",
          "sha1": "5adf4a948436994f58544cbf4ebd426217f72bf9",
          "md5": "b87d98cba2d196ef043d87da33f4452e"
        }
      ]
    }
  ]
}
