{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservations-domain/0.8.0/reservations-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "reservations-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-domain-iosX64Main-0.8.0.klib",
          "url": "reservations-domain-iosx64-0.8.0.klib",
          "size": 22989,
          "sha512": "1a3d7accaeeb9d4cfb6b4daa1cb5d8b97141e43c1f3a39a17939ae48e4f3d9e36795441e22f4f5aa2b7ea6fb66a73bcec8e4d1baf268ee1ed60941debb5c8b9e",
          "sha256": "08f721a89fbf0693345556d91a6e80c99af35b2f29b89e273000458b60159f2c",
          "sha1": "518c5e552db5918ce6e68f58fd761b7c88c0a420",
          "md5": "1487cb89edef212226852cd4f87483ff"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-domain-iosx64-0.8.0-metadata.jar",
          "url": "reservations-domain-iosx64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "54b61dff652887a2c2350a0e61522904cbf2542af445ce7e561b3ed567c042e7bb185c691aa59ddf9e715aad17f490e7936ad731169420ec80a374c9859663ca",
          "sha256": "cb7b58defaa2e689ff983a06e3c5e561f9ea08d7c98eefa5a4b12ef225ad745b",
          "sha1": "f79e370ef2981aeee0aa449f3a66c9cdf2e1ecb9",
          "md5": "1e732b3c737d1b8a3e67df382feafc0b"
        }
      ]
    }
  ]
}
