{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservation-details-domain/0.7.1/reservation-details-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "reservation-details-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-domain-iosX64Main-0.7.1.klib",
          "url": "reservation-details-domain-iosx64-0.7.1.klib",
          "size": 52399,
          "sha512": "38693dbd9bc6b0b177a9fd484b92b19a9fdda3ddc4626d1c2855da90abaab69c3ed42675057661c77412c878035d1ad385d9382a62d153db12e666281603f0dd",
          "sha256": "8be3a4d4a43fdb74f9eaadaade65175e83c6cc9747c6f86f2f05dbc924b19605",
          "sha1": "599a0edf221144f7a77ae831ed5b7b46b4590ff8",
          "md5": "5e15a5197af7205bca3345af57695e45"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-domain-iosx64-0.7.1-metadata.jar",
          "url": "reservation-details-domain-iosx64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "ffc6856c921a0bf85750276eace89192e872600b417f932f1915c341fd923bb020308f88baa4d761dd210a1fb28b58d3b9586f2cd487b26e60cea86502659697",
          "sha256": "0913eed9c153b9e531b6284c12b1dc41c27d85a6dbec037fd05c1115c9daa4fc",
          "sha1": "458830880182d1fe70790b04b09c6a15c86982f6",
          "md5": "4ddb03de8ba13bc627648d60f9d743f3"
        }
      ]
    }
  ]
}
