{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api/0.8.0/sdk-api-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-release.aar",
          "url": "sdk-api-android-0.8.0.aar",
          "size": 10192,
          "sha512": "fac2ee49ee4d0595942046ee1d0237ff9d1212b441c8432d80b91095a2fbd5aae35324770f4be19f5d8e3d6cf5ccf31613670bb901304249227a3a426f68836d",
          "sha256": "28b2ad5d3f79d391e3b58e0ff561bdd658e0a7e8113a6cdba2329a7e80afbf6a",
          "sha1": "adf8a9d83f89801a11f2a844cb198d2ebfbb9ea9",
          "md5": "8a1ab171ac9d7624db99c35d8d95241a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-usecase",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-usecase",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-usecase",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-usecase",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-usecase",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-usecase",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-usecase",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-usecase",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-usecase",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-usecase",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-usecase",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-analytics",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-di",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-api-release.aar",
          "url": "sdk-api-android-0.8.0.aar",
          "size": 10192,
          "sha512": "fac2ee49ee4d0595942046ee1d0237ff9d1212b441c8432d80b91095a2fbd5aae35324770f4be19f5d8e3d6cf5ccf31613670bb901304249227a3a426f68836d",
          "sha256": "28b2ad5d3f79d391e3b58e0ff561bdd658e0a7e8113a6cdba2329a7e80afbf6a",
          "sha1": "adf8a9d83f89801a11f2a844cb198d2ebfbb9ea9",
          "md5": "8a1ab171ac9d7624db99c35d8d95241a"
        }
      ]
    }
  ]
}
