{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-usecase/0.7.0/authentication-usecase-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "authentication-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iosSimulatorArm64Main-0.7.0.klib",
          "url": "authentication-usecase-iossimulatorarm64-0.7.0.klib",
          "size": 5075,
          "sha512": "65fa77990acd19f3f32d5a78798fec782788208c0158bb3cdc6f10ca93112ad4bc564d4182d4324bd15aa30e92957d9ed7e76d418dbcfd5be003020999991b6c",
          "sha256": "37fecc854911b9f891e47e0c9da62577c9a47c8a241c43336154eeb93172887e",
          "sha1": "5dad57405b79be59400cf0b093bcf6c8c59e5c8c",
          "md5": "eefd79e5a130d24e6ce0918c578beca8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "authentication-usecase-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "81610da07977475303e6d9b77f16dea8ae1409cadcdbd22206be5b10b07110c2dfe9882396356c0e23f3a3e1b578c72f8f3cd66d4bd3f5a1e3d8138ede31cb5d",
          "sha256": "935dd80866bbefaa26d8433dc67dd4ed1047a001a0b382d7578c188dafb25592",
          "sha1": "8fe7a16172a1a0099337ac8458b7dd9183f1b6c4",
          "md5": "aaed5badcaa0b791c22a3b12edd85e78"
        }
      ]
    }
  ]
}
