{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-data/0.9.1/amenities-data-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "amenities-data",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-data-iosArm64Main-0.9.1.klib",
          "url": "amenities-data-iosarm64-0.9.1.klib",
          "size": 22340,
          "sha512": "cfdcf296edc2985f9fff7b70678d88b0b8fa530b886f342ec2c79113ab172465e78b13a2c37b4380f923350d8dde8026c3c0511381a5667689efb26e72c92159",
          "sha256": "5d5ee75eea6fe4b061f53b3078a622c027cc24b42f241329a8ba1a7064489c77",
          "sha1": "74c970b1c655c98a51033b5b1f045c8d7aeb5c3c",
          "md5": "062cd871b5df907e01f6e95a9af6cf44"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-data-iosarm64-0.9.1-metadata.jar",
          "url": "amenities-data-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "f0aa1733c7b90ab3cbef864e3608a936363a8abbcef502c42b1cb0c8cf1ae4d1ed374b8d4d4884894e8af58df8d0f6f06dbf0660e61a758cb449e883f92d31d3",
          "sha256": "d7df630c4585b0572ed022410e19e7aaf38471978631d87b184e2a7f6fbf157c",
          "sha1": "4520b72b3709c79c0ec8352449a6260178d68d32",
          "md5": "1d0e365b2b4ad87570f7f4dc68c249e9"
        }
      ]
    }
  ]
}
