{
  "formatVersion": "1.1",
  "component": {
    "url": "../../search-usecase/0.9.1/search-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "search-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "search-usecase-iosArm64Main-0.9.1.klib",
          "url": "search-usecase-iosarm64-0.9.1.klib",
          "size": 4741,
          "sha512": "99bcd4d458f1cd7a4c431514edbc876183b3518005befd078d183c9cef516ed38e68a49778326ed0c50680de867e9b17c2d0dbb6044539525088ada89965e377",
          "sha256": "e1ff4cd600905f82fdc0f73e8bc6a0a7d1e088d6e8d61a7e14bf9765f6d5e350",
          "sha1": "5d6dc2fced0598fd0534e67ac50a65c69acac569",
          "md5": "c4876c2372bce9d8a5c613b9941952f6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "search-usecase-iosarm64-0.9.1-metadata.jar",
          "url": "search-usecase-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "3df85b1acd6ee4963abdf261aa32f3bd4ab8eab19806ddc4c8fba82f6f906b2b5b575ec96274210c2ec3fa6385c43b4273177aca52886691e8003c665d36c2e9",
          "sha256": "bc4c2fb1600ddbd7e4e169613ada31ca2334a4b6d369f3bbde6ba0f11528a0b4",
          "sha1": "4b1eedf7790694604cc1fd3241e3ecced6656855",
          "md5": "3183e2a6e01dc6e2f2f37e85fc80b14f"
        }
      ]
    }
  ]
}
