{
  "formatVersion": "1.1",
  "component": {
    "url": "../../stripe-payments-usecase/0.8.0/stripe-payments-usecase-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "stripe-payments-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-iosSimulatorArm64Main-0.8.0.klib",
          "url": "stripe-payments-usecase-iossimulatorarm64-0.8.0.klib",
          "size": 4900,
          "sha512": "a585f347c65ed9059815e9836d26984ca811a14459bc1f14a56b9d949ed2025bc4f1a1c5abd4a8b9fd2433c2d4b361b0f78cb6b4c36b6021846c6580f4f94ac5",
          "sha256": "8233078e764200c757f4412c36aa49ac23acfe258d2082b2c4c85b0735e581a4",
          "sha1": "bbd8b593ec3ea197d2f2d560713f88464cadb1e8",
          "md5": "290d58866c214359675d41d15326b283"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "stripe-payments-usecase-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "2438d2aa0c07c32e552aea67c6f374cda040af0b5ca76b35ba2b69f808dbfc620e62fa5b88490bde678deb2420e65ff103ccb22a21febd02f534ee4d447bcaf9",
          "sha256": "48bb80f48412e5dd5dfa101f9c2595cf840fc34c9874b1afdb41d77d3536247e",
          "sha1": "4c1ef8fb6a11f502a4ff9ded8d63cd86571eb795",
          "md5": "ca6d2b218565a4ce8cbb0dfefba78a0f"
        }
      ]
    }
  ]
}
