{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-domain/0.8.0/amenities-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "amenities-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iosSimulatorArm64Main-0.8.0.klib",
          "url": "amenities-domain-iossimulatorarm64-0.8.0.klib",
          "size": 12781,
          "sha512": "9a35d219ee7a62e4bfabee54dc1174dcf6b9f555539d8b96e81c0ec8cfdff34bdcfd4cd4e59edbe2093a38a5d2e63fc2abd05b1a5096b73d2f5b01fd2fb05558",
          "sha256": "8a0c0bf0a12a5e6bd626dea98c3e0341104d017fa3868fe925b27f5b4cd4c934",
          "sha1": "3533cacaaf8cbdc142d87c95c001557b7b61c733",
          "md5": "b2b01f08f4e454561dca5ed7d7c5b2e4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "amenities-domain-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "amenities-domain-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "20b2b3cd40fa625a2b7a4855cb8d1baaad0c2f504bc852348864b4b57f9280ac4a7054ad6725b4e83eeac9a5db890af4f0982794e6663f5fc0a37d9e1945cfaf",
          "sha256": "2fa05459a6117cdf7c798b408f45ff5868c780af36cccf9da7a2c87513260dbd",
          "sha1": "8150218fa0e0986646104f9847cab7921897851c",
          "md5": "e276248f2f02a5c4a430e3d5424c6c75"
        }
      ]
    }
  ]
}
