{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-domain/0.8.0/authentication-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "authentication-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-domain-iosArm64Main-0.8.0.klib",
          "url": "authentication-domain-iosarm64-0.8.0.klib",
          "size": 44128,
          "sha512": "ea4155df09521d8e38a303100980d1bc1727e3c6c4dc86d4ecf1328377feebb0c13ec20c026c168203f93d99fb14723db45d656746e422f01cd5e1d59d938a36",
          "sha256": "66a5dbf498daaecee0e9012b2e561f0eb7cb5cf0884a129c6b4c74fad6f9f755",
          "sha1": "7174fe7cbf1a84034d84f9e10205aef04603a2bf",
          "md5": "a21a4d9f1b51e08043bfb0adaf611aa6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-domain-iosarm64-0.8.0-metadata.jar",
          "url": "authentication-domain-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "56a8353ebd4cd910b7ce72417d5389bcb5ac456e2cef59e6e856ea21f0c8aa92563074d76f7d6b440b24c5fd2aa1f99d191d53c04255f4e0774439a18275e997",
          "sha256": "d90deffc462b92746cefd1615be585a68c12cccc90c5345c6f994eada86e2d65",
          "sha1": "0fa4178ecb95ec57a26f9df5b8a54698133b8163",
          "md5": "cc5d7ca32c9a8ada815c6afab77d9384"
        }
      ]
    }
  ]
}
