{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservation-details-domain/0.9.1/reservation-details-domain-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "reservation-details-domain",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-domain-iosX64Main-0.9.1.klib",
          "url": "reservation-details-domain-iosx64-0.9.1.klib",
          "size": 51780,
          "sha512": "7d88989e7523cd4e65379c71fef5fbde68989b68465e543687666ea74e6b310301461d61eb0997ec02272a9d3252182d60db719d041c988adcc6381408640dfb",
          "sha256": "b3258135daf8f4a076eb2b3535facf6325e2cc0d4adf3fb35456209fa296d641",
          "sha1": "cd12dc27651a5f02ef6ced3de08dfe06b267b190",
          "md5": "a29003186c3e89edaf04cc238786d337"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-domain-iosx64-0.9.1-metadata.jar",
          "url": "reservation-details-domain-iosx64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "c109b964d27659a2a7b493966f5a027461da2d03f388c49b2fdddf84f1489e2964b545f2206230aa71f7951aad39f859671532d9acbdeec32e94eefa0139cd77",
          "sha256": "161e213d4d175baee616d8e7b0e5cb669a055bc0d2c84d6cd6b27a7297da2126",
          "sha1": "b22aa8d0a7a962024a96c7d1aafd32ee7a8646ce",
          "md5": "daad6e443a1a81f4bbfd6f03a5d6c7eb"
        }
      ]
    }
  ]
}
