{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-permission/0.9.1/core-permission-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "core-permission",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-iosX64Main-0.9.1.klib",
          "url": "core-permission-iosx64-0.9.1.klib",
          "size": 33804,
          "sha512": "917e97c721de067b42e6ae8cad1adc54ddee3da30b1907e57f6bef488f22bdf819d934bb08a59d96047a8755b8a5905db461a801dbaf1f84f4cf46759ffbd0b5",
          "sha256": "2328620d9f57a77d43df41b4a7d9b663338116a6c5792df0cbefa4b926ec6cfc",
          "sha1": "8bb7f84bc813ec132142a5786aa7d09687dd0d6a",
          "md5": "5e2c96798c7cb669d66de721062fffec"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-iosx64-0.9.1-metadata.jar",
          "url": "core-permission-iosx64-0.9.1-metadata.jar",
          "size": 3162,
          "sha512": "fb8cdb5ee51204a6fd59f0c2f48eb6d171815cc87e61324dbc4e6756235686518469194f9c1e9318029088f2a5b7cc49d80df8b9ee9976538b16611f486a00d1",
          "sha256": "d04b79174f7941ce34df9a777608a5c04daf171e5ab1d1628edcdd5b44307cd4",
          "sha1": "0a9f18c2fd55b76fca0a7f556436620c5d0bdab1",
          "md5": "c0738938a834dfd4f4f131b5a029fa73"
        }
      ]
    }
  ]
}
