{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-domain/0.7.1/pricing-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "pricing-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosX64Main-0.7.1.klib",
          "url": "pricing-domain-iosx64-0.7.1.klib",
          "size": 23431,
          "sha512": "8647bde80b4351c98034adaa1894cc6e3e192e9e6cdd5fc498df2a5d366276ded1389f786f45685283aafa177571c2b19cd23edcf2d3fe70d3f9ee89d2916214",
          "sha256": "9e7dec0c5f096521ec3051bb93ac2761e2f50a30b74a6daf6346cbcd653da41e",
          "sha1": "e631f887c020a9063a88a6e3457f2fe2485938e1",
          "md5": "4859cf3489b025d340e81e8a7c3183d1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosx64-0.7.1-metadata.jar",
          "url": "pricing-domain-iosx64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "9bb4a018121aff619484a187b9ca537959ea49a75327c2b31ecbcb9ec4092048c5c318b7f1a87ffe8e357194d7134f62575b1cd6beb7766d5433fcebfd052162",
          "sha256": "8c132f7f6b9708e11fcb6d5910fbfcc3618a87f4edb90d439353ddea2c49f5bc",
          "sha1": "030bd3e4573085856f77cd3abcc6fd833d34d8c6",
          "md5": "c9d4a19eb54d21d4b76648b2174b7900"
        }
      ]
    }
  ]
}
