{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coupons-usecase/0.7.0/coupons-usecase-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "coupons-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-iosSimulatorArm64Main-0.7.0.klib",
          "url": "coupons-usecase-iossimulatorarm64-0.7.0.klib",
          "size": 4955,
          "sha512": "9d26efe77fa49328e0b315b2ed39b76dd58805a24876f9476e0e1d3f79f4846a85e63b5aad3a588c86375e277db1b491603f7d0588a8b9736304ed9a2aecc2c0",
          "sha256": "78668699371b02cd71509a8a7797cc1121d6246039ca7538496f3a0dcf764d9a",
          "sha1": "5041bf65f35e74ea3fc05ec5e68d5bd2f9fd03e6",
          "md5": "daf7c81cdb0f15783c023252ecbfdf12"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-iossimulatorarm64-0.7.0-metadata.jar",
          "url": "coupons-usecase-iossimulatorarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "677b6d61a37549b91908d5a1afc377f0cc19649167cec0df33153530743441aebb73f8acec4a8a00b45db8377c228f0dbc623cafb6f98ccd4f29a647b12a7cf7",
          "sha256": "1551aeac126ba0bd04f3fdc9575da0086f9f2f2aef7316d4e4d0471429b43f0a",
          "sha1": "5ae026736ba26e8876d8365b41e3cfee50af7278",
          "md5": "d440f6643801a807095e21b25eff2a0e"
        }
      ]
    }
  ]
}
