{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "reservation-details-domain",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservation-details-domain-metadata-0.2.0.jar",
          "url": "reservation-details-domain-0.2.0.jar",
          "size": 19795,
          "sha512": "756c3f335b675e845fff12e66a6d6f36152220f4821ac9338b7963c7fe0f29e3cc46a69f816629cf422f0fb5ba9f9b881df13ac909cfeb9ddf63b0a37d67558d",
          "sha256": "5793baabcfe34eba77b102bae4144cafb7483b4857bccc381488b2ff8260b73d",
          "sha1": "26cac29ad3d62e1862be4c569b94a3abd8ca4ed0",
          "md5": "9814aaec7f65097187993bd18f8682b1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../reservation-details-domain-android/0.2.0/reservation-details-domain-android-0.2.0.module",
        "group": "com.mozio.mobile",
        "module": "reservation-details-domain-android",
        "version": "0.2.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../reservation-details-domain-android/0.2.0/reservation-details-domain-android-0.2.0.module",
        "group": "com.mozio.mobile",
        "module": "reservation-details-domain-android",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../reservation-details-domain-iosarm64/0.2.0/reservation-details-domain-iosarm64-0.2.0.module",
        "group": "com.mozio.mobile",
        "module": "reservation-details-domain-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../reservation-details-domain-iosarm64/0.2.0/reservation-details-domain-iosarm64-0.2.0.module",
        "group": "com.mozio.mobile",
        "module": "reservation-details-domain-iosarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../reservation-details-domain-iossimulatorarm64/0.2.0/reservation-details-domain-iossimulatorarm64-0.2.0.module",
        "group": "com.mozio.mobile",
        "module": "reservation-details-domain-iossimulatorarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../reservation-details-domain-iossimulatorarm64/0.2.0/reservation-details-domain-iossimulatorarm64-0.2.0.module",
        "group": "com.mozio.mobile",
        "module": "reservation-details-domain-iossimulatorarm64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../reservation-details-domain-iosx64/0.2.0/reservation-details-domain-iosx64-0.2.0.module",
        "group": "com.mozio.mobile",
        "module": "reservation-details-domain-iosx64",
        "version": "0.2.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../reservation-details-domain-iosx64/0.2.0/reservation-details-domain-iosx64-0.2.0.module",
        "group": "com.mozio.mobile",
        "module": "reservation-details-domain-iosx64",
        "version": "0.2.0"
      }
    }
  ]
}
