{
  "formatVersion": "1.1",
  "component": {
    "url": "../../search-domain/0.7.1/search-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "search-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-iosArm64Main-0.7.1.klib",
          "url": "search-domain-iosarm64-0.7.1.klib",
          "size": 57496,
          "sha512": "3ff5e8bff8ec82f7bafd3f31b2e88eed98b4ae5b9a40d3b4bad7fd1b7fdf67a379344660bdb91e033a32f85f0ee880429b66787836f932581806373227e0d845",
          "sha256": "837d10c74c9c4827fa0c60c93ab5666287ea475b41c42a4ab199f1f6d65c0008",
          "sha1": "7759ccd4c2359d9ac5743ef62c0f0e83bdad8e45",
          "md5": "ace92bfcbeeda524aaf288c75fa707a3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-iosarm64-0.7.1-metadata.jar",
          "url": "search-domain-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "bdb3f6fafc0e20c72a50e6cb29b3238ed86a9317cc406f8840b4370be6b5e5c646340da995a85ea8586dab172cb20cfde7370d1fdc083f480d8a6a3ac15e4480",
          "sha256": "e36db2446396562bc1ba375c9edd3f72903d43b1b182601d99ca7bdc82e28c2c",
          "sha1": "a31be6c31f24a235236de5b1a3e4fcb6b283adb6",
          "md5": "c04151bf5c72c2a06bf78060092a348e"
        }
      ]
    }
  ]
}
