{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-domain/0.9.0/pricing-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "pricing-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosArm64Main-0.9.0.klib",
          "url": "pricing-domain-iosarm64-0.9.0.klib",
          "size": 23146,
          "sha512": "ffa114b24d92b59f3911f7b59921df0122ea761476a7c3445d7c224b9d2b68ded82088aeafea96d95ca7c101fbbc044f3f943e62827b8f71e6cb4c6bd00ca517",
          "sha256": "fa502f9ebaaa0834b5b696c96b07e080a0fb451b603bfa915e27dab179334675",
          "sha1": "d4c3b85d66c6e4d0b2dfd17a27abd36dc93bfa79",
          "md5": "e9b31a01fd2a6245317093af43b06a7a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosarm64-0.9.0-metadata.jar",
          "url": "pricing-domain-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "bd079d0e1c02d6c3f407bcb3be26bff829fa262f4165a2745132d566ca1b847aad41f2d113aed74f0172c2013fd383b8b4b898e8eb26a5ed07a086aa4121e51d",
          "sha256": "67b13ff7673865953f1d0d69e1f278e3a0c9ee2efa30dbdc8373301d16c99844",
          "sha1": "600a31749b4f3c968826eff71f8d9f66c5bd0e3d",
          "md5": "5601d1cd4683f4ba12b48c5eb8ba1c12"
        }
      ]
    }
  ]
}
