{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-data/0.9.0/countries-info-data-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-data",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosArm64Main-0.9.0.klib",
          "url": "countries-info-data-iosarm64-0.9.0.klib",
          "size": 16292,
          "sha512": "1ade087c3d9b0ccd803aa86e569fd8c1d4b565034e5538deb95fc7d910b4afd2345dc6de84fdea9034d9dc5b25a73f0a32a79452280cfcea18b3739f02d6fb34",
          "sha256": "11c808b8d68ec64f34b7bc674dbde58d7670ea09ce368281ece4388840a6e9d1",
          "sha1": "2b77b9c926a76d8fa85ace3b8c51deed39c7a8e2",
          "md5": "c74ab09a2690d3bab6a53326f186f564"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosarm64-0.9.0-metadata.jar",
          "url": "countries-info-data-iosarm64-0.9.0-metadata.jar",
          "size": 3299,
          "sha512": "b80c7d958b5f65884390f9b40cf587b539af2aaefa4c5b537c52d0101cc2d80c164f4c58630eb2863d309c80a3572c7ed9e471225eb4dfe18f5cbc1f06225c3e",
          "sha256": "656886f9e46ddddf71e64c4847e970e5086b9fe80406140fd8b36b36b810e6b5",
          "sha1": "31e3dbf2ffdd0f487e2fc3f4ff63c9d34b0a807c",
          "md5": "2c1fba3f52990a93ff79cc002fae6f6e"
        }
      ]
    }
  ]
}
