{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-data/0.9.1/countries-info-data-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-data",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosX64Main-0.9.1.klib",
          "url": "countries-info-data-iosx64-0.9.1.klib",
          "size": 16279,
          "sha512": "18f5919a6f824d78b0b9b4f13652faaf854a1ba4c6e1f95ec0021d4d4cff53a8d64eaf6a26b8e29c82d2fe7635275a6754f8ad997b188cec4a80f74f726438a5",
          "sha256": "222cbf77cb7d25253b67ed2a5f7411106b12a6f0b68fc4344640520be8b27c28",
          "sha1": "f809f25ac0684e8cce0efa0ed4b48685b9da1614",
          "md5": "e1608950fd2fbe3b10b6781476e0ce4f"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-data-iosx64-0.9.1-metadata.jar",
          "url": "countries-info-data-iosx64-0.9.1-metadata.jar",
          "size": 3299,
          "sha512": "034411f1e41f377974eb96a4706bb2b8738e544c1a3a7e5b67dbce74b9e3a041853462e9caee1dcec1a81d5e8e1f74d6986dfbbbdcbc0850ffe68245b92ef0ed",
          "sha256": "b9817dfc36751071fff5e3b6d24040099a5e78eb61c8d9bae576a10590f4e218",
          "sha1": "e841a11cf5b5ea8f9151c82010755fa30eed520e",
          "md5": "97cd24613797141bac49ea07fdb5b6fb"
        }
      ]
    }
  ]
}
