{
  "formatVersion": "1.1",
  "component": {
    "url": "../../locations-domain/0.9.1/locations-domain-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "locations-domain",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosX64Main-0.9.1.klib",
          "url": "locations-domain-iosx64-0.9.1.klib",
          "size": 33637,
          "sha512": "d705c4f745444efb46051d930d6014c1603e2fd9a307ca278d0ba2f63d8625d86fdee27f159cfd41f379be8b6f9eb5c2b4498f0558bd8cf32f2141db6f74a7ab",
          "sha256": "590f076a7c5f1e8ca0db3d02d5d6ddbb496c8188409ffb10ccbcf49959c99d00",
          "sha1": "b3436247852f2d5f7c492888002d921a47083760",
          "md5": "4f62baf0902a5af771183465b56424da"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosx64-0.9.1-metadata.jar",
          "url": "locations-domain-iosx64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "2fe1ad84e80bba297d6daea34cd8b4f9d24f89f3bd5624bc7ba9be67e49a92cc971e9fb7818b97cec10fd27c1c5e081a44c1aaecc2b7bd3dd26d8691ec3444c8",
          "sha256": "3969993ba9494afd8658ae0cb35d0c5ccb88d4e69b9dcd083bac2f3372bb40e8",
          "sha1": "574909b8598d9cbea0e372b285f414be0291735f",
          "md5": "4191e3e39e45e9289f17f9d8a43f5cf5"
        }
      ]
    }
  ]
}
