{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile.android",
    "module": "search-rides-ui",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "search-rides-ui-0.2.1.aar",
          "url": "search-rides-ui-0.2.1.aar",
          "size": 1472205,
          "sha512": "eaa462cb7446f32fc3db466077c297b04efe88fe360a9ce4fd8c4b0e2f53ac71c5f30c11354af347bac11f9a4eee5acfe2c1b479e2850e142708595dc13453f7",
          "sha256": "ae57307d01dcf096e2fdc16f28d0684af7793cbf24d12ef399b471c46782584e",
          "sha1": "3c5fe16ef40544b989c849edba0ff66839fc4c4d",
          "md5": "fa990312d0e1ca8caee69232e1e8c3c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "core-ui",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "prebook-ui",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "prebook-bookingflow-ui",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "googlemaps-ui",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-usecase",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-svg",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-compose",
          "version": {
            "requires": "6.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-ktx",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-utils-ktx",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "search-rides-ui-0.2.1.aar",
          "url": "search-rides-ui-0.2.1.aar",
          "size": 1472205,
          "sha512": "eaa462cb7446f32fc3db466077c297b04efe88fe360a9ce4fd8c4b0e2f53ac71c5f30c11354af347bac11f9a4eee5acfe2c1b479e2850e142708595dc13453f7",
          "sha256": "ae57307d01dcf096e2fdc16f28d0684af7793cbf24d12ef399b471c46782584e",
          "sha1": "3c5fe16ef40544b989c849edba0ff66839fc4c4d",
          "md5": "fa990312d0e1ca8caee69232e1e8c3c7"
        }
      ]
    }
  ]
}
