{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservation-details-usecase/0.8.0/reservation-details-usecase-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "reservation-details-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservation-details-usecase-iosSimulatorArm64Main-0.8.0.klib",
          "url": "reservation-details-usecase-iossimulatorarm64-0.8.0.klib",
          "size": 5017,
          "sha512": "877e2876d35427b786d7b98a40dff88bace0f07a4a6c2752fc0dd45c7f16e911f94ab6266f5d5299373dfea17e2844ccdf87cea0ac3a2c562974a4c566e2f073",
          "sha256": "1e47afc40726e824d15986740fd5b33986716c370f8f1b7aeaaba38f9a27dea5",
          "sha1": "05a3d95cb89a04fe7105b2ea46d823c5e82d0e8a",
          "md5": "46beb92e55fab950617e26e5353b46c3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservation-details-usecase-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "reservation-details-usecase-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "f8640c37a4a311ac8efc2433d948a6c6c6e6430ccd859fd331343c9d75d17812c86e7662679ed8803dc17dd39ae4a95f9a50ecd0d1988e7d8269f09391260206",
          "sha256": "6ac94fff841bd696e7b9c6b346ea9d6b4165e308962c1fd47f48139277689d01",
          "sha1": "1471a34e09c07e1fa2589cdd580afdbd6be25ed3",
          "md5": "923541f90ef579c7d73e7028ed2d26d0"
        }
      ]
    }
  ]
}
