{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-usecase/0.7.0/pricing-usecase-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "pricing-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-iosX64Main-0.7.0.klib",
          "url": "pricing-usecase-iosx64-0.7.0.klib",
          "size": 4880,
          "sha512": "a58b8bf879ba1971b8a143595d8ec23e2becad9327c0e86cfe45425d9bf0d2eab1eff7b0f7d7aedc704868d064b9fba7fe16a7a81135ae17f2377906d73269f9",
          "sha256": "e527d28ee3c1aa4040c2aacb9124e03f6505da2b788cd9de87380720832cfd44",
          "sha1": "6314d7d531a0a8936c3ab0dc1da426476d2271b4",
          "md5": "35f34f2af569e6a15ce3c8da91afb3c5"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-usecase-iosx64-0.7.0-metadata.jar",
          "url": "pricing-usecase-iosx64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "ecd92b1f8a15f9b59d51fe88bd1969977412233d2286947e1bd47ef881af701dd2a00b13d2c14ba05f95b380038b29bb5f6aebb1df1c68e298363df51a58ebf3",
          "sha256": "21516f8e5bdbc03152bfb8c094c2cd03fc635edeaa5c4d923e08170f5b935d02",
          "sha1": "9dc08b0807a2be44798a4a6677bf411ab23cefc1",
          "md5": "deb80adc5b16ae3571a88e8c3459c1f6"
        }
      ]
    }
  ]
}
