{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coupons-domain/0.8.0/coupons-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "coupons-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-domain-iosSimulatorArm64Main-0.8.0.klib",
          "url": "coupons-domain-iossimulatorarm64-0.8.0.klib",
          "size": 23865,
          "sha512": "ad21335aa7cb966c24fea3c13a1a4ec730c1e82c2c78c2698d001cc08622dc0a55954c4fa0b28490e7a2a149b4fdf795647d09d65147a01e76535cda9dad823e",
          "sha256": "16ca764607a83af8ff3b50e640cc47cb241d3c6f8b875cba69e3cd1e9a847ed5",
          "sha1": "6257e01c8dee70886cb8ac4c03006dc39597dfa2",
          "md5": "66c43b8a02dcce5f8840411b298b69c1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-domain-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "coupons-domain-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "51b0ef3fef6a8dc0c62782e79c5c0e2e44365ad45a3c7db9e33940eb23e2b9cfd9beca8c598021edff7797b940187f8b4613a822fe910fcd4cb31ac2d7492352",
          "sha256": "7a5ef6e955d42c5d8054b0e7e9ce36be72c9910a6e2ecd4d9a4b03559cf25ea6",
          "sha1": "78bfa8cf30c408b5637f31172885d666bc0c2f3d",
          "md5": "c086298fe2b80c9c299bed7c1b5deb57"
        }
      ]
    }
  ]
}
