{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mobile-sdk-bff/0.7.0/mobile-sdk-bff-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "mobile-sdk-bff",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-iosArm64Main-0.7.0.klib",
          "url": "mobile-sdk-bff-iosarm64-0.7.0.klib",
          "size": 136319,
          "sha512": "206341147065dfad5a9ff3edbf0ef9af4ce2c58d55a0c2736318bcee20ebe03f3f2b358e2e1d1b33ecd7f72e7999d9ddb3d6cd909b87cd3959e024336a475087",
          "sha256": "a935496dffe2be2dd30a98e1d132356b0ab918269847f9bd4d9062e18ef1dadf",
          "sha1": "6b58b89853d1732a7a6c5cb3dac10991bb50841d",
          "md5": "188a553ffebf2dd3278dd50ecdea4cf8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-iosarm64-0.7.0-metadata.jar",
          "url": "mobile-sdk-bff-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "f88e708b30d75fe10443214f0c5dad15475bace0731956de14aa2087ebba36aee64e4438f6325bf1b979def46d5b721f95ef71bedd7a76da3009def93f968cf3",
          "sha256": "4273db65dda1369c04a99dbd7dafe172a3de09f02ea1f343641c15630c52d1da",
          "sha1": "062e9177e1764ed80acab5b87e9429fa99f1d98b",
          "md5": "666d82ed9f249e2d9eb66bbf8189e14e"
        }
      ]
    }
  ]
}
