{
  "formatVersion": "1.1",
  "component": {
    "url": "../../locations-domain/0.9.0/locations-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "locations-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosArm64Main-0.9.0.klib",
          "url": "locations-domain-iosarm64-0.9.0.klib",
          "size": 33642,
          "sha512": "01490a7f4fca3177ec2e602fe8b42f04fd287de0e48e6ad4a8dac97bbd506b50df2d9c605edeeaabbd7e9ea8f10b49fb31ecc004e32e1745f065330f08dc694a",
          "sha256": "3348b97d196bfeaf5644d37a06b1de660f7bc63e4426d1299f9110495f663ba1",
          "sha1": "a02578c095bab004d0b740a32894f0756272b283",
          "md5": "5a130708d7078d7a35a607e2ba70b5a1"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosarm64-0.9.0-metadata.jar",
          "url": "locations-domain-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "ccea7ea1992e5eb492b6cc0ca1f8f3d32a0f0a5cb8cab46e9050c20a7e5e40ed7019682f961d4b4a02b631375eef24cb269dceba89d58a5b976e8a4b3eb01abc",
          "sha256": "0b69aea4a61879d1b1a63970490c07851db233184c55c23046036df537b90284",
          "sha1": "c8049cdb2bd81ed4a103b76da12113e93615aca7",
          "md5": "2e38c9535b2ec04faec44dec6cae0ac7"
        }
      ]
    }
  ]
}
