{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-domain/0.8.0/pricing-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "pricing-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosArm64Main-0.8.0.klib",
          "url": "pricing-domain-iosarm64-0.8.0.klib",
          "size": 23146,
          "sha512": "ffa114b24d92b59f3911f7b59921df0122ea761476a7c3445d7c224b9d2b68ded82088aeafea96d95ca7c101fbbc044f3f943e62827b8f71e6cb4c6bd00ca517",
          "sha256": "fa502f9ebaaa0834b5b696c96b07e080a0fb451b603bfa915e27dab179334675",
          "sha1": "d4c3b85d66c6e4d0b2dfd17a27abd36dc93bfa79",
          "md5": "e9b31a01fd2a6245317093af43b06a7a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosarm64-0.8.0-metadata.jar",
          "url": "pricing-domain-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "37ea9c0a8966540d0842c48016fe4c0ecaade68c8b3ac35896c02f6896cb2031cbe852c66276e8eb4116bb685b02d40cff4a9697992ca79b957a6fbfc0363c6a",
          "sha256": "dd645edd1e4401de7a368f39a55878b06470249143d6064583a276baead8bdfd",
          "sha1": "3eebca1359ee63fe71c1d69b6223b20b5835ad3f",
          "md5": "2bf6243c0ab663f53cde848be430ab8e"
        }
      ]
    }
  ]
}
