{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coupons-usecase/0.9.1/coupons-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "coupons-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-iosArm64Main-0.9.1.klib",
          "url": "coupons-usecase-iosarm64-0.9.1.klib",
          "size": 4746,
          "sha512": "d74186e439b59092dc508f3797d2b1b51c3bd057fcf94f57f0ebc90371d946344f5d5b179c3eafa4e281682642ce43c41bc8fdd8e4bf37f3404e40363658034d",
          "sha256": "0ff6c58489094cdd907d07e1f75259e8c5c379d5fa5b4146a6393bdd0bc0681a",
          "sha1": "b8172fe0547a7fdb06689cd316adf3017ead4520",
          "md5": "6f49c9cd8c1a6797c8e71896b78c4974"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-iosarm64-0.9.1-metadata.jar",
          "url": "coupons-usecase-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "5d53489a4e431617831fcc09ea181feb643d200c7193f171ad1d2772dff7b10830db27bb306088c3dd2b56f0be14a48ec8a9b84e6b0b3aefefb85fe2675865af",
          "sha256": "438802685861d01fa6c7e67c2970b1628bc244f5e4ff992a2ef5e514f5360a2a",
          "sha1": "09f35b50ae9c77283da5816e9a26df6f710218b9",
          "md5": "5d084c45d30096fa026dc6265eb5282a"
        }
      ]
    }
  ]
}
