{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api-config/0.7.0/sdk-api-config-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api-config",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config-environment",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-iosArm64Main-0.7.0.klib",
          "url": "sdk-api-config-iosarm64-0.7.0.klib",
          "size": 39046,
          "sha512": "35d4e3e0c0b2ff7f76f8a6e448460e9836d8db75fbb23fc536679c4e159175fdc4d8b83a56d7f26cc1f22a1919514e2d2dcae9fdf5432fb10dfe64ff6f76561c",
          "sha256": "c3ed9209a122baf39920e4ce51b4dc2f53f744cde718cfd55ccdec8e95f84c34",
          "sha1": "70e0d85f299ee968a9e740a3092a7e33bbee36b8",
          "md5": "acc130d0a097da7a1647c68ba932fa3e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config-environment",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-iosarm64-0.7.0-metadata.jar",
          "url": "sdk-api-config-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "ca49bbb06deae571fe3f3bb357d42110d0319b5f4573f066d05cceee15974421f8e9333390e6f6c88ab28bbd0b4afc7e06f428479331e0607a7d0d6d121534ae",
          "sha256": "adca7e864f6039d90faa35bafdf406c122997b17209244bfd1fc5f8f6d7d4922",
          "sha1": "8e8678f00ba63f4e7bdbb23b5415ee7493d37cf5",
          "md5": "6c88c33dc3524d5773f828d76d51a794"
        }
      ]
    }
  ]
}
