{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-permission/0.8.0/core-permission-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "core-permission",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-iosSimulatorArm64Main-0.8.0.klib",
          "url": "core-permission-iossimulatorarm64-0.8.0.klib",
          "size": 33882,
          "sha512": "45d62bec3fb37142769737865f71552de053d71949faa3a80997a53f1e5ef82e9b857a67e817aa69a6f0a07f9a27e8c22c9d159df37009d204415b94adb880b3",
          "sha256": "93214f7176076cc698db07df7952b253f9bae9d02e8a9f055eb475a5e5a45f26",
          "sha1": "d1ed0d0e7d62644b4cb6ae942c435e206771b637",
          "md5": "fb8307083b49fc70714bfb5a81461f25"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-permission-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "core-permission-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 3162,
          "sha512": "696aefa29d63c89b915cdfc9555f035edab7fccd366a1674103b3b3eaf65be45aba80f50be6d0324f21a110cf94095257438945f6658cdeed82c689752b25926",
          "sha256": "e48d4872a817b65134e8ff6d0fb3c02bb09dca18e9c3cf962a5f126f841f4cf1",
          "sha1": "03c522650542a0cb3580042f415558ade41e0f95",
          "md5": "a07241756a6e64466751fb1b5696be87"
        }
      ]
    }
  ]
}
