{
  "formatVersion": "1.1",
  "component": {
    "url": "../../locations-usecase/0.8.0/locations-usecase-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "locations-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "locations-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "locations-usecase-iosArm64Main-0.8.0.klib",
          "url": "locations-usecase-iosarm64-0.8.0.klib",
          "size": 4774,
          "sha512": "7b6be1183222afff07147b2a93ef28fb267f840579437d84ccf749f761f7dbb3a0a5d58ba8b66c55e33d0c6a608e3c0d61bee015ab3ca1a757f9e2449c0b966c",
          "sha256": "339b0327e2b851c4fdc87604ab976e59728be6a6e6eefc06da7350037d4d08cf",
          "sha1": "f9b37920d58f663d03df8ba45daf8b3e402aedcd",
          "md5": "4186fd03ac31ca3421af4e36aef3e368"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "locations-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "locations-usecase-iosarm64-0.8.0-metadata.jar",
          "url": "locations-usecase-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "ec26e36f6b2c8329475d8762144f14915e7ee27c447818530713e1b57a0256829f8c6a3149a1456de15cc1bc0d6f8a7c55936463cb2ba6672395447ab6a712d2",
          "sha256": "b34a7e5fa23bdcaa570915a45a4c870a87ac999e77bcae0981e3bf4b6cf28375",
          "sha1": "cee45b0ee90286c757cb1844ce987e6ba761af52",
          "md5": "f65dfbe9b420f706ba392266fa7dd83d"
        }
      ]
    }
  ]
}
