{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "stripe-payments-usecase",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-domain",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-data",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "stripe-payments-usecase-metadata-0.2.2.jar",
          "url": "stripe-payments-usecase-0.2.2.jar",
          "size": 2536,
          "sha512": "dc14be82319ccfa7e3b7698dd0bf1d44be5e63b115c6a15c5a021c5be32ae9e2be0868b8e0de14b36033082cd0ae712cc11859e5aa509979db44713f99c8cf22",
          "sha256": "f2d883871f00bb4a28586a7bdea7675c77116599cba7a95ef3297691d0024a63",
          "sha1": "0d4b0c560d5fe861654c4608c12466b6b39f90f0",
          "md5": "e22356bc330ce724d35e372752c298c3"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../stripe-payments-usecase-android/0.2.2/stripe-payments-usecase-android-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "stripe-payments-usecase-android",
        "version": "0.2.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../stripe-payments-usecase-android/0.2.2/stripe-payments-usecase-android-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "stripe-payments-usecase-android",
        "version": "0.2.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stripe-payments-usecase-iosarm64/0.2.2/stripe-payments-usecase-iosarm64-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "stripe-payments-usecase-iosarm64",
        "version": "0.2.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stripe-payments-usecase-iosarm64/0.2.2/stripe-payments-usecase-iosarm64-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "stripe-payments-usecase-iosarm64",
        "version": "0.2.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stripe-payments-usecase-iossimulatorarm64/0.2.2/stripe-payments-usecase-iossimulatorarm64-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "stripe-payments-usecase-iossimulatorarm64",
        "version": "0.2.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stripe-payments-usecase-iossimulatorarm64/0.2.2/stripe-payments-usecase-iossimulatorarm64-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "stripe-payments-usecase-iossimulatorarm64",
        "version": "0.2.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stripe-payments-usecase-iosx64/0.2.2/stripe-payments-usecase-iosx64-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "stripe-payments-usecase-iosx64",
        "version": "0.2.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../stripe-payments-usecase-iosx64/0.2.2/stripe-payments-usecase-iosx64-0.2.2.module",
        "group": "com.mozio.mobile",
        "module": "stripe-payments-usecase-iosx64",
        "version": "0.2.2"
      }
    }
  ]
}
