{
  "formatVersion": "1.1",
  "component": {
    "url": "../../local-storage-data/0.7.0/local-storage-data-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "local-storage-data",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosArm64Main-0.7.0.klib",
          "url": "local-storage-data-iosarm64-0.7.0.klib",
          "size": 8748,
          "sha512": "ea5535a1cac0d72c6ce80c52cf58e40f4ea54bf76651b732619fc816df504454354e9e3727065dc700bca3beb9862cee576cc470e927cf2d8284d8d838f8573c",
          "sha256": "60ef442db8f04a5fe20cdb7c0fc1dc89cbac0608b2bcfd03d3ed51f4a57e5264",
          "sha1": "7e4d7f0260683e1ac74841bd650ff8bd6285a313",
          "md5": "9cecc5431e8b59fbed270aa7f489eb60"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosarm64-0.7.0-metadata.jar",
          "url": "local-storage-data-iosarm64-0.7.0-metadata.jar",
          "size": 2476,
          "sha512": "8ff5cea28fa807bc1fbb352e90caefa1f8aac8aaf3b00e86570ae5ded76050f454a0608b238f278581471104d5b9ba3cac453b460ba2e6e750dd8debb59b2d8a",
          "sha256": "1888dde40baecc41e1d5986b1fef8354846f7fcca119fea3635bd904b181d6ae",
          "sha1": "2e3e6c62137f878068e1fc94c96432b1d69179f8",
          "md5": "3d72836453ab6c3a0bd80d2d6cea2e16"
        }
      ]
    }
  ]
}
