{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api-config-environment/0.8.0/sdk-api-config-environment-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api-config-environment",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-environment-iosX64Main-0.8.0.klib",
          "url": "sdk-api-config-environment-iosx64-0.8.0.klib",
          "size": 6707,
          "sha512": "5fa22b3e805fe500c1994ea6e8c7c6d3a7a8a8659979ebfd42c0aea847b8a86e4cecac4eb89c9d79b6e7455f65c384e1559d9ed0288329879e28498b3587b5ae",
          "sha256": "78ad0bf25cb48a9286f291301e3ff3ae8c13b02cf40f857d2f81512ea98f1c30",
          "sha1": "f6377a362802336b32e5f7834ca248b127a54041",
          "md5": "4282cfc9d84baf9ebb8979a0e64a486a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-environment-iosx64-0.8.0-metadata.jar",
          "url": "sdk-api-config-environment-iosx64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "2c3796bea6548f2c7b793fb9c000a2b6211afd6f7896630f8d7ea9f845ef7501bc89608cf1128351b3f0522dfab46397678b3a378f956e98cb38a9e4e8e35f13",
          "sha256": "5ab0f29d5a5d554c9b6ac0fb7fae9befb854f07bc18b77477cf476e4af51304c",
          "sha1": "e4fc105cc92d4946bf05285fc9036deb036b623f",
          "md5": "c1950288ace44940a537a4ccc608ea0b"
        }
      ]
    }
  ]
}
