{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coupons-domain/0.7.1/coupons-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "coupons-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-domain-iosX64Main-0.7.1.klib",
          "url": "coupons-domain-iosx64-0.7.1.klib",
          "size": 24114,
          "sha512": "d0438e5eed17217833c7392ec2b65cdcc652b556bb36727383e2f40f5123bc208ea6515958028f715b33d84986bfc669deecbf39b78741b1cba3df451d786cdc",
          "sha256": "5113168218319e97f55f7810c14fb900733190ecb7bfbc37d395ce0bc8053d35",
          "sha1": "4eb7ee4e8b370a3b77573d985d68a782c8ede071",
          "md5": "cf533ed8adece73fed99f05b7aa76ae9"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-domain-iosx64-0.7.1-metadata.jar",
          "url": "coupons-domain-iosx64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "afcd1d74fa578b07c368d39abb34181b2b7b297dd7404f116f279000af5d4f97dca596298cd82000b90a392207e800a988b15c9c68849fd26c4cfab875d8bc73",
          "sha256": "16edc5a21b1d638106b7a332ca0af6dc60b7cd859cd785ba4dcc435fa82a5b69",
          "sha1": "2d355839355e7139364fdb60fcf934a97a99e7e1",
          "md5": "b1780778406196bf57672377a94687c7"
        }
      ]
    }
  ]
}
