{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-domain/0.7.1/user-profile-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-domain-iosArm64Main-0.7.1.klib",
          "url": "user-profile-domain-iosarm64-0.7.1.klib",
          "size": 25132,
          "sha512": "3363813b5960b76f8012ea00cbb4ea47af0d39ab296767d54aee2a91247e019b5a7874389647489e992e4fc062afa5ea3c27be9c30f58ec43314b8d125a095fe",
          "sha256": "1050bb35dae5a331d9f2e522d7eacb1f78ea3060454bb9d55afe5bd8d48db9d9",
          "sha1": "40abce4bd7a0054ab3caafcb752196f72c7cfe86",
          "md5": "c0437a87821ad12ceaede145639e8287"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-domain-iosarm64-0.7.1-metadata.jar",
          "url": "user-profile-domain-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "b9d0fa8048508c9488d93baf3d4146aa5e4ccb45f63ec630e4e4b2abde9b6710de98c65c9c7242eed4a455807858715664338f2b5e941111055b534615ab53c9",
          "sha256": "7dc756bc2e62d9f417d8cbbd22fb051220e2b54dcc53613ed98a6df56b150674",
          "sha1": "0285474fa0edaa46d7749d6c993d4da9ffb0e859",
          "md5": "2f50cf23a5af38d861e1cdc661f8c7c6"
        }
      ]
    }
  ]
}
