{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "searched-locations-history-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-domain-metadata-0.7.1.jar",
          "url": "searched-locations-history-domain-0.7.1.jar",
          "size": 6967,
          "sha512": "c74c690f16e90001f8dad5f1d0e6945b69ee1705571af1dbdea198bae4daa915f1e2236d15002d96bbf912c1ca1ff168c0298197e1a06b1f2bd1d77e67eb8c94",
          "sha256": "7203d0d459cbee6a7f56a0d6da9839a78665df697392086628fb0a80d2d1b2e2",
          "sha1": "b7d100f8bd48dab56164cd039a431729b004b790",
          "md5": "c798736365c8784a757dae994fe63f9c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-android/0.7.1/searched-locations-history-domain-android-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-android",
        "version": "0.7.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-android/0.7.1/searched-locations-history-domain-android-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-android",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-iosarm64/0.7.1/searched-locations-history-domain-iosarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-iosarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-iosarm64/0.7.1/searched-locations-history-domain-iosarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-iosarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-iossimulatorarm64/0.7.1/searched-locations-history-domain-iossimulatorarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-iossimulatorarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-iossimulatorarm64/0.7.1/searched-locations-history-domain-iossimulatorarm64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-iossimulatorarm64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-iosx64/0.7.1/searched-locations-history-domain-iosx64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-iosx64",
        "version": "0.7.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../searched-locations-history-domain-iosx64/0.7.1/searched-locations-history-domain-iosx64-0.7.1.module",
        "group": "com.mozio.mobile",
        "module": "searched-locations-history-domain-iosx64",
        "version": "0.7.1"
      }
    }
  ]
}
