{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-analytics/0.8.0/sdk-analytics-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-analytics",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-analytics-iosArm64Main-0.8.0.klib",
          "url": "sdk-analytics-iosarm64-0.8.0.klib",
          "size": 27378,
          "sha512": "553aff31c3ad24e2dc1c54733ebe3e5e9ddf10d306244385ffe82d6758dde2ccb37b3c80a86b5d7879b070f8630e6cbbcc9d5873589ab24064343bd0cb65be97",
          "sha256": "4e47f87b17d820525b2c6cc8e2c12e7d1c7b6aa63a87395cdd1f3a240f50fa51",
          "sha1": "8d2d527b9c7510d1dd0863f535a9d72ad9a9d8f7",
          "md5": "32721b138bff29895a3e4449e0ac9345"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-analytics-iosarm64-0.8.0-metadata.jar",
          "url": "sdk-analytics-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "bd8e5a17289bbb5b60654b83c697b53d17668bfc123f9575d85df49a5fb22aff8beb99a43f3a860636210b00a8e314a1c3fcfc0ef069416e89e717666cf6de77",
          "sha256": "11c4a12fc5b9b519164dde52f3f8b649ce4a17eb5480d8e0f47f6070ed50e9eb",
          "sha1": "47568af3d80a6447aa095e858712de66f68df540",
          "md5": "06c9f67c6ec3ca1453beb75b6b1265a2"
        }
      ]
    }
  ]
}
