{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservations-domain/0.8.0/reservations-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "reservations-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-domain-iosArm64Main-0.8.0.klib",
          "url": "reservations-domain-iosarm64-0.8.0.klib",
          "size": 23002,
          "sha512": "50c470af69b963d63bbed8cd2d068bf7adf97b727fcc4bccd44395f95faec2361a67b9ba628bcda815aab2d2d27896c831985236b6602ee75cb70326b48fe602",
          "sha256": "61f28b994842dd7ff513cfa158610d42018b0de6ec4d8c39741e2f8b4ea845e3",
          "sha1": "2f3ec7f152081b8f204af23c5c43b1b44ca72288",
          "md5": "6f1e7192efc741779b7dc36d28c9ec1c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-domain-iosarm64-0.8.0-metadata.jar",
          "url": "reservations-domain-iosarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "54b61dff652887a2c2350a0e61522904cbf2542af445ce7e561b3ed567c042e7bb185c691aa59ddf9e715aad17f490e7936ad731169420ec80a374c9859663ca",
          "sha256": "cb7b58defaa2e689ff983a06e3c5e561f9ea08d7c98eefa5a4b12ef225ad745b",
          "sha1": "f79e370ef2981aeee0aa449f3a66c9cdf2e1ecb9",
          "md5": "1e732b3c737d1b8a3e67df382feafc0b"
        }
      ]
    }
  ]
}
