{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-location-usecase/0.7.0/user-location-usecase-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "user-location-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-location-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-usecase-iosArm64Main-0.7.0.klib",
          "url": "user-location-usecase-iosarm64-0.7.0.klib",
          "size": 4953,
          "sha512": "819094762a606ac313a5085aa95d9eb92458521aa9839f2b51a9f47b76bc6c383d8f4993443eb5651e30782e8dbb8708d4cabfe2779ddf8f20e4fc853876c008",
          "sha256": "7334b2fa4af2f280b263b5d15e31633b4d3f63d65c5966d265b7652ffbc01a2b",
          "sha1": "f511938267478237a5f652e6c9d899cd9aeaec93",
          "md5": "972773b97d62a60d5bc5775c6aa219f6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-location-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "user-location-usecase-iosarm64-0.7.0-metadata.jar",
          "url": "user-location-usecase-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "f731445f376d77f39e47df0cfa7a4a115923b31d20d235d54c8976eff75490763f95b147867e5b5efc15046418678de928c38a2e75c3d70e01f1244bb88777fb",
          "sha256": "33402798a63ecfabe181cf74f44ab375a87965d0ca57ba2ba14d0524955a56f5",
          "sha1": "81f1aaf63ca5bba7ea5f7eefde31629490ccab4a",
          "md5": "8cee89dd2b6b3345c0d4cb339fbbf4e7"
        }
      ]
    }
  ]
}
