{
  "formatVersion": "1.1",
  "component": {
    "url": "../../search-domain/0.9.0/search-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "search-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-iosArm64Main-0.9.0.klib",
          "url": "search-domain-iosarm64-0.9.0.klib",
          "size": 56529,
          "sha512": "ec000b87a22b09d01e1e19645a238b61925086e6da7111b2c60e8c1c232f80d01e9e5911087e8fd3459e30ecb8d38ca591b8083712391a19c707773dad11bd8a",
          "sha256": "315f1ef5a46132c8b1742acf845ea96d39f388e56baba411c616a2f6b0149316",
          "sha1": "f0ed8a6c6073b2d2ee7a9a496681496d4694ee5a",
          "md5": "e6099598bc7c8803a78994f3614daae7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-iosarm64-0.9.0-metadata.jar",
          "url": "search-domain-iosarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "43c36a93a3a34ec7404d8ca861f866941d6127953e0fc38733b7d2fb0b04d749cea3be001edacf78677eecc16f3b814be99e2e3dcfcf6e1ba56b2b63d9580fb6",
          "sha256": "621f8baf354ca7007e84cf92f991eeec7e08964d7581cc494ad1c097b2ad6360",
          "sha1": "7f87e63b7a1b730f180313e8fa54ae5cb689f091",
          "md5": "b535fcd7731ba8f30d3f11a49c8dbd03"
        }
      ]
    }
  ]
}
