{
  "formatVersion": "1.1",
  "component": {
    "url": "../../searched-locations-history-domain/0.7.1/searched-locations-history-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "searched-locations-history-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-domain-iosSimulatorArm64Main-0.7.1.klib",
          "url": "searched-locations-history-domain-iossimulatorarm64-0.7.1.klib",
          "size": 31703,
          "sha512": "2b4db63d1756440a5cdf051ed0dd89b90a73978e4a01e55fb8186bc4a547eb6e0dcb6addceb2d78567575c085df5298f140be71a531e740ef10bf4e3a08fcdaf",
          "sha256": "11bae7eb890eaf07ab49590c3edc22af4f8e6ef059ade2a9f9d854ce3b884b61",
          "sha1": "a838e84bcd1619c9625bdf749a3e7a90d9853f35",
          "md5": "80dbb85f6a924b5ce89c82dafdc29118"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "searched-locations-history-domain-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "searched-locations-history-domain-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "186e4d1a741d3c3e801156cc96b7465152b61d798879a8037c00b5fcaa69e77cddfd3d0a7499ace5e2c5d4d0a1cf7e7e0fbe066204e9142f34197cb3092dacf2",
          "sha256": "3a7d56682c52d1b891953c1b71bc95fec42e5e422058758254ba735c00ccd228",
          "sha1": "3d56f2e54b8753e348bac80081282fc920999748",
          "md5": "94b40bdafb947f98152affa6f29ff2d1"
        }
      ]
    }
  ]
}
