{
  "formatVersion": "1.1",
  "component": {
    "url": "../../locations-data/0.7.1/locations-data-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "locations-data",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-data-iosArm64Main-0.7.1.klib",
          "url": "locations-data-iosarm64-0.7.1.klib",
          "size": 66603,
          "sha512": "b891f12d889392ef2cec29857b545fb9dd3fab26c53eaa6df9fd9dde3ff98850d451efd9f2ed0de03d6d9134680daf129b04c5b5ca662e856cc2705b18cfc9ec",
          "sha256": "b3a808129de73bb7de34c6a3ef2b30850583d2380d61f3c02ebe228b71ba8f37",
          "sha1": "35c329fd8ce0dc8625a0a9a42af6c4d7375c3796",
          "md5": "074b74837f0ce2acaaa40feac9e1ff0d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-data-iosarm64-0.7.1-metadata.jar",
          "url": "locations-data-iosarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "7a731e984fcb0cb1f7cc6b97efaf7e71d18bc4daf07b23260278344a7c33454c50cd98e4ef222d048c90894d1a4b7acfba99f1f779a572ed0a700f5680e96f3e",
          "sha256": "d07366f2632fa380206fa9c39a4fd574332418c705a776e8f730b57e3092c25a",
          "sha1": "c6530ce962482b3aae88993eb23a45e03af45455",
          "md5": "6491ba272e647d15deeaba4d62af38ee"
        }
      ]
    }
  ]
}
