{
  "formatVersion": "1.1",
  "component": {
    "url": "../../local-storage-data/0.7.1/local-storage-data-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "local-storage-data",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosSimulatorArm64Main-0.7.1.klib",
          "url": "local-storage-data-iossimulatorarm64-0.7.1.klib",
          "size": 8814,
          "sha512": "1ccd02881379965bd78cf2b3a63f122da90082c4d8a9c97dd120358c75f2b21e459327a9b3468f7ca5be66c710d78ff344cd5956a44a5240f856d95b89e69a4b",
          "sha256": "9d3a68f2cd9630f638f6e7082ea82fa4ea0b882f7e78d3feab72e375889f320a",
          "sha1": "643e3590a70188b62a02ce9fc1c210b1073f7393",
          "md5": "99d58ea7939ed6503179ce84deea4a65"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "local-storage-data-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 2476,
          "sha512": "41fb621bfb94421e60218dc6501dc0db5da2db56611674762634686a451fa51ca929b1e25516e8502c6756e8587ad91d1c7f01994eb811345a00932195e5a596",
          "sha256": "42e132492135dac220bc54a70037755b7e01fef99c2eb4ab3ec0208fb9bb43dc",
          "sha1": "a3b8d6a5cbbc537bf2efaafafaf20848ca7ecba5",
          "md5": "042d9f58c138984bfb3e2a7b1aea0c3e"
        }
      ]
    }
  ]
}
