{
  "formatVersion": "1.1",
  "component": {
    "url": "../../locations-domain/0.7.1/locations-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "locations-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosX64Main-0.7.1.klib",
          "url": "locations-domain-iosx64-0.7.1.klib",
          "size": 34182,
          "sha512": "1c7291d9da013e7a7fd67cc8f8c0d3c1420fb35c894aedf31b5953fef4c0ec5f4eb8e8d0b7d3748500fe47b5be08f2df0d1999e805e28a6b73e090868ab72411",
          "sha256": "a3dc4e07278056d012471b759481e2dcac441531369800ee22c50a395795c4dd",
          "sha1": "1737784c378131fb8200d6b9c7d9fa40d622081e",
          "md5": "c6724c3f0d6b39c00f1759616b27076d"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosx64-0.7.1-metadata.jar",
          "url": "locations-domain-iosx64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "77b4b11150f2f4839e0becfedccf772d71e7fa5e923a1d41012ca62a5353a4d0d984dbe6ba186a7b72b17f6b0ff0280b493b9be5163c63fca591e3251243d1f0",
          "sha256": "45efbde189b93f4b12069e19a7099551f612e41f2a5d3ee79e44b7f0ebd1d908",
          "sha1": "f87c244183eca71d8facd5032ed166aa1c6483e3",
          "md5": "df2d28be52cd9cb507f6c2920dcdb83c"
        }
      ]
    }
  ]
}
