{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservations-usecase/0.8.0/reservations-usecase-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "reservations-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservations-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-usecase-release.aar",
          "url": "reservations-usecase-android-0.8.0.aar",
          "size": 2251,
          "sha512": "ff89526e32883c6804052742c6bf09ee01b8ad1bcff60b601f68b73472bd7f566d60c910522164e0b0ed843165f71f558cab23126805deb9ee44dd9237fc689e",
          "sha256": "672d4ced77aefecd489a4377272b03384ca20fbe35f9a208097c0977594a55f4",
          "sha1": "f853bc7cece47e17c815f0119f7993f8ce59311f",
          "md5": "4805b0beb8a18806d06fd64df752dcd5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservations-domain",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-data",
          "version": {
            "requires": "0.8.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "reservations-usecase-release.aar",
          "url": "reservations-usecase-android-0.8.0.aar",
          "size": 2251,
          "sha512": "ff89526e32883c6804052742c6bf09ee01b8ad1bcff60b601f68b73472bd7f566d60c910522164e0b0ed843165f71f558cab23126805deb9ee44dd9237fc689e",
          "sha256": "672d4ced77aefecd489a4377272b03384ca20fbe35f9a208097c0977594a55f4",
          "sha1": "f853bc7cece47e17c815f0119f7993f8ce59311f",
          "md5": "4805b0beb8a18806d06fd64df752dcd5"
        }
      ]
    }
  ]
}
