{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-usecase/0.7.0/authentication-usecase-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "authentication-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iosX64Main-0.7.0.klib",
          "url": "authentication-usecase-iosx64-0.7.0.klib",
          "size": 4995,
          "sha512": "9a5569e7f9e72f5f282252d1d0494d9a9aafc7dad84f172872b9bf1a6371ddd25aaded95d316a0d405576f3c2f5503405cf2b5f34a9668ae9ad2f605236516c8",
          "sha256": "68f12af8966a8b218c04726045128ee24d77ebb0bb30d17d032d6b3982c9e1d5",
          "sha1": "3f6b76d1398f2155081466f9615ecf4234cd9dd4",
          "md5": "ba71d1619531034b73a3a5eac10c410e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iosx64-0.7.0-metadata.jar",
          "url": "authentication-usecase-iosx64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "074a7ccc623a0a02c3355970e5b8fcf205eb99e92fbab2711ddc43392c3aabe165cc7b4e68cdd92e2f0c77e188c1d827d5393c38bb128f734c28a0776550c535",
          "sha256": "1a298ceaacd6da1ffd00419b5f62c156b6df96b383fcee2b909fe80c7175992f",
          "sha1": "fe9e96c6b36e9efe7b14fbff0e5358a4eba2da2b",
          "md5": "940fb3b9c74843940c0e3bfcd7c0f289"
        }
      ]
    }
  ]
}
