{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "pricing-data",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-data-metadata-0.8.0.jar",
          "url": "pricing-data-0.8.0.jar",
          "size": 12435,
          "sha512": "6626ea389b220b487b4bb51d2f1c823bf37728f3ba673cb2957403caa0604db13d7459219c33ec0963f10fe16a42d6bbf6f7aac9036ead08ed3aeaea85616027",
          "sha256": "53a511f211de7495556c18c29c51df80d1a26965d21f0960ecc84e1eda7e411f",
          "sha1": "3520622ce6a0761106c6a588f63efaf6f1ceadd2",
          "md5": "775910551d695d2d535ba84cb5537562"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../pricing-data-android/0.8.0/pricing-data-android-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-data-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../pricing-data-android/0.8.0/pricing-data-android-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-data-android",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-data-iosarm64/0.8.0/pricing-data-iosarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-data-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-data-iosarm64/0.8.0/pricing-data-iosarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-data-iosarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-data-iossimulatorarm64/0.8.0/pricing-data-iossimulatorarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-data-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-data-iossimulatorarm64/0.8.0/pricing-data-iossimulatorarm64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-data-iossimulatorarm64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-data-iosx64/0.8.0/pricing-data-iosx64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-data-iosx64",
        "version": "0.8.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../pricing-data-iosx64/0.8.0/pricing-data-iosx64-0.8.0.module",
        "group": "com.mozio.mobile",
        "module": "pricing-data-iosx64",
        "version": "0.8.0"
      }
    }
  ]
}
