{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-domain/0.9.0/authentication-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "authentication-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-domain-iosSimulatorArm64Main-0.9.0.klib",
          "url": "authentication-domain-iossimulatorarm64-0.9.0.klib",
          "size": 44194,
          "sha512": "d7f6ff177d9c89f07fb2a21c66a13558613985006232971cf2dbf701650583abba202c0c007dfdd67892aac89a65c4c40a61ed3d2f43aa0029c15d97d02d8707",
          "sha256": "a3f98b8d195b38baf99e32d9e439800c071bb3e79f7c257a686e022ccfb2d532",
          "sha1": "381beb70f2d41de21f69d69e8550a258ff06161d",
          "md5": "b8e133a2a20929555653a5235241aa81"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-domain-iossimulatorarm64-0.9.0-metadata.jar",
          "url": "authentication-domain-iossimulatorarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "dcfaa8fcf2a961a6dbc3cda9e8b90420fff127e3911693f643aebcbdebc2849c6c193a0eabc8bc279e77ac8aa5c1ea234f1da4af5d040903f930298dc97af46a",
          "sha256": "6bb4316f23c809d71ce0af82a61f08835f92c615e6c10a4f6cb25a09cec09e87",
          "sha1": "41f6768fa3f98b9776870548db6dbebdc228ca6b",
          "md5": "ea63e4a9a950a21c1100ebe481870d9c"
        }
      ]
    }
  ]
}
