{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservation-details-usecase/0.9.0/reservation-details-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "reservation-details-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservation-details-usecase-iosX64Main-0.9.0.klib",
          "url": "reservation-details-usecase-iosx64-0.9.0.klib",
          "size": 4939,
          "sha512": "aa95f88418161960142a15ed228fbe56505c8da2076810e08606d6fb29bc2c2eadb4d2a656619ab97eb115d64bb7724eac0f20311918eb52dda7cb35a0ce5e29",
          "sha256": "b8d0f1f5381244dc257248a28081e46c642c7d5c406146151ed11c411bbc9c30",
          "sha1": "101cc3b85971e6319671526a7aa9f2ff495f13d2",
          "md5": "5843257febfd16a22abde957eccde4ec"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservation-details-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservation-details-usecase-iosx64-0.9.0-metadata.jar",
          "url": "reservation-details-usecase-iosx64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "afb8e5bcb0d55b7b7c5e8b3951fc8ae5bc640f02c6206ece930611210d3e125ea624bb12ed2c13b6599a0d8f01f44e750f10e541251e9d5701ce6b62c03623e2",
          "sha256": "03a65bd445274e9b3280b396b59ed21c9d3ab9e480143eb9129335d9c115f8ba",
          "sha1": "68f17ff31e77c7740d04c9063075da09bac84beb",
          "md5": "d81a3606c8404e7e7cfa5e74454bc90a"
        }
      ]
    }
  ]
}
