{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-usecase/0.9.1/authentication-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "authentication-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iosSimulatorArm64Main-0.9.1.klib",
          "url": "authentication-usecase-iossimulatorarm64-0.9.1.klib",
          "size": 4923,
          "sha512": "5b1ebef0ba5b5e52a83423d605e01d609c33e7d20a5c52d70d1325456b92b71b7f104311652f6ef84018165b7cc9879bc0aab8be205f8798a8e7473a5aa515e6",
          "sha256": "ce84202e532d596cf3e098df28ddc7ce79a270057a766ef26d1c209b0359601b",
          "sha1": "93feb9357505cbf20e124f64bdc53cfbef37bd5b",
          "md5": "87db07211414af366f30642ef8774bee"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "authentication-usecase-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "32ac4e94220da0cb1185a8cc4b70d0557eeb044a8f0fe45b74166b2bebae33c91ed96c232bb5153e19c6c07bc5fc5d814be4d62aac081074f67ffb08d0d1fdb1",
          "sha256": "f28367c6796dc4b30435187671ef34e97c89af3516bf1b97ec4e4b97f585abcb",
          "sha1": "b02ee7fb27d5165009ceb26896b51184d40c6a1b",
          "md5": "77eb279e44210c9ae0c8d73e34a13472"
        }
      ]
    }
  ]
}
