{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile.android",
    "module": "myaccount-ui",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "myaccount-ui-0.5.0.aar",
          "url": "myaccount-ui-0.5.0.aar",
          "size": 130838,
          "sha512": "fe790ace8517a751f8d199400f55f65c62c1a79edba3235e3c711a8d6111a4f366008b337cb5379f1df3b8b20223c3a9bbdcdd90d74beb4a9bcd839ee7ee2dac",
          "sha256": "acae5fafd8b657bb34c59770a9bf0e3b14ecefb16b1531936b55f282c6f5b32b",
          "sha1": "81ee1f775cdeda165154e6119edaf9f4ecee2b92",
          "md5": "d738d74e2412e0b84c43c98c572bbe8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "core-ui",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "authentication-ui",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "country-phone-ui",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-di",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "myaccount-ui-0.5.0.aar",
          "url": "myaccount-ui-0.5.0.aar",
          "size": 130838,
          "sha512": "fe790ace8517a751f8d199400f55f65c62c1a79edba3235e3c711a8d6111a4f366008b337cb5379f1df3b8b20223c3a9bbdcdd90d74beb4a9bcd839ee7ee2dac",
          "sha256": "acae5fafd8b657bb34c59770a9bf0e3b14ecefb16b1531936b55f282c6f5b32b",
          "sha1": "81ee1f775cdeda165154e6119edaf9f4ecee2b92",
          "md5": "d738d74e2412e0b84c43c98c572bbe8c"
        }
      ]
    }
  ]
}
