{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile.android",
    "module": "sdk-ui-config",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-config-0.4.0.aar",
          "url": "sdk-ui-config-0.4.0.aar",
          "size": 8537,
          "sha512": "467fc95eeb46dc3fcc72540d71125683e9dac67b8850489d5f26b141a9f27fab9e59866757641d4bb211ef301cbd45dcad51e477c728031a8880cbba20b334d1",
          "sha256": "f6a76226575087ee3233aa1b9c4b17088d7367c21864d83f3fddb2b30180d7fe",
          "sha1": "4f7493797f0479da9c17d8312ba229ea1ce81530",
          "md5": "f408ca6651afea552d14e517c3e8b283"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile.android",
          "module": "core-ui",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.19.1"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-config-0.4.0.aar",
          "url": "sdk-ui-config-0.4.0.aar",
          "size": 8537,
          "sha512": "467fc95eeb46dc3fcc72540d71125683e9dac67b8850489d5f26b141a9f27fab9e59866757641d4bb211ef301cbd45dcad51e477c728031a8880cbba20b334d1",
          "sha256": "f6a76226575087ee3233aa1b9c4b17088d7367c21864d83f3fddb2b30180d7fe",
          "sha1": "4f7493797f0479da9c17d8312ba229ea1ce81530",
          "md5": "f408ca6651afea552d14e517c3e8b283"
        }
      ]
    }
  ]
}
