{
  "formatVersion": "1.1",
  "component": {
    "url": "../../search-domain/0.8.0/search-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "search-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-iosSimulatorArm64Main-0.8.0.klib",
          "url": "search-domain-iossimulatorarm64-0.8.0.klib",
          "size": 56594,
          "sha512": "b778ec9e204a4f9c7735aa06095c867c24602735b9cd253d496bf7614d51502d7c2fe131be854b2020b8888d8f6830eae620b50981658aed371196a16ebf55c1",
          "sha256": "92bf9751f8c405188273a6c4b2bd8e9c116ac2aee661745845141f1057784fe5",
          "sha1": "926b1c4f73e88398d461005c047483d989c6c7a8",
          "md5": "91ecb540aae17360325015d38bc675c3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "search-domain-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "search-domain-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "ece9dd87ca1aaf3bf67af35939572c63635ed68b3dd67a1ccde2379c617ba3a67ee431635df348671e7982ab639c9ef0275e8e7f1e29c5ba07452a5a5ca531df",
          "sha256": "9f0400620a772ddd43cdcb915451ec4562b25ec206ea16ef0660cd0a9b761d42",
          "sha1": "b6d5f57af3a94118371a0284c6fa793511957559",
          "md5": "1d6c6eb1079ff43828cc856e8f0960c0"
        }
      ]
    }
  ]
}
