{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-di/0.9.1/sdk-di-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "sdk-di",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "sdk-di-iosSimulatorArm64Main-0.9.1.klib",
          "url": "sdk-di-iossimulatorarm64-0.9.1.klib",
          "size": 7310,
          "sha512": "c3fcc781928894f219a6e9bc26d775862bbefcccc89bcc25999d889980293379ff5f4b3031dd73180d653f103965a32b5aa592edc27edca4f0de5f4d19b81897",
          "sha256": "c5ad600a0ff081ce8e295affe8204386fb52f824bc05a285360ffddb9067292d",
          "sha1": "37eac6ce7b563a1dbd2cfaea27b18651e87b7989",
          "md5": "ceabb75a4d3b8c16ffa5f7c2161ec804"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "sdk-di-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "sdk-di-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "38c9db2b0c0c4eca4066972ba348e6761ec28e75b1673080b837404474b19ff8d9d4f2016e90d1fc474ec295b832e3dd123cf383c69a58b5b5c3b2eb739d05aa",
          "sha256": "52410a78c685cfb76397154976452cfabac3cdd734ce0bfcb68378fcc4eb8bb1",
          "sha1": "278b94d6fa6a03bde71c4d38d9ec68b924ca174c",
          "md5": "b43657a6d52a3a57510dd50f8926e7b0"
        }
      ]
    }
  ]
}
