{
  "formatVersion": "1.1",
  "component": {
    "url": "../../authentication-usecase/0.7.0/authentication-usecase-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "authentication-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iosArm64Main-0.7.0.klib",
          "url": "authentication-usecase-iosarm64-0.7.0.klib",
          "size": 5008,
          "sha512": "c75cbfe742367b75ff88309a9c6fe02a198bb8f8d31295367f5b4fd69370a6a9bff3153d4577e453407015564d85705a44f3ae244ba0de8c19557b15e4046e5c",
          "sha256": "ded9c0d65a8f813e4bcc62b7b457af91b8c3f84d825b8e61a39486f49dd009ec",
          "sha1": "85d6ebcee9171ac01ebc6a44bbaf9f847f38e5af",
          "md5": "558ac7b47fc728651e984cbd4f412904"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "authentication-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "authentication-usecase-iosarm64-0.7.0-metadata.jar",
          "url": "authentication-usecase-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "81610da07977475303e6d9b77f16dea8ae1409cadcdbd22206be5b10b07110c2dfe9882396356c0e23f3a3e1b578c72f8f3cd66d4bd3f5a1e3d8138ede31cb5d",
          "sha256": "935dd80866bbefaa26d8433dc67dd4ed1047a001a0b382d7578c188dafb25592",
          "sha1": "8fe7a16172a1a0099337ac8458b7dd9183f1b6c4",
          "md5": "aaed5badcaa0b791c22a3b12edd85e78"
        }
      ]
    }
  ]
}
