{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-domain/0.7.1/user-profile-domain-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-domain",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-domain-iosX64Main-0.7.1.klib",
          "url": "user-profile-domain-iosx64-0.7.1.klib",
          "size": 25119,
          "sha512": "46fb042a8f7444b70b2a05ecf8d898500bad4fb6c6295d8587bb486e366fb2fab5ac7a2db1c2c89a0a7ee4651f21b247c1899e5820068b058a76fe20ea22eca1",
          "sha256": "614ef5dc4719cccf7d2129ec7637a6ac69eda8b9f9092605620ea2626b59011c",
          "sha1": "84c0fa88cb88baf9b3a2839b0fa95bf1458d6a4f",
          "md5": "6c0d15418fa500f0b5cdca9692d8678c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-domain-iosx64-0.7.1-metadata.jar",
          "url": "user-profile-domain-iosx64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "b9d0fa8048508c9488d93baf3d4146aa5e4ccb45f63ec630e4e4b2abde9b6710de98c65c9c7242eed4a455807858715664338f2b5e941111055b534615ab53c9",
          "sha256": "7dc756bc2e62d9f417d8cbbd22fb051220e2b54dcc53613ed98a6df56b150674",
          "sha1": "0285474fa0edaa46d7749d6c993d4da9ffb0e859",
          "md5": "2f50cf23a5af38d861e1cdc661f8c7c6"
        }
      ]
    }
  ]
}
