{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coupons-usecase/0.7.0/coupons-usecase-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "coupons-usecase",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-iosArm64Main-0.7.0.klib",
          "url": "coupons-usecase-iosarm64-0.7.0.klib",
          "size": 4890,
          "sha512": "1d1878a19638fcf1b2d3bf141435b042ff29b98a080b2aafc82a6b10a8cf5bcf1ed7fddd850f10815e16bc83b74e31e6b5a19b0070b9a520449a8346845ba75d",
          "sha256": "505a61e959e0d9f74fcc936fe569c0606828c9f716f3bad14c3753ccc75e22c1",
          "sha1": "a98ec9b89a08dad0367e7dedc82b77d258c6aad5",
          "md5": "00171be30022cd9d356fb8ed5a4f63b0"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "coupons-domain",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-data",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "coupons-usecase-iosarm64-0.7.0-metadata.jar",
          "url": "coupons-usecase-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "677b6d61a37549b91908d5a1afc377f0cc19649167cec0df33153530743441aebb73f8acec4a8a00b45db8377c228f0dbc623cafb6f98ccd4f29a647b12a7cf7",
          "sha256": "1551aeac126ba0bd04f3fdc9575da0086f9f2f2aef7316d4e4d0471429b43f0a",
          "sha1": "5ae026736ba26e8876d8365b41e3cfee50af7278",
          "md5": "d440f6643801a807095e21b25eff2a0e"
        }
      ]
    }
  ]
}
