{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-usecase/0.9.1/countries-info-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "countries-info-usecase-iosSimulatorArm64Main-0.9.1.klib",
          "url": "countries-info-usecase-iossimulatorarm64-0.9.1.klib",
          "size": 4812,
          "sha512": "9ea7722f1016c783a3aea78a11bfc1e4c2fc2e4974692b703d36cfacfb2ae47b113dae9ee24e41201caf0e4ea0ac7c4a966a40a4348f09d39e7cedc265467539",
          "sha256": "8a551852cd43d350eb9bf89122f685bef82313d46613cad3fdc84f1e43700877",
          "sha1": "87e58f415d9eaced000d0822000cba9a2231bf74",
          "md5": "dbda2e46f840c1ed3de858859f86f32c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "countries-info-usecase-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "countries-info-usecase-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "cd917218f33f181da9226760e0bd79099ab0fc0c33e606d099e4a391d7c43f7d4dcb24a9283a7a63c0b78f68202764912592e703a8184206ae7f2c6299e3b28f",
          "sha256": "1766ce8009afa621303abf46f87395d9d8bbff9eac3a1159df09f440a8965118",
          "sha1": "83ffde52c1fc0473f7c90550ce27e8cfe6c87f46",
          "md5": "03eda29349c4ae633ce3a2c7216b5af9"
        }
      ]
    }
  ]
}
