{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-analytics/0.7.1/sdk-analytics-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "sdk-analytics",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-analytics-iosSimulatorArm64Main-0.7.1.klib",
          "url": "sdk-analytics-iossimulatorarm64-0.7.1.klib",
          "size": 28393,
          "sha512": "a7ea94e5966fbc9d9a40e33182bdeef602506dbdb9fc3e857aba7971f94c7de49bfccb41e8984482e810b05b416ae7093ba23328f09f5cdc3e513afeef7c32d0",
          "sha256": "bfc23c540f3c58f781e11df0e4a9c3245b385e592f468ab90a2bd3f7903215ce",
          "sha1": "4bbf1bfffc10d09d89388d2c067844f7265ce2e7",
          "md5": "d90d4f8f3f8eed309bf5d923f5a411aa"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-analytics-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "sdk-analytics-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "8e4b8499eca78b0ee76c697a03dc295b76b9b446ce34c102b46a22b77412dcd6458abd5dff16ab929eb364213f8982c14ee1aa674d7e92232cefc2b66178661c",
          "sha256": "6d5032cb431d9446ee3c98e2c3334dc4f60375823d2857eb8c01cf0023f84e87",
          "sha1": "5924d1ac0ffbad6ba86df4f7af6fdec89ff5b33e",
          "md5": "fd5a5472f2e72b1eece650c2b2d6a0f8"
        }
      ]
    }
  ]
}
