{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mobile-sdk-bff/0.7.0/mobile-sdk-bff-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "mobile-sdk-bff",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-release.aar",
          "url": "mobile-sdk-bff-android-0.7.0.aar",
          "size": 156254,
          "sha512": "62e34417a8f53c2f37d76c6824e752511c9a78a406defebd3e650003ca66d01cf8c23239b5fd94f4c958274dbdc2dbe1c6ae338cdf9cf2451dc9b9ff43a3e33f",
          "sha256": "48135445b2bf1563287739929858004a757f2caeb7f9c99335a45807f86dcdbe",
          "sha1": "424981c09e6b78df50970bac892302c8106fd4a7",
          "md5": "31690997150e77436bb5043704ea0051"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.20.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-release.aar",
          "url": "mobile-sdk-bff-android-0.7.0.aar",
          "size": 156254,
          "sha512": "62e34417a8f53c2f37d76c6824e752511c9a78a406defebd3e650003ca66d01cf8c23239b5fd94f4c958274dbdc2dbe1c6ae338cdf9cf2451dc9b9ff43a3e33f",
          "sha256": "48135445b2bf1563287739929858004a757f2caeb7f9c99335a45807f86dcdbe",
          "sha1": "424981c09e6b78df50970bac892302c8106fd4a7",
          "md5": "31690997150e77436bb5043704ea0051"
        }
      ]
    }
  ]
}
