{
  "formatVersion": "1.1",
  "component": {
    "url": "../../search-usecase/0.9.1/search-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "search-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "search-usecase-iosSimulatorArm64Main-0.9.1.klib",
          "url": "search-usecase-iossimulatorarm64-0.9.1.klib",
          "size": 4807,
          "sha512": "fc0a9700cc9aa97989b230a97f58a719ca0238fdbc4d617d137cd2702cd8780ec920ee21c02acad4c05bd066b621188503a4146e971159504a8c430358e81a93",
          "sha256": "270716e47dd008fa905ef14eb607d94c871bd003d206c9d804d07a85da981b77",
          "sha1": "373284353e521c7a3e71e69a8959c0488c242c0e",
          "md5": "ec5ab615bd4f78f5098dcf7048dba0de"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "search-usecase-iossimulatorarm64-0.9.1-metadata.jar",
          "url": "search-usecase-iossimulatorarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "3df85b1acd6ee4963abdf261aa32f3bd4ab8eab19806ddc4c8fba82f6f906b2b5b575ec96274210c2ec3fa6385c43b4273177aca52886691e8003c665d36c2e9",
          "sha256": "bc4c2fb1600ddbd7e4e169613ada31ca2334a4b6d369f3bbde6ba0f11528a0b4",
          "sha1": "4b1eedf7790694604cc1fd3241e3ecced6656855",
          "md5": "3183e2a6e01dc6e2f2f37e85fc80b14f"
        }
      ]
    }
  ]
}
