{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-domain/0.9.0/countries-info-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iosSimulatorArm64Main-0.9.0.klib",
          "url": "countries-info-domain-iossimulatorarm64-0.9.0.klib",
          "size": 15202,
          "sha512": "4259fe5d91e7896aab181f88955964bf1fa702704e142efd4afdd4c345a4ad80dd15482109c3801a78870be959460f556e099ce9ccfd63e1d329b073ad5a6998",
          "sha256": "dafd1aac2e279a98b5d37e94c48e6349a3403aa2306a0b1bab27b02a2eb3b879",
          "sha1": "7f2568f0d05b9130d36433751d6fd5e9f88e0bae",
          "md5": "3b6a4984c0b84b414ed8750a20121a89"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-domain-iossimulatorarm64-0.9.0-metadata.jar",
          "url": "countries-info-domain-iossimulatorarm64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "6187e0e2297a7cbf699f1609581f085963e6144605c6f0b63866e438c165bd0715dac24269568cfa745d0e8fb48a20548711626337283e057b90a130565dc7e8",
          "sha256": "231d8391816f0128facda5339ecd50c29a6d0f85c4404d6d575a16d81f7766a7",
          "sha1": "739f1f83115e8fa13578f73945e3cd3f5d0188f2",
          "md5": "302549466abd31e221e1fbb5d8f406be"
        }
      ]
    }
  ]
}
