{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api-config-environment/0.7.1/sdk-api-config-environment-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api-config-environment",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-environment-iosSimulatorArm64Main-0.7.1.klib",
          "url": "sdk-api-config-environment-iossimulatorarm64-0.7.1.klib",
          "size": 7065,
          "sha512": "867575afe01a36405292a08959c5f44e2cd2f53601d3689ac3eff3f2c7b1e149a2eaa444aa5e059945b059b23b5586bd86cd2904c679c8267ddd8f037e868a83",
          "sha256": "98fa68fe6b12295262e828135a4c3c73f45efee197058f2e67284ca6a5e4c159",
          "sha1": "34103f68fbc73361d7ab98cce913ec652dd3978a",
          "md5": "e4c1357ca307d607d5c6142041932976"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-bff",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-config-environment-iossimulatorarm64-0.7.1-metadata.jar",
          "url": "sdk-api-config-environment-iossimulatorarm64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "b8cb7e83c6948656d4afdc6b9639fdc74e1c305c4d81096184ad75fe528a28c3b75e40c1d5f1a4d4b96b72ef6defe01f5f4a9bc8343b9bf4875d2fe55480a0f6",
          "sha256": "9b1f320c6cb9b64e4f998cf9fb4dd6204cbfe4b1b39df69a93f37c4aae43e960",
          "sha1": "a0cefeebee8c3fbeaeab888bc78dea657e54e0a3",
          "md5": "e33fb16848eb8ecc0425c768760c88e2"
        }
      ]
    }
  ]
}
