{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amenities-usecase/0.9.0/amenities-usecase-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "amenities-usecase",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosX64Main-0.9.0.klib",
          "url": "amenities-usecase-iosx64-0.9.0.klib",
          "size": 4753,
          "sha512": "1c466075134551f9ff9edca64c597b06e2b7e5216cb02d4fe3f92a5053b3124df7020665e40535b14aa5c3ea734b09828b49a1af45e648e7e1a5bb283fc37746",
          "sha256": "de1b12719d19458b34f390f02b361dabc1ba8071780f403ec22f2d896329f9fe",
          "sha1": "6faa47937531c34052c68b71d70d2e48e28a2e5e",
          "md5": "8769b588f6f6a2017be4d01b6b296a22"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "amenities-domain",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-data",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "amenities-usecase-iosx64-0.9.0-metadata.jar",
          "url": "amenities-usecase-iosx64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "5d9c75664c6a7039fa94d3a36d59f7a5bac6f09cc8a3d0d71eca1aedf33baeb9533d4b572cb8c6973d08da902c076da4917e929d68d37a0526c4ca79f3a5af25",
          "sha256": "bd1e4ca08b555c3c2016bb388729cb4c14a2fde217af3bb8dc4a165ad2a77089",
          "sha1": "a0f5e942a9e91faef3dee56229dc24df5c21c606",
          "md5": "7268842a90bcf901d73bc12d41fbdb49"
        }
      ]
    }
  ]
}
