{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pricing-domain/0.8.0/pricing-domain-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "pricing-domain",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iosSimulatorArm64Main-0.8.0.klib",
          "url": "pricing-domain-iossimulatorarm64-0.8.0.klib",
          "size": 23211,
          "sha512": "60af00e075f2cb76f8da7affcc75eb9290a38876202c16799b1f911cf578edb20641c7b65cd43e393997159cfb1aad4f89e98ddcfe7fcdf21723f4704cb72f61",
          "sha256": "e07ba48aae814ae1ade70ba270396ecbdd55b1f44cdfa78cfd29263b1eb696f7",
          "sha1": "9659752f724d1f3fece3b31b838f57faa3fce0d3",
          "md5": "3f49d3cf25e76c2c3d149b154ea81057"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "pricing-domain-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "pricing-domain-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "37ea9c0a8966540d0842c48016fe4c0ecaade68c8b3ac35896c02f6896cb2031cbe852c66276e8eb4116bb685b02d40cff4a9697992ca79b957a6fbfc0363c6a",
          "sha256": "dd645edd1e4401de7a368f39a55878b06470249143d6064583a276baead8bdfd",
          "sha1": "3eebca1359ee63fe71c1d69b6223b20b5835ad3f",
          "md5": "2bf6243c0ab663f53cde848be430ab8e"
        }
      ]
    }
  ]
}
