{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "reservations-usecase",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservations-domain",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-data",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "reservations-usecase-metadata-0.5.1.jar",
          "url": "reservations-usecase-0.5.1.jar",
          "size": 2503,
          "sha512": "7cad149295df89ef88f9fe5a6fff5fe2bf4431c8b6845347b111dd76c9915fbc1c8661ff971c61b1602d002169c98c1ce325d798bf146bdb099a29bcee4311f8",
          "sha256": "096ac9606baf2a6188cc7f4e81efe831ffbd4305c17db2c451d8b4924dcf04f6",
          "sha1": "5355bda262ff6a28af5adccd89b735690af0c7ff",
          "md5": "868568fe4365fd753abaa427a4eb2d17"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../reservations-usecase-android/0.5.1/reservations-usecase-android-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "reservations-usecase-android",
        "version": "0.5.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../reservations-usecase-android/0.5.1/reservations-usecase-android-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "reservations-usecase-android",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../reservations-usecase-iosarm64/0.5.1/reservations-usecase-iosarm64-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "reservations-usecase-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../reservations-usecase-iosarm64/0.5.1/reservations-usecase-iosarm64-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "reservations-usecase-iosarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../reservations-usecase-iossimulatorarm64/0.5.1/reservations-usecase-iossimulatorarm64-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "reservations-usecase-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../reservations-usecase-iossimulatorarm64/0.5.1/reservations-usecase-iossimulatorarm64-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "reservations-usecase-iossimulatorarm64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../reservations-usecase-iosx64/0.5.1/reservations-usecase-iosx64-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "reservations-usecase-iosx64",
        "version": "0.5.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../reservations-usecase-iosx64/0.5.1/reservations-usecase-iosx64-0.5.1.module",
        "group": "com.mozio.mobile",
        "module": "reservations-usecase-iosx64",
        "version": "0.5.1"
      }
    }
  ]
}
