{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mobile-sdk-bff/0.2.0/mobile-sdk-bff-0.2.0.module",
    "group": "com.mozio.mobile",
    "module": "mobile-sdk-bff",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-release.aar",
          "url": "mobile-sdk-bff-android-0.2.0.aar",
          "size": 156193,
          "sha512": "298df804f54e2d2e3285b7aea927b73b8f047ec075d2627555485c7fc3c9e7f40b6cdd591acd698491e6b16b5f5f52a1fded53f64765769a3c3150047f36637f",
          "sha256": "4b6fd7b5e8fcd034052506f57dca83a39c222a93368d7674f12e3ffd262def0e",
          "sha1": "5797ac153022b72d0c6f20a1ac0a0a196bc118a3",
          "md5": "041f7762045f37c0e6e88f7cebd45e50"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-http",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-bff-release.aar",
          "url": "mobile-sdk-bff-android-0.2.0.aar",
          "size": 156193,
          "sha512": "298df804f54e2d2e3285b7aea927b73b8f047ec075d2627555485c7fc3c9e7f40b6cdd591acd698491e6b16b5f5f52a1fded53f64765769a3c3150047f36637f",
          "sha256": "4b6fd7b5e8fcd034052506f57dca83a39c222a93368d7674f12e3ffd262def0e",
          "sha1": "5797ac153022b72d0c6f20a1ac0a0a196bc118a3",
          "md5": "041f7762045f37c0e6e88f7cebd45e50"
        }
      ]
    }
  ]
}
