{
  "formatVersion": "1.1",
  "component": {
    "url": "../../locations-domain/0.7.0/locations-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "locations-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosX64Main-0.7.0.klib",
          "url": "locations-domain-iosx64-0.7.0.klib",
          "size": 34182,
          "sha512": "1c7291d9da013e7a7fd67cc8f8c0d3c1420fb35c894aedf31b5953fef4c0ec5f4eb8e8d0b7d3748500fe47b5be08f2df0d1999e805e28a6b73e090868ab72411",
          "sha256": "a3dc4e07278056d012471b759481e2dcac441531369800ee22c50a395795c4dd",
          "sha1": "1737784c378131fb8200d6b9c7d9fa40d622081e",
          "md5": "c6724c3f0d6b39c00f1759616b27076d"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosx64-0.7.0-metadata.jar",
          "url": "locations-domain-iosx64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "53589b59395f643cce37178ef3beaf001c45fc013859075d26193daa53011610c778d505de0a59b13a5f1daa4652e6a066ed51236ea542eb3c8817b232c60502",
          "sha256": "8143cc9bffa01d531a23603ffb0eee3dcdf874edbe7d161d6529373401683a04",
          "sha1": "28c0c6a316c3f043050426de41e612c7fd30066d",
          "md5": "d47ba66c0f47268a95a19aed2bf4be5d"
        }
      ]
    }
  ]
}
