{
  "formatVersion": "1.1",
  "component": {
    "url": "../../countries-info-usecase/0.7.1/countries-info-usecase-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "countries-info-usecase",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-usecase-iosX64Main-0.7.1.klib",
          "url": "countries-info-usecase-iosx64-0.7.1.klib",
          "size": 4879,
          "sha512": "f645e635d637cc2c80212c29d60a6985b9122dc49058035ee0bf5a9f3f6e551ba7c067145de31a7dbc91b56a68077dce8d2fe8348734c3d180de747d29e17463",
          "sha256": "ecfa76df109a198fa00970a4659a350a6a15985e4627fc9abca22c591455c2f5",
          "sha1": "078134cee5bda1ea1b1544acdc1d29c2ec87fa75",
          "md5": "18ec4685785067139d7f648a46d9dd0b"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-domain",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-data",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "countries-info-usecase-iosx64-0.7.1-metadata.jar",
          "url": "countries-info-usecase-iosx64-0.7.1-metadata.jar",
          "size": 261,
          "sha512": "f1152f7bfbb68f56d98eb77258ecfad86ed7f793950e6ececd9ccf60655a62c5186746f788aa3ef2db8abc85b847a627d5e6e7f419821923e5533c7b419df804",
          "sha256": "5a54766986b6670f5d2f577ee3162944049265d43c0ecaeb81e97670eeede454",
          "sha1": "6647f3028890d2cf821e616f589a227bcfd780dd",
          "md5": "f24c023e18dc9c1b4a1794c524602fc6"
        }
      ]
    }
  ]
}
