{
  "formatVersion": "1.1",
  "component": {
    "url": "../../local-storage-data/0.7.1/local-storage-data-0.7.1.module",
    "group": "com.mozio.mobile",
    "module": "local-storage-data",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosArm64Main-0.7.1.klib",
          "url": "local-storage-data-iosarm64-0.7.1.klib",
          "size": 8748,
          "sha512": "ea5535a1cac0d72c6ce80c52cf58e40f4ea54bf76651b732619fc816df504454354e9e3727065dc700bca3beb9862cee576cc470e927cf2d8284d8d838f8573c",
          "sha256": "60ef442db8f04a5fe20cdb7c0fc1dc89cbac0608b2bcfd03d3ed51f4a57e5264",
          "sha1": "7e4d7f0260683e1ac74841bd650ff8bd6285a313",
          "md5": "9cecc5431e8b59fbed270aa7f489eb60"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-serialization",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.russhwolf",
          "module": "multiplatform-settings-coroutines",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "local-storage-data-iosarm64-0.7.1-metadata.jar",
          "url": "local-storage-data-iosarm64-0.7.1-metadata.jar",
          "size": 2476,
          "sha512": "41fb621bfb94421e60218dc6501dc0db5da2db56611674762634686a451fa51ca929b1e25516e8502c6756e8587ad91d1c7f01994eb811345a00932195e5a596",
          "sha256": "42e132492135dac220bc54a70037755b7e01fef99c2eb4ab3ec0208fb9bb43dc",
          "sha1": "a3b8d6a5cbbc537bf2efaafafaf20848ca7ecba5",
          "md5": "042d9f58c138984bfb3e2a7b1aea0c3e"
        }
      ]
    }
  ]
}
