{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-api/0.8.0/sdk-api-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "sdk-api",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-analytics",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-di",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-iosX64Main-0.8.0.klib",
          "url": "sdk-api-iosx64-0.8.0.klib",
          "size": 11379,
          "sha512": "0a34014f83b645e5ea8fe139d3f1ce0c8284ba4a4d465529a365074d287f18187934d1549211d63bca1f4c3a6ca4800958a77cc19f037611243b9173853d4e8c",
          "sha256": "a5114fce87d84fe53a7220fe103f3f0d3942a2b3d9f8131546decbd2d9e341df",
          "sha1": "87dac318232f2a293b798c5a4bc4edc7ae3b5974",
          "md5": "d7d6a685945f12f536e0a46013cbbd0c"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "locations-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "search-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "searched-locations-history-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "amenities-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "pricing-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "countries-info-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "coupons-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "stripe-payments-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "authentication-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-profile-usecase",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api-config",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-analytics",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-di",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-api-iosx64-0.8.0-metadata.jar",
          "url": "sdk-api-iosx64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "e705f50d72977aec8e0bbc4ecfa7405991f8909b0452019bdc626970368bc194d93114f38146b117554edb465415326c7c825f7d3663138b109c91c3702f6d36",
          "sha256": "3651e0713a449d58575e4ac4f704d545f60df79eaa8e56d7a56e766c4c06a550",
          "sha1": "7d7356849bcfb266dc33704def5166af47922a78",
          "md5": "4851f438803c5eba718b239ff594fdbb"
        }
      ]
    }
  ]
}
