{
  "formatVersion": "1.1",
  "component": {
    "url": "../../reservations-usecase/0.8.0/reservations-usecase-0.8.0.module",
    "group": "com.mozio.mobile",
    "module": "reservations-usecase",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservations-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservations-usecase-iosSimulatorArm64Main-0.8.0.klib",
          "url": "reservations-usecase-iossimulatorarm64-0.8.0.klib",
          "size": 4865,
          "sha512": "a1306528729a924af846fc16458c4e6ff4e5a14fb3a0bfc3a5140376d4048ad9c4fa31574dee6de6c18975d845742ae552ed295b97183cade841e046e07ee721",
          "sha256": "07b69ff833491a70b0631d0d66029f7c0bf7a3fd5f0839db0d138f654efb0b53",
          "sha1": "588d26d51b2069d52d2c193549029bf8ce8b0fe1",
          "md5": "311628e54607744715f454b5df8e6196"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "reservations-domain",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "reservations-data",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "reservations-usecase-iossimulatorarm64-0.8.0-metadata.jar",
          "url": "reservations-usecase-iossimulatorarm64-0.8.0-metadata.jar",
          "size": 261,
          "sha512": "0e1984899db0759262066f4627b5fc10ad12b034719395003a54572ea06267cfc27e749663a28aa6ab0066cc5c7a77b044c2a73b1b1aee6f4f493505cf5be2f1",
          "sha256": "c5dbbabbef193b8a32a0411585e9606b0d3e89cfad5d9a8c40644900a7ac3506",
          "sha1": "726c7d6b3f4d30992444ca05fe3673073f0095c2",
          "md5": "011e71bd3292b026605e053dccfdbab8"
        }
      ]
    }
  ]
}
