{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile.android",
    "module": "myaccount-ui",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "myaccount-ui-0.1.0.aar",
          "url": "myaccount-ui-0.1.0.aar",
          "size": 134076,
          "sha512": "751772ad9ce0ea3a2b681de09e9c5d07bb303020b3a90e629cefd9767587f6a353dbdfe37d95ddeb7e27cbb2c0cd83bfd9dc264de55127613f876a17adf18f66",
          "sha256": "c0833c2991bd4b5d5b50e989bdabc36d6475f5e3248c101fc92f4b6ab31334a6",
          "sha1": "93f707d04e841a48f9bd4b06ce0eab5741615c17",
          "md5": "3536db2b3544c1f00e6b4825bb92461c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "core-ui",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "authentication-ui",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "country-phone-ui",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "myaccount-ui-0.1.0.aar",
          "url": "myaccount-ui-0.1.0.aar",
          "size": 134076,
          "sha512": "751772ad9ce0ea3a2b681de09e9c5d07bb303020b3a90e629cefd9767587f6a353dbdfe37d95ddeb7e27cbb2c0cd83bfd9dc264de55127613f876a17adf18f66",
          "sha256": "c0833c2991bd4b5d5b50e989bdabc36d6475f5e3248c101fc92f4b6ab31334a6",
          "sha1": "93f707d04e841a48f9bd4b06ce0eab5741615c17",
          "md5": "3536db2b3544c1f00e6b4825bb92461c"
        }
      ]
    }
  ]
}
