{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-profile-domain/0.9.0/user-profile-domain-0.9.0.module",
    "group": "com.mozio.mobile",
    "module": "user-profile-domain",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-domain-iosX64Main-0.9.0.klib",
          "url": "user-profile-domain-iosx64-0.9.0.klib",
          "size": 24938,
          "sha512": "f55585a1bdf2d56b79da8b440d5d8cbd2bb9b58fb1d01cabab8738f5136b8c3397316db0d2134309db39aaee90bf91d671c637e17cac1be674ce8e364a9534af",
          "sha256": "e0f91d6bdc14510a2890b860ef22aea310af2700a5ba81a74bfd1d107ef0ac9e",
          "sha1": "b2cd59f79ded73acc86073d6353c5961d358314c",
          "md5": "78316ed14887f463a8fb6e0702e23935"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "user-profile-domain-iosx64-0.9.0-metadata.jar",
          "url": "user-profile-domain-iosx64-0.9.0-metadata.jar",
          "size": 261,
          "sha512": "4f68f7e5990db6716c18e4db672b2fe15ee3989eb3667c2c69d055faaf3ec3567490fef1b22afaf8f80c1411c89ae7998c275303b30de818df30e1f657daea9c",
          "sha256": "05f10f2e23ed5b93d5b53a606f34ae6e11e4b4d51651842fd1d07b2c8a50515d",
          "sha1": "a3b555009c217d4ec4881dad42a0eb5d86239e4b",
          "md5": "eca772c1563daec430b0ddcae2c4f053"
        }
      ]
    }
  ]
}
