{
  "formatVersion": "1.1",
  "component": {
    "url": "../../user-location-usecase/0.9.1/user-location-usecase-0.9.1.module",
    "group": "com.mozio.mobile",
    "module": "user-location-usecase",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-location-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-location-usecase-iosArm64Main-0.9.1.klib",
          "url": "user-location-usecase-iosarm64-0.9.1.klib",
          "size": 4801,
          "sha512": "fdaee4daa5978d5edfa857c90309bb7f41e6b5a87444ccdb0a2e7ee013bffdaa7d7c3d3de30e39d7a507d0efaae3390a7f396d333469be91ddb7c04805c814df",
          "sha256": "c8fb4d719bab020edfbdd9ae9582cb2e97d6ba1804a8007183083e1b4e3d59f5",
          "sha1": "d765c060c5c9bd6f8b312688e52ce3c6d23ef8a4",
          "md5": "17bf6bf327ee017974fc6421639f4339"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mozio.mobile",
          "module": "user-location-domain",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-data",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        }
      ],
      "files": [
        {
          "name": "user-location-usecase-iosarm64-0.9.1-metadata.jar",
          "url": "user-location-usecase-iosarm64-0.9.1-metadata.jar",
          "size": 261,
          "sha512": "6865f66ad0a4c76dd7dc3f179130e557c34eebbea15d2a3049ba2145739c64a86dbddcaf316b3d67b79c90e841ef448a82efb7400cfe6eaedb667aba2d2ad784",
          "sha256": "31fa3643af57655c945c82afdf9483b095aa70b914ad4f731a5ce2d3db8a0302",
          "sha1": "00e55808f8c911de2a736d85588f26bb5184d01c",
          "md5": "00adedd339851fe3031d2bb65b6853c6"
        }
      ]
    }
  ]
}
