{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile",
    "module": "sdk-di",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-di-metadata-0.7.0.jar",
          "url": "sdk-di-0.7.0.jar",
          "size": 2928,
          "sha512": "b1eebdc0d82b6f1ff43ab65f71dc8ac11493c0b8a614df932c001652ef3e89b9623ec1d8da7282d60c52ee0807effd3dfc625ce54df4d44b9f54c7f03cc04181",
          "sha256": "c51fd67b85f1b4934372c760f51808d565a911a4bc2fe3cfb163b0e537da0792",
          "sha1": "05a94f3cf43354953024079dfdef98099ecf891b",
          "md5": "21812563090d90b6310bd8cdaaaa0c13"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-di-android/0.7.0/sdk-di-android-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-di-android",
        "version": "0.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-di-android/0.7.0/sdk-di-android-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-di-android",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-di-iosarm64/0.7.0/sdk-di-iosarm64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-di-iosarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-di-iosarm64/0.7.0/sdk-di-iosarm64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-di-iosarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-di-iossimulatorarm64/0.7.0/sdk-di-iossimulatorarm64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-di-iossimulatorarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-di-iossimulatorarm64/0.7.0/sdk-di-iossimulatorarm64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-di-iossimulatorarm64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-di-iosx64/0.7.0/sdk-di-iosx64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-di-iosx64",
        "version": "0.7.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-di-iosx64/0.7.0/sdk-di-iosx64-0.7.0.module",
        "group": "com.mozio.mobile",
        "module": "sdk-di-iosx64",
        "version": "0.7.0"
      }
    }
  ]
}
