{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mozio.mobile.android",
    "module": "search-rides-ui",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "search-rides-ui-0.9.0.aar",
          "url": "search-rides-ui-0.9.0.aar",
          "size": 603770,
          "sha512": "73a3e9e76b4a3121bb3bb95d4d197844bfc803f17a6d9b782d88fa638de227172afb2d02d47f5e20183a2e551f133f903f502c52739f6c3aa9c65c6722cba23f",
          "sha256": "3088b4f01d52b2be69d90629d2111d3ab5dcc168d42dbad113592315c456a98b",
          "sha1": "4f0a1e5d0b160ccfe4734086bddcf7344157871d",
          "md5": "31443f658587893c3f6f0d72bb2d3895"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-bom",
          "version": {
            "requires": "4.1.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "core-ui",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "prebook-ui",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "prebook-bookingflow-ui",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile.android",
          "module": "googlemaps-ui",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-api",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "user-location-usecase",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.7"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose-viewmodel"
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor3",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-compose",
          "version": {
            "requires": "6.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-maps",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-ktx",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "com.google.maps.android",
          "module": "maps-utils-ktx",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "sdk-analytics",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "search-rides-ui-0.9.0.aar",
          "url": "search-rides-ui-0.9.0.aar",
          "size": 603770,
          "sha512": "73a3e9e76b4a3121bb3bb95d4d197844bfc803f17a6d9b782d88fa638de227172afb2d02d47f5e20183a2e551f133f903f502c52739f6c3aa9c65c6722cba23f",
          "sha256": "3088b4f01d52b2be69d90629d2111d3ab5dcc168d42dbad113592315c456a98b",
          "sha1": "4f0a1e5d0b160ccfe4734086bddcf7344157871d",
          "md5": "31443f658587893c3f6f0d72bb2d3895"
        }
      ]
    }
  ]
}
