{
  "formatVersion": "1.1",
  "component": {
    "url": "../../locations-domain/0.7.0/locations-domain-0.7.0.module",
    "group": "com.mozio.mobile",
    "module": "locations-domain",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosArm64Main-0.7.0.klib",
          "url": "locations-domain-iosarm64-0.7.0.klib",
          "size": 34195,
          "sha512": "02b15de9a8d7fb8f5c9773f8de17ae1d2fab772e3ebf9fca2f0170e4c13a9658cbf1eb9bbe0cdac37608ed1ecac1bcf01f1631deb7f23da6882c2fc292b8ac22",
          "sha256": "a10fa74fef645593eeb600c9af4265f1b0b750e803ba154a9b92afcef59cf797",
          "sha1": "d2ad6235eb7a9b4269b434d3a9358b43ac76737f",
          "md5": "2e817496c46a8d022cfd76cfc00f0bf7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-util",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.mozio.mobile",
          "module": "core-coroutines",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "locations-domain-iosarm64-0.7.0-metadata.jar",
          "url": "locations-domain-iosarm64-0.7.0-metadata.jar",
          "size": 261,
          "sha512": "53589b59395f643cce37178ef3beaf001c45fc013859075d26193daa53011610c778d505de0a59b13a5f1daa4652e6a066ed51236ea542eb3c8817b232c60502",
          "sha256": "8143cc9bffa01d531a23603ffb0eee3dcdf874edbe7d161d6529373401683a04",
          "sha1": "28c0c6a316c3f043050426de41e612c7fd30066d",
          "md5": "d47ba66c0f47268a95a19aed2bf4be5d"
        }
      ]
    }
  ]
}
